### ISSUE TITLE
selected-item returns null object when user select the selected item

### ISSUE THREAD

**Issue by suleymanccelik** [PolymerElements/iron-list#100]
If user selects an item which was selected before, selected-item of iron-list returns null object. I review source code of iron list, when user selects an item from iron-list, _selectionHandler method is called and _selectionHandler method calls toggleSelectionForItem method, selected-item is toggled and returns null. multiSelection property of my iron-list is false when I am using iron-list.  

_selectionHandler method : https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1240
toggleSelectionForItem method: https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1192
There is a workaround for my problem in the following http://stackoverflow.com/a/32573007/903973.

**Comment by blasten** [comment]
@suleymanccelik yes. This is the expected behavior for `selection-enabled`. Why would you like to disable this behavior? After all, it's a very common UI pattern to tap to select and tap again to deselect an item.

**Comment by fenerlee1907** [comment]
@blasten I do not think it is a common pattern. In my personal opinion, this feature is added to support multiple selection purpose. While using multiple selection (like in standard <select> component) clicking on the selected item should deselect it; yes it is correct. But when I use iron-list without multiple-selection option, I do not expect deselection when I clicked the selected item. A "toggleSelection" or something like this would be very useful.

**Comment by suleymanccelik** [comment]
When I disable selection-enabled behavior, selected-item returns null for every select event.

**Comment by blasten** [comment]
@fenerlee1907 I think we could add an attribute to handle this case.

**Comment by blasten** [comment]
@fenerlee1907 Here's an example of how you can achieve this behavior: http://jsbin.com/bazivo/edit?html,output

**Comment by zoechi** [comment]
I find this quite cumbersome. I consider this the default behavior for a single-selection list.
