### ISSUE TITLE
blank screen during scroll (long lists)

### ISSUE THREAD

**Issue by debianw** [PolymerElements/iron-list#102]
I've been testing this on mobile safari and chrome mobile. During long scrolls you'll see how items start disappearing from the screen and come back in a few seconds.

Here is a screen capture I did using Android and chrome

https://www.dropbox.com/s/7w0rtllyvtse08s/iron-list-render.mp4?dl=0

**Comment by blasten** [comment]
@debianw is this a simulator or what device did you use?

**Comment by debianw** [comment]
Real device, I only test on real devices

**Comment by debianw** [comment]
I tested this on real devices (HTC one and iPad mini). (Android 5.0.2, iOS 8, iOS 9). I noticed this since Polymer/core-list now I see iron-list has the same issue.

There's no issue if you scroll down or up slowly, but the idea of a native scroll is that the user goes to the bottom or to the top as fast as possible.

**Comment by ShashankDesai** [comment]
Same problem here. I'm using cordova to package it into an android app.
Is there any way to pre load some list items beyond those that fill the viewport?

**Comment by blasten** [comment]
This issue is a limitation of an old version of webkit. I'm surprised that you see this issue in Chrome for android. What version of Chrome are you running?   
In IOS, Chrome/Firefox or any native app using a web view have this issue. However, Mobile Safari (the app) should work fine.

**Comment by blasten** [comment]
Please reopen if this issue is still happening.

**Comment by hereiam133** [comment]
This is still happening on real devices in a wrapped Polymer cordova app

**Comment by debianw** [comment]
yes, I don't know why this was closed. I didn't see any fix on this.

**Comment by hereiam133** [comment]
I am actually also seeing this issue in the latest version of chrome on my mac as well.

**Comment by blasten** [comment]
@hereiam133 on mac? Do you have a demo? I can't reproduce it on https://elements.polymer-project.org/elements/iron-list?view=demo:demo/collapse.html&active=iron-list

**Comment by hereiam133** [comment]
Ok so I have narrowed the issue down. The problem is when you have dynamic content and large image file sizes. The proper behavior would be using iron image with the preload and a background color or something as a placeholder, but what actually happens is it cant load in the images fast enough and you get a blank screen, instead of showing the placeholder while waiting for the images to load.

**Comment by blasten** [comment]
@hereiam133 are you using `<img>`?

**Comment by hereiam133** [comment]
No I am using iron-image

**Comment by hereiam133** [comment]
any update? using iron-list on a cordova app has major issues when scrolling. long ui render time and blank white sections until render completes.

**Comment by blasten** [comment]
@hereiam133 do you have a jsbin? I can't reproduce the issue in the demos https://elements.polymer-project.org/bower_components/iron-list/demo/index.html The only limitation is for old versions of webkit that don't support `-webkit-overflow-scrolling` As last time I tested, `UIWebView` in iOS doesn't support that CSS property, so you will see a blank screen while scrolling... but Safari (the app in IOS) should be fine unless there's something wrong with the setup.

**Comment by hereiam133** [comment]
We are seeing the issue on cordova wrapped android app, latest version of cordova on all test devices. Kitkat and up.

**Comment by rubenstolk** [comment]
This should be reconsidered @blasten.

**Comment by thomasvogel** [comment]
The issue still exists! Tested with 6000 list entries on Chrome Version 62 and IE 11

**Comment by komal-eCommera** [comment]
I am still facing this issue, I have a page with a list of line items having product images. when user scroll blank space is visible for fractions of a second.

**Comment by armujahid** [comment]
This issue should be reopened.

**Comment by ramiroaisen** [comment]
Still not solved, but this is a Chrome issue, not a polymer issue
