### ISSUE TITLE
Support headers and footers

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/iron-list#103]
Unique fixed items at the start/end of the list - example (screenshots of current behaviour below):

```
<iron-list items="[[items]]">
  <div>I'm a list header</div>

  <template>
    <div>Item <span>{{index}}</span></div>
  </template>

  <div>I'm a list footer</div>
</iron-list>
```

![screen shot 2015-09-18 at 1 54 24 pm](https://cloud.githubusercontent.com/assets/134568/9970883/09e3f8c2-5e0d-11e5-82dc-a151e52153fd.png)

![screen shot 2015-09-18 at 1 55 34 pm](https://cloud.githubusercontent.com/assets/134568/9970888/0f088598-5e0d-11e5-9990-d3b0d2715650.png)

**Comment by WrinklyNinja** [comment]
You could do this with an external scroll target being a parent element, and put the header/footer as siblings of the iron-list, but AFAIK external scroll targets haven't yet made the jump to 1.0 (I'm waiting on the support myself)...

**Comment by blasten** [comment]
@hawkett 
@WrinklyNinja is right, external scroll target should help you to achieve this. Give it a try in: https://github.com/PolymerElements/iron-list/tree/custom-scroller
