### ISSUE TITLE
What's the equivalent of scrollTarget in core-list?

### ISSUE THREAD

**Issue by aahoo** [PolymerElements/iron-list#104]
In the documentation for iron-list it says:

> Important: iron-list must ether be explicitly sized, or **delegate scrolling to an explicitly sized parent**.

How can I delegate scrolling to parent?

**Comment by blasten** [comment]
@baazoo There's a PR for this feature. https://github.com/PolymerElements/iron-list/pull/85 It should be merged soon. cc @kevinpschaaf
