### ISSUE TITLE
Variables in the parent scope are not passed during initialization.

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-list#107]
This issue was also reported in https://github.com/PolymerElements/iron-list/issues/82,  https://github.com/PolymerElements/iron-list/issues/75  and  https://github.com/PolymerElements/iron-media-query/issues/15#issuecomment-143483583.

jsbin: http://jsbin.com/lezada/edit?html,output

@kevinpschaaf if the items are set synchronously, then it works as expected. I believe this is the reason why the smoke test works. Is there anything we forgot to do?

**Comment by kevinpschaaf** [comment]
Root-caused to https://github.com/Polymer/polymer/blob/master/src/lib/template/templatizer.html#L385-L389; parent props need to be pulled from the `<template>` rather than the `<iron-list>` element.

**Comment by kevinpschaaf** [comment]
@blasten https://github.com/Polymer/polymer/issues/2504 is now resolved; can you confirm in `iron-list` and close?  Thanks.

**Comment by blasten** [comment]
It's confirmed! Thanks for fixing it!
