### ISSUE TITLE
After deleting items, scrollToIndex yields empty space

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/iron-list#108]
Repro case: a list of items that calls `scrollToIndex(length - 1)` when an item is deleted.
http://jsfiddle.net/s6f029j3/4/

Delete the top item in the viewport 7 times (i.e., you'll delete A, then W, V, U, T, S, R).

Result: http://imgur.com/mhdqspe.png

All but the bottom two items disappear. After scrolling up, then back down, you can make 2 more items appear, but the remaining ones never come back, even though there are still 19 items in the model.

**Comment by blasten** [comment]
This issue is confirmed...
