### ISSUE TITLE
Unable to display list inside neon-animated-pages of paper-dialog

### ISSUE THREAD

**Issue by motss** [PolymerElements/iron-list#110]
Please help look into this problem as many ways have been tried to generate the list even giving the `iron-list` its explicit CSS height. However the list will show up if `neon-animatable` is removed.

Structure of the code:-
```
. paper-dialog
.. neon-animated-pages
... neon-animatable
.... iron-list
```

[Code URL](http://jsbin.com/bacicejako/edit?html,output)

**Comment by blasten** [comment]
This issue seems to be related to https://github.com/PolymerElements/neon-animation/issues/60

**Comment by ericdes** [comment]
Same issue with this structure:
`
. iron-pages
.. section
... neon-animated-pages
.... iron-list
`
I set a fixed height to the iron-list (following motss' findind) to display the list items.

**Comment by ronnyroeller** [comment]
+1

**Comment by motss** [comment]
Just an update! Try firing at `iron-list` after opening the dialog (or whenever the dialog is made visible). Click here for the [working example](http://jsbin.com/fezawanufe/edit?html,console,output).

**Comment by ziszo** [comment]
< neon-animated-pages >
        < paper-dialog >

Dialog closes after a few seconds.
Is there any work-around for this issue?
