### ISSUE TITLE
Method to select all

### ISSUE THREAD

**Issue by bpinney** [PolymerElements/iron-list#124]
For iron-list components where multiSelection is true, a method for selecting all selectable items in the list would be helpful.

**Comment by zoechi** [comment]
There are `selectedItem` and `selectedItems` for (`multiSelection` `false`/`true`)
I think there should be a `selectItems(array)` in addition to the existing `selectItem(item)`. Then you can just pass your entire items array to `selectItems(....)` to select all, or a subset of all to select some.

**Comment by blasten** [comment]
That'd be useful. For now you can use:
```js
function selectAll(list) {
  list.items.forEach(function(item) {
    list.selectItem(item);
  });
}

// selectAll(myList);
```

**Comment by blasten** [comment]
This is out of scope since it's easy to add the behavior in user-space.

**Comment by dman777** [comment]
What about unselecting all items?
