### ISSUE TITLE
Allowing altering the overflow-x property.

### ISSUE THREAD

**Issue by dlmma** [PolymerElements/iron-list#126]
It would be very nice if instances of iron-list with no external scrolltarget could set the overflow-x CSS property to hidden programmatically via an element property or something like that. Or, overflow-x could be hidden as default which would make sense since iron-list expects a vertical layout.

**Comment by blasten** [comment]
```css
iron-list {
 overflow-x: hidden;
}
```
would that be sufficient?

**Comment by blasten** [comment]
Let me know if that works. Feel free to reopen if you still have this issue.

**Comment by davidmaxwaterman** [comment]
the supplied solution doesn't work since `overflow: auto` is added via the style attribute.

adding '!important' works, but that is surely a hack.

**Comment by keanulee** [comment]
Hmm, I think we can just set `overflow-y` instead (since we only support vertical scrolling).
