### ISSUE TITLE
Item changed in ui is not selectedItem when selectedItem is changed due to data binding.

### ISSUE THREAD

**Issue by PeterSvedberg** [PolymerElements/iron-list#128]
#### Context
I have an iron-list where both the items and the selected item have a two-way data binding via a parent element to two siblings (A and B). The selected item is displayed in sibling A. I can edit e.g the title of the item in sibling A and the change gets propagated to the list.

#### Problem
When an item is selected with a click on the item in the list the change propagates as expected. However, if the selection originates in sibling B the edit in sibling A propagates to the previously selected item in the list. But **only** in the html. Inspection of items and selectedItem in iron-list shows the change propagated correctly.

#### Details
If we go to _forwardItemPath in iron-list.html and replace: var idx = this._physicalIndexForKey[key]; with: var idx = this.items.indexOf(this.selectedItem); then it works correctly. I'm obviously not offering this as a solution but to highlight the discrepancy between, the index key is pointing to, and the index of the selected item.

**Comment by blasten** [comment]
This seems odd. Would you mind proving a jsbin example that reproduces this issue?

**Comment by PeterSvedberg** [comment]
I hope a github repository will be as good as a jsbin:  https://github.com/PeterSvedberg/ironList128.

**Comment by blasten** [comment]
This issue seems to be fixed, would you mind testing the latest version?

**Comment by blasten** [comment]
please reopen if this is still an issue.
