### ISSUE TITLE
Scrollbar appears behind element (chrome)

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#137]
[Element background appears above scrollbar](http://jsbin.com/ruxavotoxi/edit?html,output) on Chrome for OS X version 46.0.2490.80:

![image](https://cloud.githubusercontent.com/assets/44454/10976548/9e9fe266-83a9-11e5-810b-50903dd0527e.png)

New issue due to [previous Safari-specific issue](https://github.com/PolymerElements/iron-list/issues/18) being closed.  Proposed fix to aforementioned issue does not fix the issue for Chrome.

**Comment by blasten** [comment]
@indolering I couldn't repro this issue. Chrome for Mac  46.0.2490.80 (64-bit)
<img width="514" alt="screen shot 2015-11-05 at 10 59 26 am" src="https://cloud.githubusercontent.com/assets/1410613/10978539/6b2c9cfa-83ac-11e5-9436-f588f693f2f8.png">

**Comment by indolering** [comment]
What in the hell?  I disabled all extensions but I'm still getting it when using incognito mode, a fresh profile, a different user account, and Chrome Canary.

I'm on 64 bit too but I'm still on OS X 10.9....  I'm planning on upgrading over the weekend and I'll report back.

**Comment by indolering** [comment]
Just had a coworker confirm that the problem on 10.10 but with an older version of Chrome: 41.0.2272.118 (64-bit).

**Comment by indolering** [comment]
@blasten Still there on 10.11.  It looks like the link above points to the latest version of that JSBin.  Can you confirm you aren't seeing the issue on [this snapshot](http://jsbin.com/duqekepequ/1/edit?html,output)?  Note that I trimmed the translate directive to just the `.item:nth-of-type(2n+1)` entry.

**Comment by blasten** [comment]
@indolering yup. no issue. 
<img width="504" alt="screen" src="https://cloud.githubusercontent.com/assets/1410613/11105133/d865efae-8881-11e5-963a-5752f830170d.png">

**Comment by indolering** [comment]
I was able to reproduce the issue using Selenium (OS X 10.11 and Chrome 46) on both the [original JSBin](https://saucelabs.com/tests/5e0d72a82cd14139bec2827716d72d79) and the [version locked JSBin](https://saucelabs.com/tests/cd17be17a20f4cb3a5e584e9284c74b4).  That's 3 independent machines plus ~3 or so isolated version of Chrome on my local development machine.

**Comment by blasten** [comment]
I tested in Chrome stable and Canary. It seems like a weird issue in the compositor, maybe you set a flag?

**Comment by indolering** [comment]
@blasten WRT to my local machine, I didn't compile any of these browsers and the isolated instances (using a new profile, opening up in a different user account, using Chrome Canary) should have bypassed at about:config flags.

The "Selenium Log" on the Saucelabs tests show that they disabled some 3d/2d acceleration.  I just switch it from "public restricted" to fully public.  You should be able to view the "Selenium Log" tab.

**Comment by indolering** [comment]
When I checked out chrome://gpu on my local machine the only thing of note was that rasterization was disabled. I forced it on for all layers and generally enabled any hardware acceleration setting I could find, no joy.  I'm running on a MacBook Air (11-inch, Mid 2011) with a Intel HD Graphics 3000 (384 MB).

I saw a comment on the interwebs that BrowserStack doesn't disable GPU acceleration so I gave it a shot in their remote browser, didn't seem to help.

**Comment by blasten** [comment]
I slightly modified your jsbin to see if you can still repro the issue: http://jsbin.com/kutucib/edit?html,output   
I'm surprised that this is issue in Chrome, but I need to confirm it given that I have only seen this issue in Safari 8 & 9.

**Comment by ismailman** [comment]
One difference in your setups that can be causing the discrepancy is the scrollbar behavior you have defined in your OSX preferences. If you have the scrollbar behavior as "show on scroll" that behaves differently than "show always".

I'm running into a similar issue right now...

**Comment by indolering** [comment]
@blasten Yup, still there.  SauceLabs and BrowserStack offer free trials : )

@ismailman I don't think so, the "show always" just forces a more traditional scrollbar that /always/ takes up space and thus doesn't interact with the z-index of the elements.

**Comment by indolering** [comment]
@blasten The only difference is that having the white background turned on hides the scrollbar completely.

**Comment by indolering** [comment]
Any progress on this?  Should I poke someone on the Chrome team?

**Comment by blasten** [comment]
@indolering I'd say so, I cannot reproduce this issue in Chrome 47.0.2526.80 and Canary 49.0.2591.0 canary (64-bit).

<img width="1214" alt="screen shot 2015-12-18 at 3 22 06 pm" src="https://cloud.githubusercontent.com/assets/1410613/11909404/3388305a-a59b-11e5-8e0a-bde7628d73c3.png">

**Comment by indolering** [comment]
@blasten Posted [here](https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=571256), please comment because I have no idea what's going on.

**Comment by blasten** [comment]
@indolering the bug is confirmed in Chrome:
Can you try adding a `will-change:transform;` property to the iron-list? That way, we could temporarily fix this issue.

**Comment by blasten** [comment]
BTW, I realized that I removed the `will-change: transform;` from iron-list https://github.com/PolymerElements/iron-list/blob/5ab9fdbb2d4ae300efdad40a58bda84c0cfa393f/iron-list.html#L8    Will add it back.

**Comment by indolering** [comment]
@blasten So should I wait for the next release or manually add that property to iron-list?

**Comment by alanhg** [comment]
> @indolering I can reproduce this issue on non-retina displays. the bug is confirmed in Chrome:
> You can try adding a `will-change:transform;` property to the iron-list. That way, we could temporarily fix this issue. Please let me know if that fixes the issue.

it solved problem;
