### ISSUE TITLE
"Invalid value used as weak map key" when items is bound to a null object

### ISSUE THREAD

**Issue by adrianaioanei** [PolymerElements/iron-list#14]
I'm using an iron-list with data binding for the items property. The array is dynamically loaded after the list is instantiated. When the list gets created and the array is null, the error is thrown.

**Comment by moderndeveloperllc** [comment]
Have you tried to set the array variable to an empty array instead of null when the element is created?
```
properties: {
  data: {
        type: Array,
        value: function() { return []; }
      }
}
```

**Comment by blasten** [comment]
@adrianaioanei what error did you get?  iron-list renders just fine if `items=null` and then you set it to an array of models.
