### ISSUE TITLE
focused element is not reset when scrolling

### ISSUE THREAD

**Issue by alexdeefuse** [PolymerElements/iron-list#141]
Hi,

The issue manifests as followins:
An iron-list that has inside the template a paper-item for instance.
When you click on a paper-item, the background becomes grey.
Now scrolling down, you'll notice that somewhere down in the list, another item gets focused as well (cause the item being reused doesn't get reset properly).

The issue can also be seen over here: 
https://elements.polymer-project.org/elements/iron-list?view=demo:demo/selection.html&active=iron-list
Click on an item to focus / select it, then scroll down a few pages.

How can I get this fixed?

Thanks!

**Comment by niedzielski** [comment]
I see this issue in every example I can find that uses an iron-list of focusable items. For a list of paper-items, I found the following a useful workaround to disable the focus color altogether:

    paper-item {
      --paper-item-focused-before: {
        background: none;
      };
    }

**Comment by alexdeefuse** [comment]
@niedzielski thanks for the insight. Meanwhile I figure out a way to deal with the issue as well. Thanks again!

**Comment by blasten** [comment]
This is a limitation :(  It's not just reseting the focus state, but also restoring the whole tab index navigation. I will explore a few ideas and see how far I can get with them.

**Comment by blasten** [comment]
This is now fixed and released in v1.2.0
