### ISSUE TITLE
scrollToIndex should return element

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#145]
`scrollToIndex` should return a reference to the physical element after it had scrolled and false/null if the element couldn't be found.  Then you can interact with the element knowing that it has been instantiated.

Edit: I need to get more sleep.

**Comment by pwasem** [comment]
Unsubscribe

Zach Lym <notifications@github.com> schrieb am Di., 24. Nov. 2015 um 21:42:

**Comment by blasten** [comment]
@indolering would you mind explaining what the use case is?

**Comment by indolering** [comment]
In my use-case, I'm trying to scroll to an element in the list and so I can highlight that element using an animation.  To do that, you must first scroll to this element to make sure it has been instantiated.  So anytime you want to interact with a list item, you must perform the scroll and then follow that up with a search through the physical list of elements.  In my case, I have the ID for each item tied to the abstract data model, but it would be more ergonomic if iron-list just returned the element.  Furthermore, numerical ID's are not valid CSS and cannot be searched for without some minor hacking.

**Comment by blasten** [comment]
@indolering Have you tried using data binding to toggle the class that will kick in the CSS animation?

**Comment by indolering** [comment]
> Have you tried using data binding to toggle the class that will kick in the CSS animation?

@blasten Because of how the list display is setup I don't think that will work in this situation, but I haven't looked at that code in 2 weeks.

One of the reasons I suggested this was because it looked like it would be very simple to implement.

**Comment by blasten** [comment]
Yes, but exposing the physical element that way would imply that you give up on the declarative way. It's highly recommended to use bindings so the system can handle the states for you. e.g. what if the item is recycled? Who would take care of resetting the CSS states? By using bindings, it would happen automatically. Therefore, I still believe you can achieve the behavior you are describing using bindings.

**Comment by indolering** [comment]
> Yes, but exposing the physical element that way would imply that you give up on the declarative way.

Isn't using `scrollToIndex` giving up on declarative bindings?

**Comment by blasten** [comment]
`scrollToIndex()` is an action from my perspective. Potentially, `firstVisibleIndex` could be bindable in the future.  

Have you tried doing something like this:
```html
<iron-list>
  <template>
    <div class="_isHighlighted(highlightedIndex, index)">
      [[item.name]]
    </div>
  </template>
</iron-list>
```

```js
_isHighlighted: function(highlightedIndex, index) {
   return highlightedIndex === index ? 'highlightItem' : '';
}
```

```css
.highlightItem {
    //some css
}
```

**Comment by indolering** [comment]
> scrollToIndex() is an action from my perspective.

Not sure what that means....

I think I see where you are coming from and I will probably switch to a declarative approach for highlighting conflicting records once we move to editing multiple records at the same time.  Right now it's just a half-second animation that get triggered using a function native to the element in each item.

However, even then, I will still need a way to check to see if a given record is visible within the list.

**Comment by indolering** [comment]
.... but a string item `""` would evaluate to false.  So just returning true/false is probably best.

**Comment by indolering** [comment]
@blasten I tried adding an observer within my custom element that would trigger an animation when the object backing the item/element has the attribute `item.fresh` set to `true`.  However, when I add an element I also scroll to it and multiple records trigger animation due to recycling.

I think returning the physical element might be the only way to fix this....

**Comment by blasten** [comment]
@indolering you should use bindings to trigger the animation. e.g. Add a class on a DOM node inside the item. That is why manipulating the physical item programmatically is tricky because the API doesn't expose hooks for reseting those states when an item is about to be recycled.

**Comment by indolering** [comment]
> you should use bindings to trigger the animation. e.g. Add a class on a DOM node inside the item. 

That's exactly what I'm doing.  I'll try to get to it when I have time.
