### ISSUE TITLE
Animated item-collapses

### ISSUE THREAD

**Issue by colindevs** [PolymerElements/iron-list#146]
This occurred to me while trying out the collapsible `iron-list`[demo](https://elements.polymer-project.org/elements/iron-list?view=demo:demo/collapse.html&active=iron-list). When I clicked on the items to expand, they just seemed to expand in a fraction of a second, as if they were abruptly teleporting. 

Following this analogy, I thought it might be nice if they be collapsing more like a child does on a slide, quickly at first and then slowing to a stop. It might enhance UX, with a more fluid and living feel.

Of course, I am not deep into the Material Design spec or whatever spec your iron animations follow, so the exact animation times and rates would be up to an experienced designer, though I'd be glad to help code this change once I read the dev guides and study the code!

**Comment by blasten** [comment]
There's a branch that has this feature. https://github.com/PolymerElements/iron-list/tree/flexible-sizes

**Comment by colindevs** [comment]
Ok, thanks.
