### ISSUE TITLE
Missing element method documentation

### ISSUE THREAD

**Issue by Sinjins** [PolymerElements/iron-list#147]
Suggest improving documentation for stamp and modelForElement methods:  
https://elements.polymer-project.org/elements/iron-list?view=docs

**Comment by blasten** [comment]
+1

**Comment by blasten** [comment]
@garlicnation this is a question about Hydrolysis. The description for the `stamp` and `modelForElement`  methods doesn't show up in the catalog. These methods are defined in `Polymer.Templatizer` and they do have descriptions: https://github.com/Polymer/polymer/blob/master/src/lib/template/templatizer.html#L393-L414 

Is this a limitation?

**Comment by blasten** [comment]
friendly ping @garlicnation

**Comment by blasten** [comment]
should be fixed in v2.
