### ISSUE TITLE
dom-repeat template not being picked up in a iron-list template

### ISSUE THREAD

**Issue by adrianaioanei** [PolymerElements/iron-list#15]
```
<iron-list items="[[data]]" as="item">
	<template>
		<template is="dom-repeat" items="[[item.columns]]">
			<div>test</div>
		</template>
	</template>
</iron-list>
```
In this above case, data is an array, each object of it having a columns property which is again an array. The inner dom-repeat template doesn't pick up the inner array. Nothing is displayed.

**Comment by blasten** [comment]
@adrianaioanei The following should work:
```html
<iron-list items="[[data]]" as="item">
  <template>
    <div>
      <template is="dom-repeat" items="[[item.columns]]">
        <div>test</div>
      </template>
    </div>
  </template>
</iron-list>
```

In your code, `<template is="dom-repeat">` is used as the item to wrap the content around, but `dom-repeat` will create the content outside the template.
