### ISSUE TITLE
Demos are broken because iron flex now requires imports from classes/

### ISSUE THREAD

**Issue by nik3daz** [PolymerElements/iron-list#154]
The demos are broken in various ways since they all use the classes from iron-flex without importing the right file.

**Comment by nik3daz** [comment]
Pull request exists at https://github.com/PolymerElements/iron-list/pull/155 .

**Comment by blasten** [comment]
fixed and tagged https://github.com/PolymerElements/iron-list/releases/tag/v1.1.7
