### ISSUE TITLE
List content duplicates when setting items again

### ISSUE THREAD

**Issue by pkaske** [PolymerElements/iron-list#156]
I'm not sure if I'm doing it wrong or if this is a bug...

To reproduce:
1. Fill iron-list with many items
2. Scroll down
3. Re-set items with `this.$.ironlist.items = this.$.ironlist.items.slice(0);`
4. Scroll down slowly
5. After some distance the items start to duplicate.

My use case is of course not to only set the same items array again.
I have a component that pre-filters the items and then gives them to iron-list as a new array.

I made a jsbin to try this:
http://jsbin.com/lenibanavo/1/edit?html,output

**Comment by blasten** [comment]
This issue is confirmed.
