### ISSUE TITLE
The iron-collapse component doesn't expand properly when listing with iron-list

### ISSUE THREAD

**Issue by damibarbieri** [PolymerElements/iron-list#157]
This issue happens while trying to have a paper element that collpases using the iron-collapse. Inside an iron-list. The item list isn't updating its size correctly. I use the corresponding method, but I got 
[this](http://plnkr.co/edit/RmR75G?p=preview). Inside the Polyme Slack I found [this workaroun] (http://plnkr.co/edit/UAj2ZXY8Jd0uHzbRz7lt?p=preview). But, IMO, it is not the smoothest solution.

**Comment by damibarbieri** [comment]
**adding screenshots!**
*collapsed*
![image](https://cloud.githubusercontent.com/assets/5324713/11726002/5d77c362-9f5b-11e5-857d-ff45cd8afb3b.png)
*expanded*
![image](https://cloud.githubusercontent.com/assets/5324713/11726008/63c4a0c8-9f5b-11e5-8c1a-8554d4f52b77.png)

**Comment by blasten** [comment]
I have moved this issue to https://github.com/PolymerElements/iron-collapse/issues/37. There's a last issue related to the animation of the collapse. iron-list doesn't currently support this use case, but there's a branch https://github.com/PolymerElements/iron-list/tree/flexible-sizes showcasing animation to the size of items. I hope it still works.
