### ISSUE TITLE
Dropdown content is not positioned correctly when paper-dropdown-menu is inside an iron-list

### ISSUE THREAD

**Issue by bpinney** [PolymerElements/iron-list#158]
Here is a JSbin of paper-dropdown-menu items in a dom-repeat, reflecting the expected outcome of working great and dropdown content appearing next to the paper-menu-item: http://jsbin.com/nizeta/edit?html,output

Here is a JSbin of paper-dropdown-menu items in an iron-list, reflecting the not so great actual behavior, the dropdown content appearing at position other than that of it's parent: http://jsbin.com/heqike/edit?html,output

There appear to be other visual issues as well, but the issue in the title is my primary concern.

Reference to paper-dropdown-menu: https://github.com/PolymerElements/paper-dropdown-menu/issues/101

**Comment by bwh-rl** [comment]
Same problem appears with paper-menu-button,
or any other element that uses iron-dropdown.

Seems like the position inside an `transform: translate3d(0px, 0px, 0px);` element cant be calculated,
and the `position: absolute;` of the items breaks the overlappings.

Position in paper-menu-button could be overwritten via mixin,
but this would not fix the overlapping issues...
e.g.
```
--paper-menu-button-dropdown: {
	position: absolute !important;
	top: 8px !important;
	right: 8px !important;
};
```

**Comment by blasten** [comment]
@bpinney @bwh-rl is correct. I have talked to @cdata about this issue. Every item in the list creates its own stacking context which is why I think the dropdown content isn't positioned correctly.

**Comment by tbone587** [comment]
Have been there any further findings on this? The suggestion bwh-rl made does fix positioning, but there is still overlapping issues as stated.

**Comment by arno-london** [comment]
Any plan to fix the problem?
It is impossible to use the paper-dropdown-menu inside an iron-list.

**Comment by tbone587** [comment]
Yes this has been open for awhile with no progress..   I did come up with my own workaround but I don't know if it works 100percent

**Comment by arno-london** [comment]
What is your workaround?

Because if I click several times on a same paper-dropdown-menu, then I don't have always the same problem. For example, sometimes the right value is completely wrong (more than 1500 pixels) - the top value is not good too but it could be acceptable temporally. Every time I am not able to see the drop down panel, so unable to select an item.

**Comment by tbone587** [comment]
My workaround was to create an element called iron-list-in-paper-menu-dropdown that appends the iron-dropdown element within to the <body> when the element is attached.  This has actually worked out pretty good.

**Comment by arno-london** [comment]
Thanks. I will try your workaround.

**Comment by tbone587** [comment]
I can provide code if you need, it actually works perfectly.

**Comment by bpinney** [comment]
@tbone587 yes please post, thanks.

**Comment by tbone587** [comment]
Whats the best way to post?

**Comment by bpinney** [comment]
An example on jsbin or a similar service would do just nicely.

**Comment by tbone587** [comment]
I uploaded a gist https://gist.github.com/tbone587/f5ec964fddc388bae85a

**Comment by bpinney** [comment]
Thank you, that's a great workaround.

**Comment by arno-london** [comment]
Thank you @tbone587

**Comment by cdata** [comment]
Please follow https://github.com/PolymerElements/iron-fit-behavior/issues/33 as the canonical tracking issue for this problem. Closing this one.

**Comment by NicolasRannou** [comment]
@tbone587 do you know if it still works? I try your gist in my iron list but when I load my element I get the following error
```
            var $dropDown = this.$.yo.querySelector( "iron-dropdown" );

            // Append the drop down menu to the body to force at highest stacking context.
            document.body.appendChild( $dropDown );  <<<<<< error here >>>>>>
```

$dropDown is not of type Node.

$dropDown is null and can not access the iron-dropdown from the paper-menu-button.

**Comment by NicolasRannou** [comment]
this.$$( 'paper-menu-button' ).`shadowRoot`.querySelector( "iron-dropdown" ) returns the iron-dropdown as expected but it doesn't show up when click on the paper-menu-button. :/
