### ISSUE TITLE
scrollToIndex causes 100% CPU for items at bottom of largeish list 

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-list#162]
This item near the end of the list loads fine: https://www.chromestatus.com/features/5238926818148352

One even later (https://www.chromestatus.com/features/5240822173794304) starts to take up 100% for multiple seconds. The CPU profile looks like iron-list is resizing itself and/or Polymer core is at fault.

<img width="1083" alt="screen shot 2015-12-20 at 4 44 09 pm" src="https://cloud.githubusercontent.com/assets/238208/11921218/2737e288-a739-11e5-9a28-bbbb22fda625.png">

cc @blasten

**Comment by blasten** [comment]
@ebidel I would like to get a copy of the current template inside the list. I assume `scrollToIndex` was called at some point after the features were received from the server. Lastly, is there anything else about the current set up I should be aware to reproduce this issue?

**Comment by ebidel** [comment]
Here's the template:
https://github.com/GoogleChrome/chromium-dashboard/blob/master/static/elements/chromedash-featurelist.html#L16-L26

When you deep link into a feature, `scrollToFeature` finds the feature in the list and calls `list.scrollToIndex`:
https://github.com/GoogleChrome/chromium-dashboard/blob/master/static/elements/chromedash-featurelist.html#L195-L206

When the user taps a feature, `list_update()` is called. But note, this doesn't get called when you deep link into a feature.
https://github.com/GoogleChrome/chromium-dashboard/blob/master/static/elements/chromedash-featurelist.html#L227

**Comment by blasten** [comment]
Fixed and released in v1.2.0
