### ISSUE TITLE
Items are overlapped when use dom-repeat to display images inside iron-list

### ISSUE THREAD

**Issue by duykhoa** [PolymerElements/iron-list#164]
I use iron-list to display a list of posts, each post includes several images.

I already set height for each image, but the iron-list elements are still overlapped.

Here is the screenshot for that.
<img width="1436" alt="screen shot 2016-01-03 at 8 03 52 pm" src="https://cloud.githubusercontent.com/assets/2004218/12078872/31dc817c-b255-11e5-93e6-401a66b2c228.png">

The red part should be below the first post.

It worked perfectly with 1 image each post, but when I allow user upload more image for each post, the iron-list is broken.

**Comment by blasten** [comment]
My first guess is that the size of the content changed after the first measurement. The content size must be determined before iron-list interact with the content to estimate the correct position of the elements inside the list. Can you confirm that all the `img` elements have a `width` and `height` property? Things like fonts or css loading asynchronously might also cause this issue.

**Comment by duykhoa** [comment]
Yes, all images already set a height and width properly.
