### ISSUE TITLE
Better non-numeric index handling

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#165]
When first working with iron-list, I assumed that I could assign non-numeric values to the index.  Using non-numeric indexes just fails silently.  Not sure if there should be an error while building the list, but scrollToIndex should at least output an error message to the console.

      if (typeof idx !== 'number') {
        return;
      }
 
Something like [this](https://jsbin.com/begecolefi/edit?js,console,output) would be more helpful:

```
function _testIndex(idx){
  if(Number.isInteger(idx)){ // 1.0 === true
    return idx;
  } else if (typeof idx === 'string') {
    idx = idx.trim();   
    //https://www.debuggex.com/r/oL9CaZx2biZ6VCZD
    var intReg = /'^[0-9]+(\.0+){0,1}$'/; 
    if(intReg.test(idx)){ 
      return parseInt(idx);
    }
  }
  return false;
}

if(!_testIndex(idx)){
  throw "Index must be an integer!";
}
```

**Comment by blasten** [comment]
You right, it should throw giving that this is an explicit invocation. One more thing, this `index` is the index  used to lookup the item in the array. e.g. `list.items[index]` so you are free to have an `index` property of any type in your data model if you need to. e.g. `list.items[index].index = "TX828282"; `  

In the template, you can bind to:

1. `index` or the value you set in the `indexAs`.
2. `item` or the value you set in `as`.

**Comment by indolering** [comment]
> One more thing, this index is the index used to lookup the item in the array. e.g. list.items[index] so you are free to have an index property of any type in your data model if you need to. e.g. list.items[index].index = "TX828282";

You should add some examples to the documentation.

**Comment by blasten** [comment]
Fixed!
