### ISSUE TITLE
DISCUSSION: PR Grid Mode Support?

### ISSUE THREAD

**Issue by jshcrowthe** [PolymerElements/iron-list#167]
`iron-list` is awesome and I am super anxious to get grid support! Instead of pestering the Polymer team (they are busy enough as is!) I wanted to get a discussion started on potentially PR'ing this feature.

I have created a functional prototype that can be found under a branch on my fork (https://github.com/jshcrowthe/iron-list/tree/grid-mode-refactor)

All existing tests still pass but before I went down the road of writing out a test suite and fixing some of the more annoying bugs, I wanted to see if my approach to the problem was acceptable and that this was something that isn't on the near horizon.

# My Approach
## Refactored Pieces 
I did a couple things just to help my sanity _(All of these can be reverted like I said these were just to help my sanity)_
- Property name change, instead of using `_viewportSize` I refactored it to `_viewportHeight` as I also would introduce `_viewportWidth`
- Refactored use of `this.transform` in `_positionItems` to `this.translate3d` as there is a dedicated function for `translate3d`
- Refactored use of `addEventListener`/`removeEventListener` in favor of `this.listen`/`this.unlisten`, for consistencies sake (Honestly I like the `listen`/`unlisten` helpers more and there were instances of both)

## Properties
Similar to `core-list` I have introduced a few properties to configure the grid layout:
- `grid` (used to toggle grid mode) _without this param `iron-list` functions as normal_
- `itemWidth` (**required** if using `grid` mode) _this param will dictate the width of any item in the list_
- `itemOffset` (**optional** defaults to `0` if not passed) _this param will allow the addition of margin between grid items that will be taken into account as the grid calculations are done_

## Added Private Props/Fxns
I have introduced one new property as well as two private functions to help keep track of grid computations:

- `_physicalItemsPerRow` is a property used in many computations across the component as I have attempted to view the entire `iron-list` as a grid with varying items per row.
- `_updateGridMetrics` is a function responsible for setting the value of `_viewportWidth` as well as the value of another property `_physicalItemsPerRow`. This is called in both `_updateMetrics` and `updateViewportBoundaries` calls.
- `_getPhysicalTopIncrement` is another function responsible for appropriately incrementing the value of `_physicalTop` when needed.

### Usage of `_getPhysicalTopIncrement`
I have replaced **all** instances of 
```javascript
this._physicalSizes[<SOME INDEX VALUE>]
```

with

```javascript
this._getPhysicalTopIncrement(<SOME INDEX VALUE>)
```

Allowing me to properly approximate the scroller size as well as scroll position and DOM node pool calculations.

### Refactoring `_positionItems` to handle horizontal and vertical positioning
I have added a little bit of logic to the `_iterateItems` call in this function to position items horizontally _then_ vertically if in grid mode. 

As mentioned before in non-grid mode this functions identically.

## Known Issues (Help Wanted!)
I am only able to observe a couple issues with this implementation:

- Resizing the browser from a small column count to a large count (e.g. 2 column grid -> 5 column grid) results in the height of the scroller not being properly shrunk to handle the new column.

- Resizing the browser from a small column count to a large count can also result in a smaller DOM node pool than is needed and the next pages artifacts not being displayed correctly.

I can open the PR so any other code discussion can happen in context of the PR but it may still be a bit premature. All in all I'd love to see this feature get added and would be glad to continue working on this PR if it's a good approach!

**Comment by blasten** [comment]
This is really awesome, thanks for taking the time! I'd love to see the PR, so we can discuss the approach in detail and fix the issues you encountered. I looked at the demo and it looks nice overall! I need to look at `_getPhysicalTopIncrement` in detail to see if there could be issues with it.  cc @kevinpschaaf

**Comment by binoculars** [comment]
:+1: I :heart: grid mode. Badly needed.

**Comment by jshcrowthe** [comment]
My pleasure to help out! A PR has been drafted that can be worked on until this is ready to go. If you like the approach I can start to draft up some more demos (to have a complete demo suite) in addition to starting on the tests?
