### ISSUE TITLE
A flexed iron-list has the size to contain its children, but it still shows scrollbars

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/iron-list#170]
A flexed iron-list has the size to contain its children, but it still shows scrollbars and allows minimal scrolling (a few pixels)

https://weneed-1147.appspot.com/#!/pending

Open the hamburger menu and add items. When adding more than the paper-card current size, they will all flex, but the iron-list shows scrolling though it has the height to fix its children (# of children * 30px)

**Comment by kenchris** [comment]
@blasten any idea about this or work arounds?

https://goo.gl/photos/5JWCWVKYoqyQeBDE9

each item is 31px (meaning 186px for all 6) which is the size of the yellow area, which still allows being scrolled.

**Comment by kenchris** [comment]
So apparently this is due to the ink-effect, so a fix would be to do

```
iron-list > * {
  overflow: hidden;
}
```

The ink effect in general is a bit of a problem, like the the above example it is already being clipped to the iron-list to the left side.

@robdodson maybe it would be an interesting Polycast episode to talk about the ink effect and how to best avoid it being clipped or messing up your layout?

**Comment by blasten** [comment]
This issue should be fixed after merging https://github.com/PolymerElements/iron-list/pull/175.  You can customize the `scrollTarget`  and have a selector such as 
```css
#scrollingRegion {
 overflow: visible;
}
```

and then ` <iron-list scroll-target="scrollingRegion">`
