### ISSUE TITLE
unexpected filtering of records when item is either a zero or blank string 

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/iron-list#171]
given the following scenario ...

```html
  <template id="demo" is="dom-bind">
    <iron-list items="[[arrayOfValues]]">
      <template>
        <div>[[index]]: [[item]]</div>
      </template>
    </iron-list>
    <hr>
    <template is="dom-repeat" items="[[arrayOfValues]]">
      <div>[[index]]: [[item]]</div>
    </template>
  </template>
```

```javascript
    document.addEventListener('WebComponentsReady', () => {
      let demo = document.querySelector('#demo');

// same results for any of these
      demo.arrayOfValues = [ 'one', '', 'three'];
//      demo.arrayOfValues = [1, 0, 3];
//      demo.arrayOfValues = [1, undefined, 3 ];
//      demo.arrayOfValues = [1, null, 3 ];
    });
```
for `iron-list` the second value is not rendered, actually it's `hidden`, which is not the same behavior for `dom-repeat`. 

to me this is unexpected because if I bind to an array of 3 items i expect three iterations of the template to render, without any specific filtering. =[

the logic is explicitly coded in the private `_assignModels` method of the `iron-list` component ...

```javascript
        if (item) {
          ...
          el.removeAttribute('hidden');
          ...
        } else {
          ...
          el.setAttribute('hidden', '');
          ...
        }
```

the `if` clause, above, takes `0` && `''` values hostage through coercion ,-(

**is it possible to at least check with the following logic** `if (test !== undefined)` **||** `if (test != null)` **if the filtering can't be removed completely?**

thanks

**Comment by Nejat** [comment]
btw, the temporary work around is to map the values by encapsulating them into objects and then back

**Comment by blasten** [comment]
This issue was fixed in master https://github.com/PolymerElements/iron-list/issues/140. We will release it asap.
