### ISSUE TITLE
_forwardItemPath should check if it is notifying the correct item

### ISSUE THREAD

**Issue by nik3daz** [PolymerElements/iron-list#173]
I have

```
this.list = [
  { array: [{val: 1}, {val: 2}] },
  { array: [{val: 3}]}
]
```

Let's pretend iron list only renders 1 item at a time. When I move from the first item to the second item, and call this.notifyPath('list.0.array.1.val', 0), I expect \_forwardItemPath to do nothing because the first item is not rendered. However, iron-list actually sends the notification to the existing physical element, which then breaks upon trying to access .val of an undefined. I think this happens because iron-list's physicalKeyForIndex mapping is not updated when items are derendered. Alternatively, we could just check that inst.__key__ == key inside _forwardItemPath.

**Comment by blasten** [comment]
@danbeam I will investigate.
