### ISSUE TITLE
scrollToPos method

### ISSUE THREAD

**Issue by Zecat** [PolymerElements/iron-list#177]
I would like a scrollToPos method, as it's a common thing when working with a scrollable element.

Use case : for the needs of a year-picker, when it opens, I need the selected year to be centered in the iron-list viewport. 

I found no other solution but override _resizeHandler removing [this.scrollToIndex(this.firstVisibleIndex);](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1213) (as when the year-picker opens, it resizes and scroll unintentionally), then use this [dirty method](https://github.com/Zecat/paper-date-picker/commit/4c606532229f36b1a140bdfd6fa0fab105af7372#diff-01f219e213dc81af4cda36dcc27a77beR103) :

``` js
centerIdx: function(index) {
  this.$.ironList.scrollToIndex(index);
  // see https://github.com/PolymerElements/iron-list/issues/140
  this.$.ironList._render();
  this.async(function() {
    // assumes all items are the same height
    var indexPos = index * this._physicalAverage + 1;
    // the first call, it scrolled to a shifted index
    if (indexPos != this.scrollTop) {
      this._update();
      this.scrollTop = indexPos;
      this._refresh();
    }
    this.scrollTop += (this._physicalAverage - this.offsetHeight) / 2;
    this._refresh();
  }.bind(this.$.ironList));
}
```

**Comment by blasten** [comment]
Is there any other use case other than a year picker?

**Comment by bvhme** [comment]
Perhaps highlighting a search result in a long list? Centering the active selection. Or programmatically scroll to the same position after changing the `items`, which causes it to reset.

**Comment by pkaske** [comment]
IMO sorting and filtering would become much more easier to implement. In this situations it far less complex to just replace `items` with the newly sorted/filtered array, let iron-list re-render and then restore scroll position. So their should be many use cases, am I right?

**Comment by blasten** [comment]
iron-list now has a `scroll` method, so you can use that one to achieve this behavior.
