### ISSUE TITLE
Scrollbar appears behind element (safari)

### ISSUE THREAD

**Issue by ZoneMR** [PolymerElements/iron-list#18]
When list items contain content that should appear behind the scroll bar (in our case bottom borders and on-hover background), the scrollbar appears behind the content.

This happens on Safari (8.0.7) but appears fine on Chrome.

![bug](https://cloud.githubusercontent.com/assets/106949/8645855/e3604c54-2942-11e5-81a2-070f94c7b68c.png)

**Comment by blasten** [comment]
This is confirmed.

**Comment by vzhen** [comment]
Me 2
Windows 7 with chrome 45
Can we just remove below code in the source file?
`:host(.has-scroller) {
      overflow: auto;
    }
`

**Comment by indolering** [comment]
I'm getting this on Chrome, but not Firefox...

![scrollbarissue](https://cloud.githubusercontent.com/assets/44454/10298504/1dc643e8-6b9d-11e5-9fd9-48710cd0a762.png)

**Comment by indolering** [comment]
I added paper-tooltip and it appears as if the tooltip itself is being hidden behind the background of another element:


![screen shot 2015-10-13 at 4 59 15 pm](https://cloud.githubusercontent.com/assets/44454/10470697/5d963e8a-71cc-11e5-8671-3a4bf1572a5f.png)

![screen shot 2015-10-13 at 4 59 32 pm](https://cloud.githubusercontent.com/assets/44454/10470698/5d965212-71cc-11e5-8112-1c115f908c82.png)


My elements are being styled via a CSS selector in the parent element: 

```
custom-record-name:nth-of-type(2n+1) {
        background-color: #fcfcfc;
}
```

I suspect that the z-transforms are introducing laying issues.....

**Comment by indolering** [comment]
I couldn't get the demo working in JSBin, but you should be able to c/p the code and view it locally:

http://jsbin.com/cetabu/2/edit?html,output

**Comment by blasten** [comment]
It seems like the only solution for Safari is to add:
```css
iron-list {
  translate: translateZ(0);
  -webkit-translate: translateZ(0);
}
```

**Comment by indolering** [comment]
@blasten that did not fix the issue for me on Chrome.

**Comment by indolering** [comment]
@blasten that did not fix the issue: http://jsbin.com/dimafegako/2/edit?html,output

![image](https://cloud.githubusercontent.com/assets/44454/10806030/08201368-7d98-11e5-9896-224df8160153.png)

**Comment by indolering** [comment]
@blasten I tried applying in [this JSBin](http://jsbin.com/qudogefuli/1/edit?html,output) but I'm still seeing it in Safari.

**Comment by bishbashbosh123** [comment]
I think @blasten may have meant:
```
  transform: translateZ(0);
  -webkit-transform: translateZ(0);
```
This helped me solve an issue with content appearing above scrollbars in Chrome on OSX.
