### ISSUE TITLE
Uncaught TypeError: Cannot read property '_templateInstance' of null

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/iron-list#180]
A basic example causes a TypeError for each item in the list: https://jsfiddle.net/7apju810/1/

```
<dom-module id="x-foo">
  <template>
    <iron-list items="{{items}}">
      <template>[[item]]</template>
    </iron-list>
  </template>
</dom-module>
```

**Comment by blasten** [comment]
Yup, this issue is fixed in https://github.com/PolymerElements/iron-list/pull/179/files#diff-b97995700c5da5fa638d0324b5f3f861R1284. It will be merged soon.
