### ISSUE TITLE
Laggy transition of ripple and selectionBar inside paper-tabs when rendering too long list on Chrome Android

### ISSUE THREAD

**Issue by motss** [PolymerElements/iron-list#182]
## Expected outcome
Ripple animation runs smoothly when clicking on tabs that renders very long list on Chrome Android.
Selection bar runs smoothly when new tab is selected.

## Actual outcome
Rendering too long list causes laggy ripple animation in `paper-tabs`.
Rendering too long list causes selection bar to not transition smoothly to the selected tab that renders long list.

## Demo to reproduce on Chrome Android.
http://jsbin.com/darugukavi/1/edit?html,output

**Comment by blasten** [comment]
This seems to be an issue with paper-ripple.  I moved your issue to https://github.com/PolymerElements/paper-ripple/issues/77
