### ISSUE TITLE
iron-list.html:1257 Uncaught RangeError: <item> not found

### ISSUE THREAD

**Issue by agozie** [PolymerElements/iron-list#184]
This started after the last update.
` <iron-list id="list" items="[[items]]" as="item" scroll-target="html" selection-enabled multi-selection>
        <template>
...
        </template>
      </iron-list>`

If you scroll up and make `this.set('items',[]);` the error will occur and the list will become unusable. I use the same list to show different things. It worked well till now. I easily reproduced it with the demo by scrolling up, then click a button that set items to [].
Thanks.

**Comment by mbergeron** [comment]
I confirm the exact same issue. Setting the "items" property to "[]" to clean to iron-list generate a  "Uncaught RangeError: <item> not found".

**Comment by blasten** [comment]
Thanks I will look into this issue.
