### ISSUE TITLE
The list erroneously moves itself off-screen 

### ISSUE THREAD

**Issue by urandom** [PolymerElements/iron-list#186]
When a particular set of circumstances is met, the the list tries to move some kind of item offscreen, but instead moves itself. The problem occurs at:
https://github.com/PolymerElements/iron-list/blob/v1.2.2/iron-list.html#L1462

The problem is that the offscreen item is undefined, so translate3d reverts to acting on the host, rather than a given descendant. There should probably be guards against that in both cases where translate3d is called with the magic hidden_y value.

I can always reproduce the problem in under the following conditions:
- the list and another element are children of a pages element
- the list is not selected (the other element is visible) and its scrollTarget is unset
- new items are prepended to the list's item set
- the list becomes selected again
- its scrollTarget is once again set to the correct value
- the list is scrolled to a particular index, which causes the problematic function to ultimately be called.

**Comment by blasten** [comment]
Thanks, I will look into this issue.

**Comment by blasten** [comment]
this issue is fixed in master. run bower update.
