### ISSUE TITLE
Uncaught TypeError: Illegal invocationPolymer.Base._addFeature._applyConfig @ polymer.html:1647

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/iron-list#19]
The demo works fine using the code as shown on the front page. However, switching to my api starts to cause problems (Perhaps because of the nested resource?). Any thoughts?

I've used the following code:
```
<iron-ajax auto url="https://localhost:3000/foo/bar" handle-as="json" debounce-duration="300" last-response="{{ajaxResponse}}"></iron-ajax>

    <iron-list items="[[ajaxResponse.data]]" as="item">
      <template>
        <div>
          Name: <span>[[item.title]]</span>
        </div>
      </template>
    </iron-list>
```
I have an api returning:
```
{data: [
   {
      "title":"expedite strategic technologies",
      "id":1
   },
   {
      "title":"foo strategic technologies",
      "id":2
   }
]}
```
And get this stacktrace:
```
Uncaught TypeError: Illegal invocationPolymer.Base._addFeature._applyConfig @ polymer.html:1647
Polymer.Base._addFeature._afterClientsReady @ polymer.html:1642
Polymer.Base._addFeature._ready @ polymer-mini.html:62
Polymer.Base._addFeature._tryReady @ polymer-mini.html:52
Polymer.Templatizer._constructorImpl @ polymer.html:3233
TemplateInstance @ polymer.html:3071
Polymer.Templatizer.stamp @ polymer.html:3258
Polymer._itemsChanged @ iron-list.html:600
Polymer.Base.extend._complexObserverEffect @ polymer.html:1317
(anonymous function) @ polymer.html:1161
Polymer.Bind._modelApi._effectEffects @ polymer.html:1158
Polymer.Bind._modelApi._propertySetter @ polymer.html:1143
setter @ polymer.html:1219
Polymer.Base._addFeature._applyEffectValue @ polymer.html:1567
Polymer.Base.extend._annotationEffect @ polymer.html:1290
(anonymous function) @ polymer.html:1161
Polymer.Bind._modelApi._effectEffects @ polymer.html:1158
Polymer.Bind._modelApi._propertySetter @ polymer.html:1143
setter @ polymer.html:1219
(anonymous function) @ polymer.html:1259
Polymer.Base._addFeature._notifyListener @ polymer.html:1660
Polymer.Base._addFeature.fire @ polymer.html:1062
Polymer.Bind._modelApi._notifyChange @ polymer.html:1127
Polymer.Base.extend._notifyEffect @ polymer.html:1298
(anonymous function) @ polymer.html:1161
Polymer.Bind._modelApi._effectEffects @ polymer.html:1158
Polymer.Bind._modelApi._propertySetter @ polymer.html:1143
setter @ polymer.html:1219
Polymer._handleResponse @ iron-ajax.html:392
```

`Google Chrome	43.0.2357.132 (Official Build) (64-bit)`

**Comment by blasten** [comment]
I could replicate the issue if you include a property named `title` in the model.

**Comment by zmoshansky** [comment]
Yes, it seems even adding `"id"` to the basic demo in the readme is enough to trigger it. Could you clarify, is the behaviour observed a bug or just incorrect usage? https://github.com/Polymer/polymer/issues/2061 seems like a similar issue/explanation

**Comment by blasten** [comment]
@zmoshansky Right. It seems to be the same issue.

**Comment by zmoshansky** [comment]
As a potential solution, could we run a transformation step that prefixes the property names? Then call `stamp()`.

ex.) `id->data-id`; `title-> data-title`, etc.

**Comment by kevinpschaaf** [comment]
@zmoshansky On second look, we couldn't actually reproduce your issue.  This jsBin uses the exact code you posted above: http://jsbin.com/yugoxom/edit?html,output and renders without error.

I only expect you to run into problems re: https://github.com/Polymer/polymer/issues/2061 if you are trying to set `title` or `id` directly onto the template instance (aka model) which extends from HTMLElement (in the example, `title` and `id` are on `item`, not on the template instance itself).  So it's not clear what configuration actually leads to the `Illegal invocation` error you mentioned.  Can you help point us to your scenario that produces the issue?  It may also be browser related, so please include that info also.  Thanks.

**Comment by blasten** [comment]
This issue was fixed  after https://github.com/PolymerElements/iron-list/commit/37726c5016139ff942a3edde3711663f6f2d9768, so it's available in https://github.com/PolymerElements/iron-list/releases/tag/v1.0.1 :)

**Comment by zmoshansky** [comment]
Perfect, I can confirm it works! Thanks again for all the work.
