### ISSUE TITLE
Iron List Covering Absolutely Positioned Items

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#190]
iron-list is [causing interleaving with absolutely positioned items](http://jsbin.com/wayaku/6/edit?html,output).  Adding a z-index seems to fix it, not sure if there is a better fix or if you need to just document the issue.

![image](https://cloud.githubusercontent.com/assets/44454/12804333/45994b90-caa7-11e5-9aba-1a954016aa67.png)

**Comment by blasten** [comment]
I'd recommend increasing the z-index of `abs-div`
