### ISSUE TITLE
Sizing bug on elements without static heights.

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#191]
For some reason, one element will take up a LOT of space when first loaded.  The bug occurs when leaving the height unspecified or using min/max height but it goes away when you statically define the height.  It also goes away when resizing the page.

![sizing-bug png](https://cloud.githubusercontent.com/assets/44454/12832487/2b9d9ea0-cb4f-11e5-8c74-2f39bdd12563.png)

![image](https://cloud.githubusercontent.com/assets/44454/12832336/25cd3f22-cb4e-11e5-94e9-aabaf63f4e3b.png)

I was having trouble reproducing this [in JSBin](http://jsbin.com/tuyufi/4/edit?html,output) because it is somehow triggering a size refresh.  You need to copy the source to disk and serve it locally.

**Comment by blasten** [comment]
This issue should be fixed by now. please reopen otherwise :)
