### ISSUE TITLE
Uncaught TypeError when the row of iron-list has a checkbox element

### ISSUE THREAD

**Issue by limingv5** [PolymerElements/iron-list#192]
I meet a "Uncaught TypeError: <item> should be a valid item" after I update the iron-list to the version of 1.2.3

Code:
```
<iron-list items="{{cat.sub}}" as="tag" index-as="idx">
  <template>
    ....
    <input type="checkbox">
    ....
  </template>
</iron-list>
```

When I click the checkbox, the Uncaught TypeError will be occurred.

**Comment by blasten** [comment]
this issue is fixed in master. please bower update
