### ISSUE TITLE
Very poor first render performance since 1.2.0

### ISSUE THREAD

**Issue by pkaske** [PolymerElements/iron-list#198]
Hey there,

I use iron-list to generate a table like list. Each row is a custom element containing multiple customs elements. It looks like that:

![selection_020](https://cloud.githubusercontent.com/assets/11567985/12960875/de411b3e-d03d-11e5-800b-880a81eb4204.png)

It's basically rows of custom elements to build a table that has features like in cell text editing, a cursor, sortable columns and stuff. Long story short, the iron-list has quite some load.

In version 1.1.7 the first render time took something about 2 secs.
With 1.2.0 its now about 25 secs.

I tried different commits of iron-list to get the code changes that caused the drop and I was able to narrow it down to 5e0f4911. In the previous commit b98c151f iron-list is still fast.

I would love to provide a jsbin, but I don't know how to load a specific commit of iron-list into jsbin. If you can help me with that I would try to create a demo of the issue.

**Comment by frankiefu** [comment]
If you could just put the demo that shows the issue on jsbin, we could test it out with different versions locally to see the performance differences.  FWIW, taking 25 sec to load seems very bad so we need to look at it to see why.

**Comment by pkaske** [comment]
Ok, I tried to reproduce the problem with a quickly build table like component.
[jsbin](https://jsbin.com/tegowozoce/edit?html,output)

This is what I can say:

- iron-list 1.2.x shows the first three rows and after a very long time the rest appears. Version 1.1.7 showed nothing at first and suddenly all was rendered. However I'm was not able to reproduce the big performance difference with the paper-elements. It always takes very long to render.
- While the controls are unresponsive while iron-list renders, you can scroll the list which often leads to a unwanted padding at the top when the list finally shows the missing rows.
- I was suspecting the paper-input to be very heavy so I tried it with just a simple element showing text. It's called `x-text`. You can replace paper-input with x-text in the `x-row` element to see the effects. It brings up some other strange effect. If you just wait for the list to render - doing nothing on the page meanwhile - the list never finishes rendering. If you than click a checkbox or scroll around, suddenly the rest appears.

It sucks (for me) that I can't reproduce the performance gap between 1.1.7 and 1.2.x. I will try to narrow it down in my full table component and see if then I can bring it to jsbin. But overall it would be frickin awesome if render performance could be improved if many custom elements are rendered.

For your convenience I created a github repo with the jsbin that is ready be run locally with a quick __git-clone__, __bower install__ and __polyserve__. Currently iron-list ^1.2.0 is in the dependencies.

https://github.com/pkaske/iron-list-perf

**Comment by frankiefu** [comment]
In your jsbin, the iron-list is not sized, so it doesn't know how many physical items the list should generate.  I fixed it by making iron-list `--layout-fit` so it fits inside the viewport: [jsbin](https://jsbin.com/jaderuniza/edit?html,output)

**Comment by pkaske** [comment]
A yeah, I forgot that in the jsbin. This also seems to be the issue in my table component. The iron-list is sized via `--layout-flex` while it's parent element is `display: flex; flex-direction: column;`. Version 1.2.x seems to no longer like that kind of sizing, am I right? Setting iron-list to `--layout-fit` resolves all issues here too.

**Comment by frankiefu** [comment]
It's good to know is working for you.

As with the sizing, it should be fine to use flexbox to size the iron-list.  Here is the [jsbin](https://jsbin.com/kidijinihu/edit?html,output)

Basically `iron-list` must either be explicitly sized, or delegate scrolling to an explicitly sized parent. By "explicitly sized", we mean it either has an explicit CSS height property set via a class or inline style, or else is sized by other layout means (e.g. the flex or fit classes).

We are looking at making this better either by providing a default height or some warning about the size is not set. Also see this: https://github.com/PolymerElements/iron-list/issues/191

**Comment by pkaske** [comment]
Thanks for for clarification, @frankiefu :+1:
