### ISSUE TITLE
Sorting the underlying item list doesn't work anymore

### ISSUE THREAD

**Issue by mbergeron** [PolymerElements/iron-list#200]
Hi,

In version 1.1.7 of the iron-list we could do something like this:

`itemList = itemList.sort(function(a, b){return a.priority - b.priorirty});`

and the iron-list was sorted accordingly.

It does not work anymore in version 2.2.4. Is it a bug or a design change?

Thanks,

**Comment by blasten** [comment]
@mbergeron Array.prototype.sort sorts the array **in place** and returns the array, so that won't trigger the update. 

This is the way to do it:
```js
itemList = itemList.slice().sort(function(a, b){return a.priority - b.priorirty});
```

**Comment by mbergeron** [comment]
Blasten, you are right, adding the slice does trigger a complete list refresh, the problem is that if the user was scrolled halfway through, he gets scrolled back to top.

The behavior in 1.1.7. was perfect, items where getting reordered without affecting the scroll. Do you know why that behavior was changed?

Thanks,
