### ISSUE TITLE
Regression #186 - List Erroneously moves

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/iron-list#201]
It looks like whatever is causing #186 has not been fully resolved. After scrolling an iron-list, switching back and forth between pages several times, and scrolling, `iron-list` eventually `translate3d`s itself to `y=-10000px` (HIDDEN_Y).

I'm using `iron-list 1.2.4` and `polymer#master @9bdfacad72` (due to https://github.com/Polymer/polymer/pull/3408)

**Comment by frankiefu** [comment]
@zmoshansky, can you provide a testcase (e.g. jsbin) that we can try to reproduce the issue?

**Comment by zmoshansky** [comment]
Working on it...

**Comment by frankiefu** [comment]
This seems like a good check before calling `translate3d`.  @blasten WDYT?

**Comment by blasten** [comment]
I would really like to see a repro code. This check doesn't hurt, but it also suggests that something isn't working the way it is supposed to. At least this is failing: https://github.com/PolymerElements/iron-list/blob/fbcfdc4fd546061f38533a0250813ba38ba08cfc/iron-list.html#L1493

**Comment by frankiefu** [comment]
+1 about the repro code.

**Comment by zmoshansky** [comment]
So... It took all 13 hours since last post ;)

https://jsbin.com/yumicujubo/edit?html,output

Note: changing the `_delay` in `_setData` to a larger time seems to make this easier to elicit. Likely indicating that the issue is when the backing data for `iron-list` changes while scrolling (#ConcurrencyProblems?)

##### To Reproduce...
1. Scroll vigorously up and down a few times
2. Toggle "Show/Hide"
3. Quickly do a big scroll towards the bottom
4. Repeat

##### Test Code 
```
<!doctype html>
<head>

  <meta name="description" content="Polymer Example">
  <meta charset="utf-8">
  <base href="https://polygit.org/polymer+v1.2.4/iron-list+v1.2.4/iron-icons+v1.1.3/iron-icon+v1.0.7/paper-item+v1.1.3/paper-button+v1.0.11/components/">

  <script src="webcomponentsjs/webcomponents.js">
  </script>

  <link href="iron-list/iron-list.html" rel="import">
  <link href="paper-item/paper-icon-item.html" rel="import">
  <link href="paper-button/paper-button.html" rel="import">
  <link href="iron-icon/iron-icon.html" rel="import">
  <link href="iron-icons/iron-icons.html" rel="import">
  <link href="polymer/polymer.html" rel="import">
</head>
<body>

<proto-element></proto-element>

<dom-module id="proto-element">
  <template>
   <style> 
    iron-list {height: 700px;}
    paper-icon-item {height: 80px;}
  </style>
  <paper-button on-tap="_toggleShow">Show/Hide</paper-button>
  <iron-list id="list" items="[[records]]" hidden="[[show]]">
    <template>
      <paper-icon-item>
      <iron-icon icon="assessment" item-icon></iron-icon>
        <paper-item-body>
          <div>[[item.id]]</div>
          <div secondary>[[item.name]]</div>
        </paper-item-body>
      </paper-icon-item>
    </template>
    
    </iron-list>
  </template>
  <script>
    HTMLImports.whenReady(function () {
  
      Polymer({
  
        is: "proto-element",
  
        properties: {
          records: Array,
          show: {
            type: Boolean,
            value: false
          }
        },
        
        ready: function() {this._setData();},
        _setData: function() {
          var records = [];
          for (var i = 1000; i >= 0; i--) {
            records.push({id: i, name: Math.random()})
          };
          this._delay(10);
          this.records = records;
        },
        _toggleShow: function() {
          this.show = !this.show;
          if(this.show) {this._setData();}
        },        
        _delay: function(ms) {
            var cur_d = new Date();
            var cur_ticks = cur_d.getTime();
            var ms_passed = 0;
            var d;
            while(ms_passed < ms) {
                d = new Date();
                var ticks = d.getTime();
                ms_passed = ticks - cur_ticks;
            }
        }
      });
    });
  </script>
</dom-module>

</body>
```

**Comment by blasten** [comment]
@zmoshansky can you try the branch issue-201? `bower i PolymerElements/iron-list#issue-201`

**Comment by frankiefu** [comment]
The [PR](https://github.com/PolymerElements/iron-list/pull/202) has merged into #master.

**Comment by zmoshansky** [comment]
@blasten @frankiefu It looks like that resolves it. Thanks for fix! :)
