### ISSUE TITLE
Definition of "focusable element" / how to apply it to paper-dropdown for selectionEnabled

### ISSUE THREAD

**Issue by Compufreak345** [PolymerElements/iron-list#207]
So, finally I got a paper-dropdown to "kind-of" work inside my iron-list. I now have the issue that it does not seem to consider a paper-dropdown as "focusable item", as said in [the definition of "selectionEnabled"](https://elements.polymer-project.org/elements/iron-list#property-selectionEnabled) : 

> Note that tapping focusable elements within the list item will not result in selection, since they are presumed to have their * own action.

What is the definition of "focusable element" and is there a possibility to define custom elements as "focusable elements"?

Currently my row gets selected when I open the paper-dropdown - I need to prevent this behavior.

Thanks for every hint in the right direction & best regards,

Compu

**Comment by blasten** [comment]
You can add a tap event listener to the paper-dropdown and stop the propagation of the event.
e.g.
```js
_tapDropdown: function(event) {
  event.stopPropagation();
}
```
