### ISSUE TITLE
responsive iron-list

### ISSUE THREAD

**Issue by githubGabriela** [PolymerElements/iron-list#208]
Hey guys,

Did anyone already implemented a responsive iron-list?

I'm implementing an iron-list like in gmail inbox and I have multiple columns.  For the small screens I would need to a result like this one:
https://css-tricks.com/examples/ResponsiveTables/responsive.php

Thankx!

**Comment by githubGabriela** [comment]
I found a solution,  if the screen is big display the items in -webkit-flex  (this corresponds to the class horizontal).  If the screen is small display the items in block.

http://jsfiddle.net/fiddle_gabriela/u794Ltzw/73/

**Comment by blasten** [comment]
You can totally do that by using media queries and styling the `item` container.

```html
<iron-list>
<template>
<div class="item">
   <div class="firstName"'>[[item.firstName]]</div>
   ...
</div>
</template>
</iron-list>
```

If the screen is small, then you can use the pseudo selector `::before` to add the label "First name" and so on...
