### ISSUE TITLE
Bug - Iron-List doesn't render correctly if `items` changed while hidden

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/iron-list#209]
Iron-List doesn't render correctly if `items` change while hidden

## Expected outcome

Iron-List would render the current `items`.

## Actual outcome

Iron-List renders the old `items` that were shown before it was hidden.

## Steps to reproduce
See [this jsbin](http://jsbin.com/xegometogo/edit?html,output)
1. Click 'show/hide'
2. Click 'change data'
3. Observe record count has changed
4. Click 'show/hide'
5. Observe `iron-list` rendering the wrong items
---- Bug Demonstrated ----
6. Click 'change data'
7. Observe record count has changed and iron-list is rendering the new data

## Attempted Fixes
- Use `iron-list._render();` after `iron-list` is un-hidden works.
- Use `iron-list.notifyResize();` doesn't work
- Use `iron-list.updateViewportBoundaries();` doesn't work

**Comment by blasten** [comment]
@zmoshansky https://github.com/PolymerElements/iron-list#resizing
> By default, elements such as iron-pages, paper-tabs or paper-dialog will trigger this event automatically. If you hide the list manually (e.g. you use display: none) you might want to implement IronResizableBehavior or fire this event manually right after the list became visible again.

**Comment by zmoshansky** [comment]
Wow, It doesn't get much better spelled out than that... I must have been having some day :stuck_out_tongue_closed_eyes: 

Thank you for the info and the polite response to such an obvious question!
