### ISSUE TITLE
Collapsable items demo is not working

### ISSUE THREAD

**Issue by liuyao61** [PolymerElements/iron-list#210]
Browsers used are Chrome and Safaris both latest version.

Uncaught TypeError: <item> should be a valid itemPolymer.Base._addFeature.fire @ polymer.html:1264

**Comment by frankiefu** [comment]
@blasten In the demo, the [scrollTarget](https://github.com/PolymerElements/iron-list/blob/master/demo/collapse.html#L153) is set to `html` but is not within the same scope so `iron-list` can't reach it.  We should fix the demo.
