### ISSUE TITLE
Resizing window causes scroll to jump around

### ISSUE THREAD

**Issue by nik3daz** [PolymerElements/iron-list#213]
Here's a simple JSbin: https://jsbin.com/daxugahipu/edit?html,css,output

When it loads the scroll is already off by 1px (you can't see the top-most border). If you scroll it to the top so the border is showing and resize the window at all, the scroll will jump back to the 1px offset. If you scroll to the bottom and resize, the scrollbar jumps too, I'm guessing to realign with the current item?

This issue can also be seen in [this demo](https://elements.polymer-project.org/elements/iron-list?view=demo:demo/index.html&active=iron-list). When the page loads, if you resize, the list jumps down and the header collapses.

It's also causing problems in Material History (enable it in chrome:flags on Canary) where the list jumps down to align with the first item when the window is resized. This feels a bit janky.

**Comment by blasten** [comment]
@nik3daz 
> When it loads the scroll is already off by 1px (you can't see the top-most border). If you scroll it to the top so the border is showing and resize the window at all, the scroll will jump back to the 1px offset.

That should be fixed by https://github.com/PolymerElements/iron-list/pull/215

> This issue can also be seen in this demo. When the page loads, if you resize, the list jumps down and the header collapses.

On resize, the list scrolls to the first visible item. That simplified the implementation and fixed rendering issues when we tried to preserve the `scrollTop`. I could take a look again to see if that is still strictly required.

**Comment by blasten** [comment]
fixed in master
