### ISSUE TITLE
List fails to yield to allow painting the first page before rendering remaining items

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerElements/iron-list#214]
### Description
The `_increasePoolIfNeeded` implementation is intended to render just enough items to fill the viewport then yield with a non-paint-blocking async to allow the on-screen items to be painted before creating the remaining 2 pages worth of off-screen items.  However, the intended implementation is no longer working, as the main thread is blocked until all items have rendered.  As such, the initial time to first paint of the list is longer than necessary.

After debugging a bit, It appears the reason that the [16ms debounce here](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L794) does not yield to allow paint as intended is due to an additional microtask `async` being queued in the same turn due to [this code](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L724).

#### Steps to Reproduce
Insert a `console.timeStamp('stamp');` call in the iron-list [here](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L768), open a demo, and refresh with the Timeline view in devtools open.

#### Expected Results
Calls to `stamp` are spread out over 3 frames.

#### Actual Results
All calls to `stamp` occur during the same frame.

### Browsers Affected
- [x] Chrome - only tested on Chrome, but believe all are affected
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- iron-list: v1.2.7

**Comment by blasten** [comment]
The list used to call rAF to allow enough paint. However, methods such as `scrollToIndex` requires to flush any async work before changing states. As you can see in line https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1192, `scrollToIndex` now calls `Polymer.dom.flush`, but that only works if all the async work is scheduled with `this._debounceTemplate` or `Polymer.dom.addDebouncer`.

This issue could be solved by allowing a new kind of debouncer that runs after paint. Any thoughts?
