### ISSUE TITLE
Polymer components after DEFAULT_PHYSICAL_COUNT not initialized

### ISSUE THREAD

**Issue by devkat** [PolymerElements/iron-list#216]
Example code:

```
    <iron-list items="[[users-data]]" as="user">
      <template>
        <paper-icon-item>
          <avatar-image avatar="[[user.id]]" item-icon></avatar-image>
          …
        </paper-icon-item>
      </template>
    </iron-list>
```

Observation:

The <avatar> components of the first 3 list items are initialized properly. Starting with the 4th element, a plain DOM node without the component properties is inserted. It's possible that I'm doing something wrong, but I can't spot it.

Thanks a lot in advance for any hints!

**Comment by devkat** [comment]
BTW, I'm using polymer-ts (defining components in Typescript).

It looks like the problem is related to the fact that polymer-ts puts the property initialization code in the constructor. The constructor (and factoryImpl) are not called for the affected components.

**Comment by devkat** [comment]
The problem is actually that the property is set before the constructor is called. Then the property is set to the default value in the constructor again.

Here is the order of invocation:

For components 1 to 3:

1. constructor
2. attached
3. property changed

For components 4 etc.:

1. property changed
2. constructor
3. attached

I implemented a workaround by calling the affected code from both the property observer and the attached() method.

**Comment by blasten** [comment]
@devkat are you using master or `v1.2.8`?
