### ISSUE TITLE
Focusing elements with list items erroneously toggles selection

### ISSUE THREAD

**Issue by Caffeinix** [PolymerElements/iron-list#220]
### Description
The documentation for the `selectionEnabled` property reads:

> Note that tapping focusable elements within the list item will not result in selection, since they are 
> presumed to have their * own action.

This does not reflect reality.  In fact, tapping a focusable element within the list item does toggle the selection, which it should not do for the reason expressed in the documentation.

### Expected outcome

Tapping a focusable element within an `iron-list` item should not modify the selected state of the item.

### Actual outcome

Tapping a focusable element within an `iron-list` item does modify the selected state of the item.

### Live Demo

https://jsbin.com/mipenebozi/edit?html,output

### Steps to reproduce

1. Create an `iron-list` element with `selectionEnabled` set to true.
2. Put a focusable element (such as a `paper-button`) into the list item template.
3. Bind the `selected` scope variable to something and add a style sheet so the selection is visible.
4. Add at least one item to the list model.
5. Click on the item to select it.
6. Click on the button.
7. Observe that the item is deselected.

### Browsers Tested

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
@Caffeinix this issue is confirmed.
