### ISSUE TITLE
Demo scroll-threshold.html doesn't load because of mixed content errors.

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-list#221]
https://elements.polymer-project.org/elements/iron-list?view=demo:demo/scroll-threshold.html&active=iron-list doesn't load because of mixed content issues.

<img width="1250" alt="screen shot 2016-03-28 at 7 46 03 pm" src="https://cloud.githubusercontent.com/assets/238208/14096444/b83ed750-f51d-11e5-91ec-bcf72b1732cb.png">

There's a good list of free public APIs here that we could use: https://github.com/toddmotto/public-apis

**Comment by blasten** [comment]
Thanks @ebidel I'd take a look :+1:
