### ISSUE TITLE
Uncaught TypeError: Cannot read property '_templateInstance' of null

### ISSUE THREAD

**Issue by fenerlee1907** [PolymerElements/iron-list#225]
### Description

Simplest iron-list working code leads to error below: 
"iron-list.html:1076 Uncaught TypeError: Cannot read property '_templateInstance' of null" 

Same error is marked as resolved recently (https://github.com/PolymerElements/iron-list/issues/180) but I still have the error. Today, I've checkout a clean Polymer and iron-list but the result is same.

iron-list version: 1.2.8
Polymer version: 1.4.0
### Expected outcome

Elements in iron-list has to be shown
### Actual outcome

Nothing is shown but an error message in the console
### Live Demo

https://jsfiddle.net/7apju810/1/
### Browsers Affected

- [ X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by Westbrook** [comment]
I also stumbled onto this same issue recently. However, this may be more of a documentation oversight than a code error in that while it doesn't seem to be explicitly stated anywhere, all of the examples of the contents of the `<template/>` element wrapped in a block level element, or in all cases in the documentation a `<div/>`. If you do the same with your fiddle then the code runs just fine.

@blasten, I saw you closed the last issue that was similar to this, should the code at current be supporting implementation without the block level element in the `<template/>`?

**Comment by blasten** [comment]
@Westbrook is right. I will mark this issue as something we should fix in the docs and/or improve the error messages.

@fenerlee1907 this should fix the issue:
```html
<dom-module id="x-foo">
  <template>
    <iron-list items="{{items}}">
      <template>
        <!-- you need this div  -->
        <div> [[item]] </div>
      </template>
    </iron-list>
  </template>
</dom-module>
```

**Comment by fenerlee1907** [comment]
Thanks for the replies. Yes, After putting a block element, problem is gone. Should I close the issue or wait until the documentation is added?

**Comment by OvermindDL1** [comment]
Hit the same issue, and wrapping the content in an element fixed it.  Currently the documentation at https://www.webcomponents.org/element/PolymerElements/iron-list/iron-list gives many examples as:
```html
    <template>
      ...
    </template>
```
Which implies that arbitrary content of arbitrary elements or text allowed.  Perhaps it should give the examples as:
```html
    <template>
      <div>
        ...
      </div>
    </template>
```
While also adding a paragraph stating that the element in the template should be a single element, not a text node?  Or perhaps one of `div` and another of, say, `paper-item` or something, just to show a single element of anything?

**Comment by keanulee** [comment]
I've added this note to the docs in https://github.com/PolymerElements/iron-list/commit/97af147bc6d4b11579ec891ff135012d4e7009e7
