### ISSUE TITLE
Closure Compiler errors at master

### ISSUE THREAD

**Issue by rictic** [PolymerElements/iron-list#231]
Transcribing from Vincent Price:

* Function `IronListElement.prototype._updateGridMetrics`: called with 1 argument(s). Function requires at least 0 argument(s) and no more than 0 argument(s).
```javascript
this._updateGridMetrics(true);
```

* Property `_viewportSize` never defined on `IronListElement`
```javascript
   if (this._viewportSize === 0) {
```

**Comment by blasten** [comment]
This issue was fixed. Thanks for filing an issue!
