### ISSUE TITLE
Iron-list items not in the right order in DOM after scrolling

### ISSUE THREAD

**Issue by emanuela-dominte** [PolymerElements/iron-list#233]
After scrolling on iron-list, items are not in the same order in DOM like they  appear on screen. This causes problems when I want to use css selectors to items.
This is the first item after I scroll the list:
<img width="876" alt="screen shot 2016-04-21 at 15 19 04" src="https://cloud.githubusercontent.com/assets/13848382/14708712/49f45d9a-07d5-11e6-9841-59d002314392.png">
There you can found second item:
<img width="899" alt="screen shot 2016-04-21 at 15 18 56" src="https://cloud.githubusercontent.com/assets/13848382/14708708/42c6f78a-07d5-11e6-9b21-95c2b40d521a.png">

**Comment by Westbrook** [comment]
What sort of selecting are you trying to select? If you are actually looking for something in the CSS, you might be better off using the `[[index]]` property in your template to give a specific selector to each element that is irrespective of it's order (visually or in the code).

```
<template>
    <div class$="item-[[index]]">[[item]]</div>
</template>
```

The was the the elements in the DOM are not directly related to the visuals they represent is part of how iron-list provides such great performance no matter the size of the dataset you are working with.

**Comment by emanuela-dominte** [comment]
Thank you for your response. I use "+" operator because my items have an attribute called level (from 0-10) and i want that items with same level to have border and border-radius between them and items with different levels to have margin between them. I don't think index can help me in this case.

**Comment by Westbrook** [comment]
Have you thought about using a computed version of your level attribute in the class? Then you could apply styles to `.item.level-*` after using `class$='item level-[[level]]'` for simple tracking. And, if you wanted to go deeper you could use something more complex like:

```
_computeStyle: function(item, index) {
var before = this.items[index - 1],
after = this.item[index +1];
if (item.level === before.level) }
...
}
``

That would allow you to not rely on order.
