### ISSUE TITLE
iron-list element does not accept key binding on 'down'

### ISSUE THREAD

**Issue by guirenard** [PolymerElements/iron-list#236]
### Description

The iron-list element does not accept key binding on 'down' anymore.

### Expected outcome

When I use
`this.$.myIronList.addOwnKeyBinding('down', 'myHandler');`

I expect myHandler to be executed.

### Actual outcome

My handler is not executed anymore because of this [commit](https://github.com/PolymerElements/iron-list/commit/19bb005672967b25d60ddd03eb509a09ed029ff9#diff-b97995700c5da5fa638d0324b5f3f861R1722)

-> e.detail.keyboardEvent.preventDefault();

BTW, thanks for the grid layout demo ;)

**Comment by blasten** [comment]
I can see the problem. What is the use case for adding a new handler for `down`?

**Comment by guirenard** [comment]
Here is a [jsbin sample](https://jsbin.com/kelozi/edit?html,output) which displays a toast each time the user presses **down** or **up** key.
(Note that I have to override the **_didMoveDown** method to make it work.)

Basically, I'd like to be able to perform additional actions when moving up and down the list, like selecting the new focused item.

**Comment by blasten** [comment]
Here's a different way to achieve this behavior: https://jsbin.com/licure/edit?html,output. I think that would satisfy your requirement.

**Comment by guirenard** [comment]
Thanks. Indeed, I can completely make it this way!

**Comment by sasivarnan** [comment]
I am using a `iron-autogrow-textarea` inside an `iron-list` element. When I add multi-line input, I am not able to navigate down using the down key, which makes it wired to use. Any workaround for that?
