### ISSUE TITLE
overflow: auto set unconditionally in element style

### ISSUE THREAD

**Issue by tgsergeant** [PolymerElements/iron-list#237]
### Description
In chrome://history, we want to set our `iron-list` to `overflow: overlay` so that the scrollbar does not take up space on the page (reserving space for the scrollbars knocks other elements out of alignment with the iron-list). However, the `_setOverflow` function unconditionally sets `element.style.overflow = 'auto'` on the iron-list element, which means we cannot override the overlay property without `!important` (yuck).

### Expected outcome

Setting

```css
iron-list {
  overflow: overlay
}
```
should result in `overflow: overlay` on the iron-list.

### Actual outcome

The iron-list remains `overflow: auto`

### Live Demo
https://jsbin.com/zuditevuwi/edit?html,output

Inspecting the iron-list element shows that it is `overflow: auto`, not `overflow: overlay`

**Comment by samuelli** [comment]
Is there precedence for setting values other than `overlay`? Given that `overflow: overlay` is a WebKit/Blink only feature, I'm not sure there's too much precedence in supporting this. `!important` may be the way to go here.

**Comment by Westbrook** [comment]
You might look at changing the `scroll-target` (from https://github.com/PolymerElements/iron-scroll-target-behavior) such that it is listening to an element you have free range to set the `overflow` to whatever you'd like.

**Comment by blasten** [comment]
As @samuelli suggested:

```css
iron-list {
  overflow: overlay !important;
}
```
Would that satisfy the requirement?

**Comment by tgsergeant** [comment]
Sure, the two different approaches suggested seem ok. We've since discovered an unrelated issue with `overflow: overlay` anyway, so we're probably not going to use it right away.

Thanks!
