### ISSUE TITLE
Click on inner button makes iron list scroll sometimes

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/iron-list#238]
### Description
With iron-list, collapsable and resizable items, sometimes the iron-list scrolls to a different location when click on inner  button.

Maybe mis-using element resizing but unlikely.

### Expected outcome

It should not be scrolling when user clicks.

### Actual outcome
**SOMETIMES** it scrolls to an expected location.
It seems it scrolls to the location of the "selected".

### Live Demo
It is reproducible with this demo, but I attached a video to show how tricky it can be to reproduce.
It is pretty much copy paste from the collapse.html example.
http://jsbin.com/jogokovodu/edit?html,output
https://www.youtube.com/watch?v=_T-jfe-_8XQ
### Steps to reproduce
1- Scroll down a fair amount (50 elements)
2- Expand 10 cards
3- Hit the "create" icon in the cards to add content
4- Scroll up/down and hit the "like" and "create" buttons randomly.

### Browsers Affected
- [x] Chrome
- [x] Firefox

**Comment by NicolasRannou** [comment]
It seems it jumps to the "current" selected element in the list, like scrollToIndex would.

**Comment by barnomics** [comment]
I notice this behavior too.  If you scroll very far down your list and before you click, ensure the first element in view is slightly cut off, you should be able to reproduce

**Comment by NicolasRannou** [comment]
Yes and the more buttons/elements you add the ore it seems to happen. I now have a couple paper-listbox inside my iron-list and it gets pretty unusable because when I click on an element of the list it just jumps up to the current element of the iron-list.

Could it be a focus issue?

**Comment by barnomics** [comment]
i feel like it's most definitely a forced focus issue.  There are a few **Polymer.dom.flush()** calls in the code that trigger the **_resizeHandler** ... inside that resizeHandler is a **scrollToIndex** call

**Comment by NicolasRannou** [comment]
Digging into it, it seems my issue is that sometimes, the "firstVisibleItem" of the list if bigger than the "lastVisibleItem" of the list, which should not happen.

Then isIndexVisible returns false and the list jumps to the focus element.
```
 _isIndexVisible: function(idx) {
      window.console.log('this.firstVisibleIndex');
      window.console.log(this.firstVisibleIndex);
      window.console.log('this.lastVisibleInde');
      window.console.log(this.lastVisibleIndex);
      return  idx >= this.firstVisibleIndex && idx <= this.lastVisibleIndex;
},
```

**Comment by NicolasRannou** [comment]
A new simpler fiddle that illustrates the problem - try to click in the item elements of the second element.

http://jsbin.com/cuyufe/edit?html,output

**Comment by NicolasRannou** [comment]
Closing in favor of #243
