### ISSUE TITLE
Sticky elements

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/iron-list#239]
Is it possible to make the list's element sticky very much like the inbox web app:

![sticky](https://cloud.githubusercontent.com/assets/214063/15041197/778b3540-12ba-11e6-9f74-101e8dda7fa1.gif)

**Comment by blasten** [comment]
No, it's not a feature of this element, but you could implement your own if you really want that behavior. :) I'm closing this issue for now.

**Comment by NicolasRannou** [comment]
@blasten Thanks,

Would you have any recommendation on the best way to observe the first and last visible indices in the iron-list?

Just checking the iron-list first/last visible indices on scroll? My concern with this approach is that is might be overkill and there could be some timing issues.

Maybe the iron list could fire first/lastVisibleIndex changed events or something like that?
