### ISSUE TITLE
scroll(0, 0) does not scroll to top

### ISSUE THREAD

**Issue by WrinklyNinja** [PolymerElements/iron-list#240]
### Description

Using iron-list's `scroll(0, 0)` method, or even just setting `scrollTop = 0` fails to scroll to the top of the list (or alternative scroll handler).

### Expected outcome

The list is scrolled to the top. This isn't necessarily the same as scrolling to the first item, eg. when using a parent element scroll target when the list has previous siblings, but I'm seeing this bug even in the simple case where the list is the target for its own scrolling.

### Actual outcome

The list is scrolled up, but not all the way to the top. A second invocation of `scroll(0, 0)` or `scrollTop = 0` then scrolls the list to the top correctly (it may be that more repetitions are required in the general case, but I've found that two are enough in my tests).

### Live Demo

I have been able to reproduce this in iron-list's own [collapsable items](https://elements.polymer-project.org/elements/iron-list?view=demo:demo/collapse.html&active=iron-list) and [basic list](https://elements.polymer-project.org/elements/iron-list?view=demo:demo/basic.html&active=iron-list) demo pages.

### Steps to reproduce

1. Scroll half way down the list.
2. Inspect the `iron-list` element using the browser's development tools
3. Call `$0.scroll(0, 0)` in the web console. ($0 apparently doesn't work in Edge, I had to use `document.querySelector('iframe').contentDocument.querySelector('iron-list').scroll(0,0)` instead for it).

The exact scroll distance necessary for the bug to occur is unknown, but I suspect anything beyond the point at which list elements start to get recycled is enough. The bug doesn't occur if you only scroll the first element just out of view.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge

Other browsers are untested.

**Comment by blasten** [comment]
@WrinklyNinja This seems to be a bug. Thanks for reporting it, should be fixed soon.
