### ISSUE TITLE
lastVisibleIndex not properly computed

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/iron-list#243]
### Description
When clicking on paper-item within an iron-list, it appears the lastVisibleItem is not properly computed when the iron-list receives the focus event.

Related to #238.

### Expected outcome

The last visible index should be properly computed.

### Actual outcome

The last visible index can be incorrect ( firstVisibleIndex -1 or undefined). As a result the iron-list scrolls to the firstVisibleIndex

### Live Demo
http://jsbin.com/cuyufe/edit?html,output
![ironlist](https://cloud.githubusercontent.com/assets/214063/15177434/5885108e-1770-11e6-937e-b8fed616d2cf.gif)
### Steps to reproduce

1. Reduce your browser height to make sure an element of the iron-list doesn't fit in the viewport
2. Scroll to 2nd element of the iron-list.
3. Click on first item
4. Scroll a bit down the 2nd element of the iron list to hide the image.
5. Click on an item

### Browsers Affected
- [x] Chrome
- [x] Firefox

**Comment by barnomics** [comment]
👍

**Comment by NicolasRannou** [comment]
I am wondering if the iron-list is supposed to receive the focus event from the button or if it just doesn't handle it properly.

```
_didFocus: function(e) {
      var targetModel = this.modelForElement(e.target);
       ...
```

The computed target model is the element from the iron list whereas I would expect it to be the paper-button.

Does it make sense?

**Comment by blasten** [comment]
@NicolasRannou You are right, there's a bug in `lastVisibleIndex`: https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L646-L649 The comparison is incorrect.

**Comment by NicolasRannou** [comment]
Awesome! Thanks! Will give it a try!
