### ISSUE TITLE
Default Item for Paged Data Loading

### ISSUE THREAD

**Issue by Westbrook** [PolymerElements/iron-list#244]
### Description
When you create a list and know that it has a large amount of items, but have only requested a single page subset of those items you either have to use the `iron-scroll-threshold` approach where the scrollbar slowly grows in size as you request more pages, or you have to create dummy items for the items you know exist but don't have which will penalize you with a non-fixed startup cost as your list of items becomes larger and larger. One option causes an undesirable UX situation while the other presents an undesirable initialization situation. If we were able to set items to `new Array(n)` and then have a `defaultItem` outline how to address situations where the index was within the context of the items array but currently `undefined` you could get a static initialization and a scrollbar reflecting a full load.

### Expected outcome
A `defaultItem` property allows you to outline the way that an item should display in the case that it has yet to be loaded.

### Actual outcome
You have to page with `iron-scroll-threshold` causing the scrollbar to change size over time, or you have pre-initialize every item in your list.

**Comment by Westbrook** [comment]
I've been working with a prototype implementation of `defaultImage` at https://github.com/Westbrook/iron-list

**Comment by blasten** [comment]
@Westbrook If the issue is the scrollbar, someone recently asked me the same question and the workaround is to set a height using the `--iron-list-items-container` mixin, e.g.

```css
--iron-list-items-container: {
  height: 10000px !important;
}
```
Would that satisfy your requirement?

**Comment by Westbrook** [comment]
I can see how this is similar, but it doesn't explicitly match what I'm trying to do.  I do tell the list how many items I'm working with, which I had hoped would allow the scroll bar to set, but doesn't because I'd like to not have to set a larger number of list members to a default only to init the layout. Let me see if I can explain this better.

Let's say I have a list that I would like to populate with 1000 items. I want to build of the ideas of `iron-input` to only load images inside and in proximity to my view port, so I just request the first 50.  If I use something like `ironList.items = new Array(1000); itemList.splice('items', 0, 50, serverData);` I'll get something that is in the direction of what I want, in that the first 50 elements will be viewable, but first, the understood height of the list won't calculate, meaning the scroll bar size and placement will be incorrect in relation to the larger experience, and second you would never be able to see a "loading"/default version of elements 51 - 1000. This is particularly because in `_assignModels`, an undefined element is skipped: https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1179 I would like the `defaultItem` property in my demo code such such that elements 51 - 1000 would take up space and be allowed to appear with an individual loading message while I wait for my server requests to catch up.

In a smaller use case, if I use: `ironList.items = new Array(10); itemList.splice('items', 0, 1, serverData);` the results of that list of items would be something like:

```
--implied viewport start
severData //has height, layout, etc because it was filled by server data
--implied viewport end
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
undefined //has no height, layout, etc because there was no data in the item
```

I'd like the `defaultItem` property to allow my list to look like:

```
--implied viewport start
severData //has height, layout, etc because it was filled by server data
--implied viewport end
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
defaultData //has height, layout, etc because it was filled by default data
```

That way I could track the scroll bar correctly, and have a default item display when server data for the element wasn't ready yet. Outside of that, I could track `lastVisibleIndex` and `firstVisibleIndex` in conjunction with my available server data to make further requests to data as needed and splicing the response into my `items` list would not effect the scroll bar context and would only update the layout of each element from the `defaultData` to the `serverData` for that index.

Does that make better sense? I'll see if I can get a version of the actual implementation on a public server to help explain what I'm hoping to achieve.

**Comment by blasten** [comment]
I see, I think your use case can be summarized as  `the scrollbar's track should be at the correct position  regardless of how many items are initially fetched`. Please correct me if that is incomplete or incorrect. 
The scrollbar track would be at the correct position if the list knew the size of the content upfront. e.g. you tell the list how many items are in the storage collection.  e.g. `ironList.size =  100000;` but in your case `ironList.items.length` may just contain 10 objects. Similar to how UIKit does this work.  Question:  do all the items have the same height?

**Comment by Westbrook** [comment]
This is one side of it, yes. A lot would be won in my experience if what you mentioned were possible, especially because the items are all the same size. 

However, the other side is when items in view have yet to be returned from the server and I would like to display the `defaultItem`. This way I could have those items awaiting data have a fixed layout. 

For instance, imagine this item template:

[[thumb]] //fixed aspect image
[[Title]] //single line of ellipsised text
[[type]] //image || video || media

I'd like each element that way yet to be loaded to display a placeholder thumb, "Loading..." As the title, and "Media" for not knowing which will be available. Hence wanting push `defaultItem` in the model assignment at line 1179.

**Comment by blasten** [comment]
I see, yes. The only alternative would be to add a few item instances that can toggle a `<template is="dom-if"` based on a property of the items. e.g. `isPlaceholder: true`. I know this is not amazing, but this element doesn't support multiple templates right now. afaik, I think we might have that feature for 2.0, but as of now, I'd recommend using `<template is="dom-if">` to switch between the two UI components. The code would look something like:

```js
items = [];
while (items.length < 10) {
  items.push({ isPlaceholder: true });
}

list.items = items;
```
and in the template:

```html
<iron-list> 
  <template>
    <template if="[[item.isPlaceholder]]">
      <div>placeholder item</div>
    </template>
    <template if="[[!item.isPlaceholder]]">
      <div>item</div>
    </template>
  </template>
</iron-list>
```

**Comment by Legioth** [comment]
The example in the previous comment makes sense in with 10 missing items, but what if there are 1 000 or even 100 000 items, and all except the first 20 are missing? You'd then use a lot of CPU and memory just for building the dummy data.

Using `<template is="dom-if"> ` inside the item template to handle placeholders is quite acceptable, but the problem is still that it's very inefficient to populate `{ isPlaceholder: true }` into the 99 980 items in the array for which no data exists. This could be avoided if `<iron-list>` could be configured to use that object whenever there isn't an entry in `items`.

It's also worth pointing out that JS supports sparse arrays, so a 100 000 item array with only 20 slots populated uses very little memory.
