### ISSUE TITLE
Incorrect items per row with percental item width in grid view.

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/iron-list#246]
### Description
The measured item width is full integer due the use of offsetWidth. 
If the viewport width is odd and the item width is in %, this is imprecise.
getBoundingClientRect().width would retrieve the exact width.

e.g. Viewport width 499, item width 50%.

### Expected outcome
Measured item width 249.5, leading to two items per row.

### Actual outcome
Measured item width 250, leading to one item per row.

**Comment by blasten** [comment]
I see, easy fix.
