### ISSUE TITLE
item not being removed when using shadow dom in chrome

### ISSUE THREAD

**Issue by josiah47** [PolymerElements/iron-list#247]
### Description
when using shadow dom iron-list items are not being removed after array binding splice. But does work when using default shady dom.

`	<script>
		/* this script must run before Polymer is imported */
		window.Polymer = {
			dom: 'shadow'
		};
	</script>
`

Works fine in FF but not in chromium/chrome
### Expected outcome
the item should be removed

### Actual outcome
visible items stay, and labels are overwritten with other label's text

### Live Demo
Reusing example jsbin from this post
http://stackoverflow.com/questions/34627793/polymer-1-x-deleting-an-item-from-iron-list

http://jsbin.com/qefemoloxi/1/edit?html,console,output

just add this after webcomponents include
`	<script>
		/* this script must run before Polymer is imported */
		window.Polymer = {
			dom: 'shadow'
		};
	</script>
`

### Steps to reproduce
1. click on rendered elements to remove
2. change dom: 'shady' and it works

### Browsers Affected
- [x] Chromium - 50.0.2661.75 (64bit)
- [x] Chrome - 50.0.2661.75 (64bit)
- [x] Vivaldi - 1.1.453.59
- [x] Opera - 37.0.2178.32
- [ ] Firefox - 45.0.1

**Comment by blasten** [comment]
In 1.0, the API is slighly different. `splice`, `push`, `pop`, `shift` and `unshift` need the path, so the element can see the mutations to the array property:
```js
list.splice('items', e.model.index, 1);
```
