### ISSUE TITLE
Cannot reference properties outside of 'item' scope.

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#25]
Core-list allowed references to properties and functions of the parent object.  So, for example, I had a text input field whose input value is bound to a search property of the parent element.  I would wire this search property into the list-item element and the child elements would highlight matching text.

With iron-list, whenever I try to reference any property outside of the item object or index, I get the following error: `this.fire is not a function`.  I specifically created a new, text-only property and set default values and the issue persisted, so I am fairly confident that I isolated the cause.

**Comment by blasten** [comment]
@indolering You can use:
```js
list.set(keyPath,  value);
```

For example, if you open one of the examples included in iron-list, and run: 
```js
document.querySelector('iron-list').set('items.0.name', 'test');
```
You should see the update.

**Comment by indolering** [comment]
Yes, I realize I can embed the global value into the item, but that's a hack and it doesn't support the standard pattern of using a shared property between elements.  The following should result in an error:

```
<dom-module id="parent-element">
<input id="filter" value="{{search::input}}" type="search">
 <template>
    <iron-list id="domain_list" items="[[records]]" as="item">
      <template>
          <child-element record="{{item}}" search="{{search}}">
          </child-element>
      </template>
    </iron-list>
 </template>
</dom-module>

<script>
  Polymer({
    is: "parent-element",
    properties: {
      /**
       * Filtered search input.
       */
      search: {
        type: String,
        value: ""
      }
    }
  });
</script>
```
I haven't tried replicating this on a fresh seed-element install, but I can if you think it should be working.

**Comment by indolering** [comment]
I changed the title to try and better reflect the problem....

**Comment by blasten** [comment]
your search input  is outside of template. 
The following works fine:

```html
<dom-module id="parent-element">
<style>
  :host {
    @apply(--layout-fit);
    @apply(--layout-vertical);
  }


  iron-list {
    @apply(--layout-flex);
  }
</style>
<template>

<input id="filter" value="{{value::input}}" type="search">
    <iron-ajax url="data/contacts.json" last-response="{{records}}" auto></iron-ajax>
    <iron-list items="[[records]]" as="item">
      <template>
      <paper-slider min="0" max="100" value="{{value}}"></paper-slider>
      </template>
    </iron-list>
 </template>
</dom-module>
<script>
  HTMLImports.whenReady(function() {
  Polymer({
    is: "parent-element"
  });
});
</script>
<parent-element> </parent-element>
```html

**Comment by indolering** [comment]
I wrote that example on the fly, my actual implementation was properly nested in a template element and it did not work.  However, iron-list 1.0.1 seems to have fixed the issue.
