### ISSUE TITLE
Offscreen focus backfill item never updates

### ISSUE THREAD

**Issue by tgsergeant** [PolymerElements/iron-list#253]
### Description

When a physical item is hidden offscreen as `_offscreenFocusedItem`, it will no longer receive updates to its model, even after it is scrolled into view.

This causes [a bug in Chrome's Material Design History page](https://crbug.com/617482).

### Expected outcome

I should be able to modify any element while it is offscreen, and have those changes reflected when it comes back onscreen.

### Actual outcome

The changes I make to the offscreen item are never shown.

### Live Demo
JS Bin: https://jsbin.com/jofohivoji/edit?html,output

It only appears to work properly in [popout output mode](https://output.jsbin.com/jofohivoji)

### Steps to reproduce

1. Open JS Bin link
2. Scroll halfway down page, click the 'push new item' button. Note that all visible list items have their 'Number of items' count updated.
3. Scroll back to top of page. Note that the first element still has 'Number of items: 500'

Further,

1. Refresh page
2. Without scrolling, click 'push new item'.
3. Note that the count shown by the first element *is* updated

### Browsers Affected

- [x] Chrome
- [x] Firefox

[I don't have any of the others available to test right now]
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
@tgsergeant in the jsbin, it should be `longText` instead of `longtext`.  That fixes the issue in the jsbin, but I can reproduce it in https://elements.polymer-project.org/bower_components/iron-list/demo/index.html if I pick an `index > 0`

**Comment by blasten** [comment]
Fixed via https://github.com/PolymerElements/iron-list/pull/261

**Comment by tgsergeant** [comment]
Thanks!
