### ISSUE TITLE
Pad updateSizeForItem with async

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#259]
I call `updateSizeForItem` after manually updating a record using the `this.set("path", value)` command but I've run into instances where `updateSizeForItem` updates the size before the data binding kicks in.  It would be best if `updateSizeForItem` was wrapped in an `async` callback to allow Polymer's data binding system to catch up.

I can make this patch myself, but I've run into edge cases where a simple async call isn't enough, but padding it by 10ms seems to fix the issue.  Is there a better fix or is that good enough?

**Comment by blasten** [comment]
closing this issue in favor of https://github.com/PolymerElements/iron-list/issues/260
