### ISSUE TITLE
Hidden attribute doesn't work unless element is wrapped in a div.

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#26]
The hidden attribute is not honored unless the element is wrapped in a div or another element.  I know this sounds really strange, but I was able to duplicate the problem on the iron-list `demo1` page.

For example, trying to set hidden as an HTML attribute or using JavaScript from within the element (in either the ready or attached callback) will fail with the following template HTML:

      <iron-list id="domain_list" height="40" style="overflow: scroll" items="[[matching]]" as="item">
        <template>
          <easy-reg-record hidden
            class="row">
          </easy-reg-record>
        </template>
      </iron-list>

But if you wrap `easy-reg-record` with a `<div>` tag, it will work.

**Comment by blasten** [comment]
@indolering right. iron-list controls the `hidden` attribute for the first element in the template. I would recommend using:

```html

  <iron-list id="domain_list" height="40" style="overflow: scroll" items="[[matching]]" as="item">
    <template>
     <div>
        <easy-reg-record hidden class="row"></easy-reg-record>
      </div>
    </template>
  </iron-list>
```

**Comment by Flamenco** [comment]
I had this issue, fix it after viewing this thread, and then added a class name to the div;  The insanity started all over again :(

```
<style>...</style>
<iron-list id="domain_list" height="40" style="overflow: scroll" items="[[matching]]" as="item">
    <template>
      <style> .item[hidden] { display:none; } </style>
     <div class='item'>
        <easy-reg-record hidden class="row"></easy-reg-record>
      </div>
    </template>
  </iron-list>
```
The workaround was to add an additional style to the class, as shown below.
```
<style> .item[hidden] { display:none; } </style>
<iron-list id="domain_list" height="40" style="overflow: scroll" items="[[matching]]" as="item">
    <template>
     <div class='item'>
        <easy-reg-record hidden class="row"></easy-reg-record>
      </div>
    </template>
  </iron-list>
```

@blasten, Would it be possible for the iron-list to target the first item in a way that these workarounds are not needed?
