### ISSUE TITLE
Add Item in hidden iron-list doesn't update its rendering once reposted.

### ISSUE THREAD

**Issue by ystreibel** [PolymerElements/iron-list#263]
### Description
When we add item to hidden iron-list, its rendering isn't update.

### Expected outcome
Iron-list rendering is updated when the list is hidden.

### Actual outcome
Iron-list rendering isn’t updated when the list is hidden.

### Live Demo
See the demo [here](https://t.co/HtHtwa2Jsq https://t.co/ejshdi6WQl)

### Steps to reproduce

1. Hide the list by taping more button.
2. Add item by taping plus button.
3. Show the list by taping more button. There is a missing item.
4. Resize the page. Item appears.

![](http://s31.postimg.org/bdv2rog4r/iron_list_issue.gif)

### Browsers Affected
- [X] Chrome

**Comment by tpluscode** [comment]
As tony19 [correctly answered on SO](http://stackoverflow.com/a/37801657/1103498), `_render` method is not called when the element is invisible. I think that changing items should force the list to render when it is made visible again

**Comment by blasten** [comment]
question answered! I'm closing this issue for now, but feel free to reopen if needed.
