### ISSUE TITLE
Prefered solution for alternating background color

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#269]
Using `nth-of-type(2n)` selectors to alternate the background color of list items doesn't work because `iron-list` reorders physical elements on the fly, leading to visuals like the following:

![image](https://cloud.githubusercontent.com/assets/44454/16173574/25bf3d5c-355a-11e6-97fa-a9c274bc3530.png)

The best solution I can think of is to pass the array into the item, check if it's record is even or odd, and then either redefine a custom style or swap out classes.  I'm guessing others will want this functionality and was thinking of posting the code.  Would this be the preferred method or is there a better solution?

**Comment by blasten** [comment]
> The best solution I can think of is to pass the array into the item, check if it's record is even or odd, and then either redefine a custom style or swap out classes. 

I'd recommend doing that. e.g.
```html
<template>
  <div style$="background-color:[[_getBackgroundColorForIndex(index)]]">
  </div>
</template>
```
