### ISSUE TITLE
iron-dropdown elements are not considering z-index inside iron-list

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/iron-list#273]
### Description
If any iron-dropdown element, e.g. an paper-menu-button is placed inside an iron-list item, the dropdown is behind the other iron-list items content. This issue was also described in #158 but not solved.

### Expected outcome
The dropdown is on top.

### Actual outcome
The other items are over the dropdown.

### Live Demo
https://jsbin.com/kamenomibu/edit?html,output

### Browsers Affected
- Chrome
- Firefox

**Comment by bwh-rl** [comment]
I think this issue comes from the use of translate3d(x,y,z), the z value has higher priority than the z-index.
Adding translate3d(0,0,1px) to the iron-dropdown does not solve this problem.
Adding transform-style:flat; to the iron-list items does not solve this problem.

**Comment by NicolasRannou** [comment]
See #242

**Comment by blasten** [comment]
I'm closing this issue in favor of #242
