### ISSUE TITLE
Improve documentation of selected-item-changed

### ISSUE THREAD

**Issue by andrew-vandenbrink** [PolymerElements/iron-list#282]
I believe the demo is too complex 
https://elements.polymer-project.org/bower_components/iron-list/demo/selection.html

While this code works

```
var list = document.querySelector('iron-list');

list.addEventListener('selected-item-changed', function (e) {
if (e.detail.value != null) {
   console.log(e.detail.value);            
 }

```

I barely able to find it in documentation.

**Comment by blasten** [comment]
Sure. I wonder what was particularly complex? `selected-item` is a property that notifies (https://elements.polymer-project.org/elements/iron-list#property-selectedItem) meaning that it fires the `{property-name}-changed` event when its value has changed.

**Comment by andrew-vandenbrink** [comment]
It's too complex because you use two iron-list in the demo, a simple demo which show iron-list selected item being changed with text box should be easier to understand.

Not sure why paper-checkbox documentation have **"Events"** while iron-list is not.
https://elements.polymer-project.org/elements/paper-checkbox

**Comment by blasten** [comment]
Yeah, there should be a simpler demo. Those events are fired in addition to the events fired from properties that notify. https://www.polymer-project.org/1.0/docs/devguide/properties#notify

**Comment by andrew-vandenbrink** [comment]
I just know polymer can do that...
but I have to read the source code to know if certain properties have notify=true

**Comment by blasten** [comment]
The docs mention that this property notifies: https://www.webcomponents.org/element/PolymerElements/iron-list/iron-list#property-selectedItem
