### ISSUE TITLE
<iron-list> only render 3 items on 20 items, resizing will render all 20 items

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/iron-list#283]
Refering to the similar code from documentation below:-

```html
<!doctype html>
<html>
<head>
  
  <title>iron-list-test</title>

  <meta charset="utf-8">

  <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  
  <link rel="import" href="../bower_components/polymer/polymer.html">
  <link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout.html">
  <link rel="import" href="../bower_components/iron-ajax/iron-ajax.html">
  <link rel="import" href="../bower_components/iron-list/iron-list.html">
  
</head>

<body unresolved>
  <demo-1></demo-1>
  
  <dom-module id="demo-1">
    <template>
      
      <style>
        
        iron-list {
          @apply(--layout-fit);
        }
        
        .item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
        }
        
      </style>
      
      <iron-ajax url="data/data.json" last-response="{{data}}" auto></iron-ajax>
      <iron-list items="[[data]]" as="item">
        <template>
          <div class="item">
            #[[index]] - [[item.name]]
          </div>
        </template>
      </iron-list>
    </template>
    
    <script>
      Polymer({
        is: "demo-1"
      });
    </script>
  </dom-module>
</body>
</html>
```
`data.json`:-
```json
[
  {"name": "Bob"},
  {"name": "Tim"},
  {"name": "Mike"},
  {"name": "Bob"},
  {"name": "Tim"},
  {"name": "Mike"},
  {"name": "Bob"},
  {"name": "Tim"},
  {"name": "Mike"},
  {"name": "Bob"}
]
```

`<iron-list>` will only render first 3 item upon reload, and only render all 20 item upon resizing browser.

I notice the [Basic list](https://elements.polymer-project.org/bower_components/iron-list/demo/basic.html) demo uses `iron-flex-layout` to overcome similar rendering issue/symptom, which I am trying to apply to the code above. Am I missing something?

**Comment by blasten** [comment]
`unresolved` is causing this behavior. If you add the following rule, then the issue is fixed:
```css
body {
  height: 100vh;
}
```
http://jsbin.com/sijecoj/edit?html

**Comment by andrewspy** [comment]
@blasten I can confirm that your solution fix the issue, but may I know why is this happening. And, how come the same issue is not happening with [Basic list](https://elements.polymer-project.org/bower_components/iron-list/demo/basic.html) demo?

**Comment by UiCandy** [comment]
This is still an issue in the latest version, cannot get more than 3 item to render. The Index.html has min-height: 100vh specified out of the box but still won't load, any ideas?

**Comment by blasten** [comment]
@UiCandy chances are that the size isn't set. You can take a look at https://github.com/PolymerElements/iron-list#sizing-iron-list and let me know if that helped you fix the issue!

**Comment by dman777** [comment]
I am having this exact issue also. I set explicity set the size on both `body` and `iron-list` and I only get 3 items until I resize the browser/viewport. Can this be re-opened?

**Comment by dman777** [comment]
I am having this issue only when viewing on S7 cellphone. *Not* on desktop, only on my cell phone.[Reference #390](https://github.com/PolymerElements/iron-list/issues/390)

**Comment by yebrahim** [comment]
Can we re-open this? I'm seeing the same issue on desktop, feeding the list four items only displays three until resized.

**Comment by ppeou** [comment]
I too is facing this issue. Please investigate this.
