### ISSUE TITLE
Grid layout mode doesn't correctly update the virtual items

### ISSUE THREAD

**Issue by Sleeckx** [PolymerElements/iron-list#284]
### Description
When using the grid layout mode with a "large" amount of items, e.g. 1000, scrolling through the list doesn't always correctly update the rendered items according to the position of the scrollbar.

### Expected outcome
The grid layout should update items consistently.

### Actual outcome
The items don't always get refreshed correctly during scrolling, especially after pressing home/end on the keyboard. The following screenshot shows the outcome after scrolling to the bottom and then back to the top:

![image](https://cloud.githubusercontent.com/assets/2143495/17102197/ddd8500a-5278-11e6-8028-a67483dc19ff.png)

### Live Demo
http://jsbin.com/tegifiyuba/edit?html,output

### Steps to reproduce
Enable the grid layout mode on iron-list and scroll through the list.

**Comment by blasten** [comment]
I can reproduce the issue. Thanks!

**Comment by Westbrook** [comment]
@blasten you listed this as a "small-fix", but I know you've been pretty busy lately. If you had a rough direction as to where you thought this issue originated, I'd be glad to see if I might help mark this issue off your to-do list.
