### ISSUE TITLE
iron-list (grid layout) shift visible elements when tap on paper-menu-button  inside an item

### ISSUE THREAD

**Issue by Eymerich01** [PolymerElements/iron-list#287]
### Description
iron-list (grid layout) shift visible elements when tap on paper-menu-button  inside an item.

### Live Demo
https://jsbin.com/lozixipoke/edit?html,output

### Steps to reproduce
use scroll to go mid-list then tap on "more-vert" icon. you could see that iron-list shift items up almost a row.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
repeated issue: https://github.com/PolymerElements/iron-list/issues/288
