### ISSUE TITLE
Items with a 'title' property raise an illegal invocation exception

### ISSUE THREAD

**Issue by rictic** [PolymerElements/iron-list#29]
Apparently accessing the 'title' property of a TemplateInstance raises an exception, at least in Chrome.

Here's a minimal repro:

```html
<!doctype html>
<html>
<head>
  <title>iron-list title crash</title>

  <base href="http://polygit.org/polymer+:master/components/">

  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="polymer/polymer.html">
  <link rel="import" href="iron-list/iron-list.html">

  <dom-module id="x-app">
    <template>
      <iron-list items="[[data]]">
        <template></template>
      </iron-list>
    </template>
  </dom-module>

  <script>
    Polymer({
      is: 'x-app',
      properties: {
        data: {
          value: function() { return [{title: 'I break things'}] }
        }
      },
    });
  </script>
</head>
<body unresolved>

  <x-app></x-app>

</body>
</html>
```
jsbin link: http://jsbin.com/qobitotiwi/edit?html,output

**Comment by blasten** [comment]
This is an issue in Polymer and it's related to https://github.com/PolymerElements/iron-list/issues/19

**Comment by blasten** [comment]
@tasosno1 This issue was fixed  after https://github.com/PolymerElements/iron-list/commit/37726c5016139ff942a3edde3711663f6f2d9768, so it's available in https://github.com/PolymerElements/iron-list/releases/tag/v1.0.1 :)

**Comment by tasosno1** [comment]
@blasten -- excellent thanks :)
