### ISSUE TITLE
lower-threshold of iron-scroll-threshold fires everytime I scroll

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-list#290]
_From @ziszo on August 4, 2016 9:39_

### polymer-cli v0.13.0

lower-threshold fires everytime I scroll.

```
<iron-scroll-threshold id="scrollThreshold"
        scroll-target="document"
        lower-threshold="500"
        on-lower-threshold="loadMoreData">
      </iron-scroll-threshold>
```
script:
```
			loadMoreData: function(e) {
				console.log('load more');
				this.$.scrollThreshold.clearTriggers();
			}
```

_Copied from original issue: PolymerElements/iron-scroll-threshold#11_

**Comment by blasten** [comment]
Did it reach the end of the scrollable content? If yes, that's the expected behavior.

**Comment by blasten** [comment]
_From @ziszo on August 6, 2016 14:51_

It fires even if I scroll a bit, not reaching the bottom.

**Comment by blasten** [comment]
_From @minhlong139 on August 8, 2016 14:18_

I think the problem is the first time iron-list has 0px ~ is reaching the bottom so iron-scroll-threshold raise lower event. See attachment: demo has the same problem

<img width="941" alt="screen shot 2016-08-08 at 21 15 16" src="https://cloud.githubusercontent.com/assets/171335/17482723/4780118e-5dad-11e6-87ca-5d8a65d3d416.png">

**Comment by TrebuhD** [comment]
The fix for this doesn't help in my case. I'm still having this problem. For now I'll probably ditch `iron-scroll-threshold` and write a custom solution.

**Comment by TrebuhD** [comment]
Solved. In my case, it was caused by having the fullbleed property set on app-layout.
