### ISSUE TITLE
List scrolls (too much) on resize

### ISSUE THREAD

**Issue by robjepopje** [PolymerElements/iron-list#309]
### Description

When resizing an iron-list it tries somehow to reposition on the first visible item.
### Expected outcome

The list should not scroll at all. (Except when the size increases and the end of the list is reached and is longer than the viewport.)
### Actual outcome

List scrolls unexpectedly to reposition on the first visible item.
### Live Demo

https://elements.polymer-project.org/bower_components/iron-list/demo/selection.html.
Make the window bigger or smaller. The list starts scrolling.
### Steps to reproduce

See 'Live Demo'.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
This should be fixed #346
