### ISSUE TITLE
Dynamically adding one `<template>` changes `<iron-list>` but adding a second does not.

### ISSUE THREAD

**Issue by gaurav21r** [PolymerElements/iron-list#310]
### Description

Dynamically adding one `<template>` changes `<iron-list>` but adding a second does not.
### Expected outcome

`<iron-list>` should've changed. 
### Actual outcome

It remains `template1`.
### Steps to reproduce

1) Create a template 1:

``` html
          <template id="template1">
            <div style="display: flex; flex-direction: row">
              <div style="flex-grow: 1"> {{item.name}} </div> | 
              <div style="flex-grow: 1"> {{item.average}} </div> | 
              <div style="flex-grow: 1"> {{item.sr}} </div> | 
            </div>
          </template>
```

2) Create a template2:

``` html
          <template id="template2">
            <div style="display: flex; flex-direction: row">
              <div style="flex-grow: 1"> {{index}} </div>
              <div style="flex-grow: 1"> {{item.name}} </div>
            </div>
          </template>
```

3) Create an iron-list

``` html
          <iron-list id="list" style="display: flex; height: 200px">
          </iron-list>
```

4) Create the items

``` html
          <script>
          window.theItems = [{
            name: 'Sachin',
            average: 50,
            sr: 80
          }, {
            name: 'Virender',
            average: 35,
            sr: 93
          }, {
            name: 'Dravid',
            average: 45,
            sr: 60
          }]
          </script>
```

5) In the Browser console when we

``` js
Polymer.dom(document.getElementById('list')).appendChild(document.getElementById('template1'));
document.getElementById('list').items = theItems
```

It works!

6) But after that when we do

``` js
Polymer.dom(document.getElementById('list')).appendChild(document.getElementById('template2'));
document.getElementById('list').items = theItems
```

The iron-list remains unchanged. I don't know much about `Polymer.templatizer` but does that have to do with something for this? We were thinking of using this for our grid element. And specific use cases of **column reordering**, **column hiding** etc would require dynamic template manipulation from within <iron-list>.

I understand if dynamic templates don't work at render time. But when the first template was included via the console (after the render of `<iron-list>`) it worked! And with the data binding intact! This shows templates can be added at runtime. Why can't templates be **changed** at runtime? Is there some `refresh()` method of `<iron-list>` we are missing?
### Browsers Affected

Only tested on
- [x] Chrome

**Comment by gaurav21r** [comment]
@blasten @notwaldorf Any updates on this? Please ping if you need help recreating this issue.

**Comment by blasten** [comment]
@gaurav21r yeah it doesn't support that use case. I will ask @kevinpschaaf about this use case.
