### ISSUE TITLE
Iron list not showing items in chrome

### ISSUE THREAD

**Issue by baljeetbhinder** [PolymerElements/iron-list#311]
### Description
Hi I am new to polymer elements. I want to use lazy loading list in my page. So I used iron-list component. Below is the syntax that I use to produce the list:

`<iron-ajax url="../../demo-data/iron-list.json" last-response="{{data}}" auto></iron-ajax>
<iron-list items="[[data]]" as="item">
    <template>
      <div>
        Index: [[index]] Name: [[item.name]]
      </div>
    </template>
</iron-list>`

### iron-list.json contains:
[
  {"name": "Bob"},
  {"name": "Tim"},
  {"name": "Tim2"},
  {"name": "Tim3"},
  {"name": "Mike"}
]

### Output
the output is fine in firefox it produces the list correctly. But when I try to run this code in chrome the list is not getting produced but the following(see below)
![iron list output from chrome](https://cloud.githubusercontent.com/assets/8347607/18300017/0c4437d8-74e3-11e6-8234-29da029c2175.png)

if you notice there are only 3 entries getting printed (that too without any data in it) where as the iron-list.json file has 5.
Any idea about what is causing it and what do I need to do to make it work on all the browsers?

Thanks

**Comment by blasten** [comment]
It sounds like you need to set the size of the list: https://github.com/PolymerElements/iron-list#sizing-iron-list There are a few example in the readme explaining how to do it. Feel free to reopen if you still have issues.

**Comment by baljeetbhinder** [comment]
@fafcrumb  @blasten 
I believe its not the sizing issue.
also I have tried this:

`<style>
.list-container{
display: block;
height: 200px;
width: 400px;
display: flex;
padding: 50px;
flex-direction: column;
}
iron-list {
flex: 1 1 auto;
}
</style>

<iron-ajax url="../../demo-data/iron-list.json" last-response="{{data}}" auto></iron-ajax>
<div class="list-container">
	<iron-list items="[[data]]" as="item">
	    <template>
	      <div>
	        Index: [[index]] Name: [[item.name]]
	      </div>
	    </template>
	</iron-list>
</div>`
here is the output from above code on both of browsers
![iron-list-chrome](https://cloud.githubusercontent.com/assets/8347607/18338485/ee0e22b8-75b6-11e6-94a6-53388d23aa01.png)
![iron-list-firefox](https://cloud.githubusercontent.com/assets/8347607/18338486/ee12717e-75b6-11e6-8780-a71ddbd1f0ea.png)
