### ISSUE TITLE
Iron-list resizes improperly when switched to in an iron-pages element

### ISSUE THREAD

**Issue by fafcrumb** [PolymerElements/iron-list#312]
### Description
Not sure if this an iron-list or iron-pages issue. Or if I'm just missing something obvious.
Using `scroll-target="document"` on iron-list and iron-pages to switch between the list and another `div`
The list works perfectly when the list page is the first one loaded, but gets all messed up when switching pages, rendering way more elements than required for the view-port (renders about 500). The iron-resize event is automatically fired by iron-pages, and I've confirmed the list receives the event, but something must be wrong with the view-port size calculation.

### Expected outcome

Iron-list recalculates size correctly and renders only enough elements for the view-port after switching iron-pages.

### Actual outcome

Size isn't calculated correctly and hundreds of elements are created after switching pages.

### Live Demo
http://jsbin.com/huqodekiro/edit?html,output
![iron-list-demo](https://cloud.githubusercontent.com/assets/17421035/18321651/df6a9cba-74fc-11e6-82bf-5a4d0f8d6658.gif)

### Steps to reproduce

1. Create an iron-list with `scroll-target="document"`
2. Wrap it in an iron-pages element
3. Switch between pages

### Browsers Affected

Tested in Chrome and Firefox

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
@fafcrumb You are right. Thanks for filing this issue. The problem is that `_isVisible`checks for visibility of the scroll target instead of the list element itself. https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L681-L683

**Comment by fafcrumb** [comment]
Kudos for the quick response/fix!

I implemented the fix, which solves the issue, but only when the scroll position is at the top during the page change. Moving the scroll position down some distance, then changing pages, results in the same behavior as above. Should I file a separate issue for this?

**Comment by blasten** [comment]
@fafcrumb I see. This issue is fine!

**Comment by fafcrumb** [comment]
@blasten Any road-map on an updated fix? Really need to use this in a project.

**Comment by blasten** [comment]
once [this PR](https://github.com/PolymerElements/iron-scroll-target-behavior/pull/23) I can fix the issue in iron-list.
