### ISSUE TITLE
iron-list jumps when a descendant iron-pages exists

### ISSUE THREAD

**Issue by 43081j** [PolymerElements/iron-list#318]
### Description

If you have an `iron-list` which, somewhere down the tree, has an `iron-pages` as a descendant, it will cause the list to reset scroll position to the first visible item when interacted with.

This is because, when an `iron-pages` element changes selection, it fires an iron-resize event [here](https://github.com/PolymerElements/iron-pages/blob/master/iron-pages.html#L82).

This event has previously been listened for by the parent `iron-list`, because it is an [interested resizable](https://github.com/PolymerElements/iron-resizable-behavior/blob/master/iron-resizable-behavior.html#L157).

Both of these things combined results in the [resize handler](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1499) being called, which then scrolls to the first visible item of the list.

Not entirely sure if this is an `iron-list` issue, if it is considered an issue at all. It may well be that in cases like this, there is/should be some recommended way to combat the effect? Rather than a "fix".
### Expected outcome

Scroll position is maintained.
### Actual outcome

Scroll position resets to the first visible item.
### Live Demo

http://jsbin.com/vapijovava/edit?html,output
### Steps to reproduce
- Scroll down so the edge of the top element is visible
- Click the middle element
- Observe that you are returned to the top of the top element (scroll position)

**Comment by blasten** [comment]
That is because iron-pages fires the `iron-resize` event. You could add an event listener and call `stopImmediatePropagation` on it although that is a hack.
http://jsbin.com/nixino/edit?html,output

**Comment by 43081j** [comment]
For anyone who has a similar issue, I actually ended up listening on `iron-request-resize-notifications` and calling `stopPropagation()` there.

I think/hope this means descendants can still rely on iron-pages firing `iron-resize`, but parents won't know about it. So we're effectively stopping the event reaching `iron-list` (parent) but not stopping it from notifying children.

**Comment by keanulee** [comment]
This should be fixed by #346
