### ISSUE TITLE
iOS Safari resize workaround prevents proper resizing in native webviews and cordova applications

### ISSUE THREAD

**Issue by kristfal** [PolymerElements/iron-list#324]
### Description

`iron-list`'s [_resizeHandler](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1485) contains a workaround for iOS address bar height changes. This workaround prevents resize events from working when using `iron-list` in an iOS webview without a dynamic toolbar (such as a native app webview or a cordova webview). 
### Expected outcome

Calling `document.querySelector('iron-list').fire('iron-resize');` should resize the `iron-list` in a native iOS webview or cordova webview.
### Actual outcome

The list is not resized as the `_resizeHandler` iOS workaround prevents the event from triggering updatedBoundaries.
### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
- [X] Safari mobile webview / cordova webview

**Comment by kristfal** [comment]
Update: 

iOS10 have introduced changes (bugs) to the way dynamic divs scale. In order to update the iron-list scrolling context, the list/content of the list needs to set `display: none` followed by an async `display: block`.

Removing the `_resizeHandler` workaround for iOS address bar and calling this whenever the list resizes or content length changes:

```js
  this.$$('#list').style.display = 'none';
  this.async(function(){
    this.$$('#list').style.display = 'block';
    this.$$('#list').fire('iron-resize');
  });
```

Resolves the issues for iOS10 and iOS webview.

**Comment by blasten** [comment]
@kristfal this issue sounds a lot like what this PR was trying to fix: https://github.com/PolymerElements/iron-list/pull/320 would you mind trying the master branch?

**Comment by kristfal** [comment]
@blasten Sorry for the slow reply. #320 resolves this issue. In addition, the scrolling context issue of iOS10 also seems to be resolved. Consider this issue closed.
