### ISSUE TITLE
<Grid layout> style broken on load on small screen

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/iron-list#333]
### Description

When opening the "Grid layout" demo in a **small window** (i.e. grid element width = 100%), there is a scroll bar on the x-axis.
When resizing the window, styles are re-computed properly and the scrollbar disappears.

How do we insure styles are properly loaded/applied on load?
### Expected outcome

There should never be a scrollbar on the x-axis.
### Actual outcome

On load on small-screen, there is a scrollbar on the x-axis.
### Live Demo

https://elements.polymer-project.org/bower_components/iron-list/demo/grid.html
### Steps to reproduce
1. Resize the web browser as small as it can be.
2. Go to https://elements.polymer-project.org/bower_components/iron-list/demo/grid.html
3. There is a scrollbar on the x-axis.
### Browsers Affected
- [x] Chrome
- [x] Firefox

**Comment by blasten** [comment]
@NicolasRannou I only see the horizontal scrollbar if I make the window's width really small. e.g. 95px and that is because the text overflows. `overflow:hidden` on the grid items should fix it. Is that what you are seeing?

**Comment by NicolasRannou** [comment]
@blasten no I think it is different, see the enclosed GIF.

Loading the page on a small window create the horizontal scroll bar. Resizing the window then back to the very small window size makes the scroll bar disappears.

It seems that when resizing the window, some styles are re-calculed and fix things somehow.


![iron-list](https://cloud.githubusercontent.com/assets/214063/19551966/bc6d0e4e-96a5-11e6-9a9d-6e797b25c734.gif)

**Comment by blasten** [comment]
This should be fixed by now. Please reopen otherwise.
