### ISSUE TITLE
Physical items miss binding updates.

### ISSUE THREAD

**Issue by sparlampe** [PolymerElements/iron-list#340]
### Description

We are observing several defects in iron-data-table that we eventually tracked down to what we think is a defect in iron-list. The problem happens, in our view , because in some situations a physical item is taken out of the physicalItems array in 
https://github.com/PolymerElements/iron-list/blob/64129116c8b45f1a8db9ba4bab4257b5ffd5c900/iron-list.html#L1757-L1759

Then parent properties are forwarded to the physical items in
https://github.com/PolymerElements/iron-list/blob/64129116c8b45f1a8db9ba4bab4257b5ffd5c900/iron-list.html#L1067-L1086

And evenutally an item that has missed a binding update is returned in to the pool at
https://github.com/PolymerElements/iron-list/blob/64129116c8b45f1a8db9ba4bab4257b5ffd5c900/iron-list.html#L1780
### Expected outcome

All the properties are propagated correclty for out of scope bindings.
### Actual outcome

Some physical items miss binding updates.
### Steps to reproduce

It's not easy to reproduce in an isolated setup. In our application it happens if we select one item
and make it invisible using scrolling.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by danbeam** [comment]
@blasten prettttty sure this is the same as https://github.com/PolymerElements/iron-list/issues/338

**Comment by danbeam** [comment]
@sparlampe can you still reproduce this in 1.3.12?

**Comment by blasten** [comment]
@danbeam Nope. That's correct. This is a bug:  

Repro: 
1. Template:
```html
<iron-list>
  <template>
     <div tabindex$="[[tabIndex]]">[[parentProp]]</div>
  </template>
</iron-list>
```
2. Focus the first physical item.
3. Scroll down until that physical item is taken out of the pool.
4. Change `parentProp` value.
5. Scroll back to the top.

Thanks @sparlampe

**Comment by dam0vm3nt** [comment]
I'm having serveral issue with `iron-data-table` that are probably related to this bug too.

Mine is a simple table with a `paper-input` inside the template. Only the first element gets its bindings. The other are rendered but not bound to any model.

In any case here is a jsbin. The first click on `add one` works. The subsequent fails:

https://jsbin.com/xigulepine/1/edit?html,output
