### ISSUE TITLE
Keyboard navigation in single-selection list only moves focus.

### ISSUE THREAD

**Issue by jmbldwn** [PolymerElements/iron-list#348]
### Description
For a single-selection list, it's sometimes desirable to have the next item in the list automatically selected on a down-arrow (also previous on up-arrow) instead of just moving the focus.

Is there a way to auto-select the focused item on keyboard navigation?

### Expected outcome
Down-arrow moves the selection to the next item as if the next item was clicked.   Up-arrow moves the selection to the previous item.

### Actual outcome
Arrows only move focus, requiring <enter> to change selection.  This sucks if you are browsing through a list and have popovers viewing the selection.

### Steps to reproduce
Use iron-list in single-selection mode.

### Browsers Affected

- [x] Chrome
- [X] Firefox
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

**Comment by blasten** [comment]
You can add a `keydown` event handler and depending on the pressed key, move the selection to the previous or next item of the currently selected item.
