### ISSUE TITLE
create custom indexes

### ISSUE THREAD

**Issue by Negashev** [PolymerElements/iron-list#349]
### Description

I have a problem with `iron-list`. whether it is possible to create custom indexes? such as the unique values of the elements?
I use socket.io client, with python backend (flask-socketio)

### Expected outcome

I send `unique id` to socket.io server and send `broadcast emit` for all client, that this  `unique id` was removed

### Actual outcome

I can send `e.model.index` but i think it not correct  index, for other clients

### Live Demo

```
<paper-card heading="Users">
    <div class="card-content">
        <iron-list id="list" items="[[items]]">
            <template>
                <paper-icon-item tabindex$="[[item.mail]]">
                    <iron-image style="width:40px; height:40px;" sizing="contain" preload fade
                                src="{{_url(item.img)}}" item-icon></iron-image>
                    <paper-item-body>
                        [[item.mail]]
                    </paper-item-body>
                    <paper-icon-button icon="close" alt="remove this!" on-tap="_delItem"></paper-icon-button>
                </paper-icon-item>
            </template>
        </iron-list>
    </div>
</paper-card>
```
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
This feature seems out of the concern of iron-list. Is there any problem with creating a custom id by youself? e.g. putting in the item instance.

**Comment by blasten** [comment]
Please reopen if this is still an issue.
