### ISSUE TITLE
Iron-list failing when containing iron collapse

### ISSUE THREAD

**Issue by jordanfinners** [PolymerElements/iron-list#352]
### Description
Having an issue with iron list, when i add an iron collapse inside it, the iron-list ceases working.

### Expected outcome
Iron list not to fail when including an iron-collapse inside it. 
And for iron list to resize when using an iron collapse.

### Actual outcome
Iron list doesn't list items when including an iron-collapse inside it.

### Live Demo
http://jsbin.com/danoqebiki/edit?html,output

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
I'm not sure if the jsbin is complete, but the only issue I found is that it's missing the margin reset in body. http://jsbin.com/jexupes/edit?html,output
