### ISSUE TITLE
Working with a Light DOM/Templatizer throws Illegal Invocation

### ISSUE THREAD

**Issue by nicholaswmin** [PolymerElements/iron-list#356]
### Description

Attempt to templatize an `<iron-list>` so it works with Light DOM, in the same way a `dom-repeat` can be templatized

### Expected outcome

`<iron-list>` allows using the `Templatizer` in the same fashion as dom-repeat does.

### Actual outcome

Throws an 

> Illegal Invocation

error

### Live Demo

https://jsfiddle.net/apofjvzq/2/

**Comment by arthurevans** [comment]
@blasten @nicholaswmin is trying to assign a template to the `iron-list` programmatically. Seems like that would be a new features for `iron-list`. Not sure whether there's just a little bit of magic missing here, or whether it'd require big changes.

**Comment by blasten** [comment]
@arthurevans @nicholaswmin yep this is a limitation in v1. I'm working toward fixing this issue in v2 since the new templatizer allows for template distribution. [e.g.](https://github.com/blasten/dom-list/blob/master/template-distribuition.html#L52-L69)  That said, there are a few things I can try doing in v1 to fix this issue as well!

**Comment by nicholaswmin** [comment]
@blasten 

>  That said, there are a few things I can try doing in v1 to fix this issue as well!

Sounds awesome. FYI I don't mind doing a quick and dirty hack for now if as a stop-gap, if it means no work from your end.

**Comment by blasten** [comment]
someone sent a PR a few months ago: https://github.com/PolymerElements/iron-list/pull/314

**Comment by nicholaswmin** [comment]
You think I could cold download `iron-list.html` from the PR and use that instead?

**Comment by blasten** [comment]
You definitely can, feel free to test it out.

**Comment by nicholaswmin** [comment]
Will do - It won't be merged in any case though, right?

**Comment by blasten** [comment]
I need to test parent properties and styling the light DOM.

**Comment by nicholaswmin** [comment]
@blasten Here's what I'm doing to "rescope" the Light DOM so see the parent methods/props

```
<dom-module id="block-list">
  <template>
    <iron-list id="repeater" items="{{data}}">
      <content></content>
    </iron-list>
  </template>

  <script>
    Polymer({
      is: "block-list",

      ready: function() {
        this.$.repeater.dataHost = this.dataHost;
      }
    });
  </script>
</dom-module>
```

Not sure if that's a no-no but it works. Haven't tested styling yet.

**Comment by nicholaswmin** [comment]
Styling the light DOM using the `::content` selector works as well on my end.

```
<block-list data="[[data]]" >
  <template>
    <div class="list-item">[[item]]</div>
  </template>
</block-list>
```

and in `block-list.html` styles which implements the `<iron-list>`:

```
::content.list-item {
  background: #333;
}
```

styles the `list-item` just fine.

**Comment by arthurevans** [comment]
FWIW, I believe the change in #314 could be simplified to a one-liner. Simply change `Polymer.dom(this).querySelector()` on L1026 to `this.queryEffectiveChildren()`:

     this._userTemplate = this.queryEffectiveChildren('template');
 
I tried adding computed bindings and an `on-tap` event handler and these work as I'd expect.

Style scoping is wrong in shady DOM. As @nicholaswmin said, `::content` rules match the template instances here, which is incorrect. The instances are inserted as children of the `iron-list`, _siblings_ to the `<content>` element. In native shadow DOM, they're styled correctly (that is, as normal shadow children of the parent (`block-list` in the example above). You could get around this with `scopeSubtree` but it's not clear to me why this is necessary.

I did _not_ manipulate `dataHost`. It's not clear to me that that's necessary (but maybe I'm missing something).

**Comment by nicholaswmin** [comment]
@arthurevans Are the computed bindings in the parent element that contains the `block-list`, which in turn contains the `iron-list` itself?

Without manipulating `dataHost` I can't use methods of the parent element. 

For clarity, the parent element in my [JSFiddle][1] would be the `<user-list>`.

[1]: https://jsfiddle.net/apofjvzq/2/

**Comment by arthurevans** [comment]
No, using content I was doing something like:

    <content-test>
      <template> ... template for iron-list </template>
    </content-test>

`content-test`'s shadow root:

     <iron-list id="list" items="{{data}}" as="item">
        <content></content>
      </iron-list>

This is what the patch @blasten referenced is trying to allow, and (modulo shady DOM styling problems) I _think_ it works. 

Having the bindings jump shadow roots like you're doing seems contrary to the intention of web components. 

If there's a specific set of methods you want to delegate, you could pass them in to the `block-list`/`editable-list` as properties. But having a child call arbitrary methods on its parent seems iffy to me.

**Comment by nicholaswmin** [comment]
Thanks,

> But having a child call arbitrary methods on its parent seems iffy to me.

But `<iron-list>` already does this. The light DOM of `<iron-list>` can bind to methods of the element it's contained in. If I set the `<iron-list>`  Light DOM to use a further Light DOM the same rules should apply.

For example, this works as it is:

```
<dom-module id="user-list">
  <template>
    <iron-list id="repeater" items="[[data]]">
      <template>
        <div>
          <template is="dom-if" if="{{!authorized(item)}}">
            Is authorized
          </template>
          <template is="dom-if" if="{{!authorized(item)}}">
            Not authorized
          </template>
        </div>
      </template>
    </iron-list>
  </template>

  <script>
    HTMLImports.whenReady(function() {
      "use strict";

      Polymer({
        is: "user-list",

        authorized: function(item) {
          if (item.authorized) return true;
          else return false;
        }
      });
    });
  </script>
</dom-module>

```

Maybe the confusion is the word `call`. I meant `bind` via the Light DOM

**Comment by nicholaswmin** [comment]
Here's a more clear example of what I'm trying to achieve.

<dom-module id="user-list">
  <template>
    <block-list data="[[data]]">
      <template>
        <div>
         
          <template is="dom-if" if="{{!authorized(item)}}">
            Is authorized
          </template>
        </div>
      </template>
    </block-list>
  </template>

  <script>
    HTMLImports.whenReady(function() {
      "use strict";

      Polymer({
        is: "user-list",

        authorized: function(item) {
          if (item.authorized) return true;
          else return false;
        }
      });
    });
  </script>
</dom-module>


<dom-module id="block-list">
  <template>
    <iron-list id="repeater" items="[[data]]">
    <content></content>
    </iron-list>
  </template>

  <script>
    HTMLImports.whenReady(function() {
      "use strict";

      Polymer({
        is: "block-list"
      });
    });
  </script>
</dom-module>

**Comment by arthurevans** [comment]
Yeah, you're right; I thought about that after I posted the last comment but I was away from the computer. I wasn't thinking about an `iron-list` type use case.

So the slight difference that makes `iron-list` (and `dom-repeat`) feel different to me is that they both stamp their template instances into light DOM, where you would expect bindings, etc., to refer to the host element, not `iron-list` itself. But because of the nature of the data system, they still need to manipulate the `dataHost` chain as you're doing. There should probably be a better-lit path for elements like this.

**Comment by arthurevans** [comment]
Adding @kevinpschaaf to the discussion because this is deep in his territory.

**Comment by femiadeyemi** [comment]
@nicholaswmin have you been able to find a temporary solution?

**Comment by nicholaswmin** [comment]
Yep - Just do the change in `<iron-list>` as described by @arthurevans [above[1].

Then use the `dataHost` rescoping as I do [above][2].

Keep in mind that the shady DOM styling issue hasn't been solved yet. Also you won't be able to update via `bower` from the official `<iron-list>` anymore until the styling/`dataHost` issues are solved and the change suggested properly merged.



[1]:https://github.com/PolymerElements/iron-list/issues/356#issuecomment-262121737
[2]:https://github.com/PolymerElements/iron-list/issues/356#issuecomment-262066720

**Comment by femiadeyemi** [comment]
Thanks!

**Comment by nicholaswmin** [comment]
any updates to this?

**Comment by femiadeyemi** [comment]
@nicholaswmin your solution works! Thank you.

**Comment by blasten** [comment]
Fixed in https://github.com/PolymerElements/iron-list/releases/tag/v1.4.0
