### ISSUE TITLE
ScrollTop behave differently with iron-list

### ISSUE THREAD

**Issue by rajasimon** [PolymerElements/iron-list#357]
### Description
When using ScrollTop the iron-list not showing the last item added into the iron-list 

### Expected outcome
It should display the last item added into the iron-list 

### Actual outcome
But instead it showing last previous item.

### Live Demo
http://codepen.io/tony19/pen/JbWRmb?editors=1010

### Steps to reproduce

1. input element on-change="handleMessage"
2. iron-list 
3. Push message to the property array!

### Browsers Affected | checkd in

- [x] Chrome
- [x] Firefox
- [x] Safari

**Comment by tony19** [comment]
@rajasimon The bug isn't really in `iron-list` but rather in the linked Codepen in that it doesn't wait until the list is rendered before reading the list's `scrollHeight`. I've fixed it now.

**Comment by rajasimon** [comment]
@
