### ISSUE TITLE
Iron-list reports incorrect `lastVisibleIndex` when list has padding.

### ISSUE THREAD

**Issue by andreasanheuser** [PolymerElements/iron-list#359]
### Live Demo
Reproducible on demo page by adding more padding-top: http://jsbin.com/lisajotoga/3/edit?html,output

### Steps to reproduce
Add more padding-top to list (to simulate e.g. content above list). Inspect iron-list's `lastVisibleIndex`. The index is off by padding-top/item height.

See also [`get lastVisibleIndex()`](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L714). `this._scrollerPaddingTop` is not taken into account when computing this index.

**Comment by blasten** [comment]
Also #366 is addressing this issue.
