### ISSUE TITLE
Array set to size NaN

### ISSUE THREAD

**Issue by Brian-K-Smith** [PolymerElements/iron-list#36]
On Chromium I am seeing errors that arise in _increasePoolIfNeeded when this._physicalSize and this._optPhysicalSize are equal to each other. var missingItems gets set to NaN (from 0 * 1.2 / this._physicalAverage) and the NaN cascades on through to this._createPool. Doing:
```if (this._physicalSize >= this._optPhysicalSize)```
seems to fix the problem in Chrome, but it caused test failures in all the other browsers. Unfortunately I don't have a good test setup with all the browsers, etc. yet so this may be as far I get on this one.

**Comment by danmane** [comment]
+1 I am seeing this issue as well. 
Tracing back a little further; 
```
      for (var i = 0; i < this._physicalCount; i++) {
        this._physicalSizes[i] = this._physicalItems[i].offsetHeight;
        total += this._physicalSizes[i];
        this._physicalAverageCount += this._physicalSizes[i] ? 1 : 0;
      }
```
Offset height is 0 for every item.

**Comment by Brian-K-Smith** [comment]
It seems to be happening at least in part because I'm creating the element with a default zero-length array of contents and then loading the items from my RESTful API later if the user navigates to the route where the element lives. Maybe I should be waiting to create the element until I actually want to display it and have already retrieved the items to stick in it, but I haven't figured out how to do that yet. Either way, I don't think a zero-length array of items should cause an uncaught exception, just an empty list.

**Comment by notthetup** [comment]
Yup. I'm seeing this too. Same use case. I have the `iron-list` created as a part of an element, but only populated later on based on user interaction.

**Comment by blasten** [comment]
I have confirmed this issue. It only happens when the list is attached to the DOM but not fully rendered (e.g. the list or some ancestor has display: none).  It seems related to https://github.com/PolymerElements/iron-list/issues/39 as well.

**Comment by tasosno1** [comment]
@notthetup  -- where did you add this

<code>if (!missingItems){
  missingItems = 0;
}</code>

**Comment by notthetup** [comment]
@tasosno1 It was right after 

```
var missingItems = Math.round((this._optPhysicalSize - this._physicalSize) * 1.2 / this._physicalAverage);
```

**Comment by tasosno1** [comment]
ok thanks

**Comment by blasten** [comment]
This issue has been fixed after https://github.com/PolymerElements/iron-list/commit/dbbcfb97634e203ded037e37ba05e7534eb32a28
