### ISSUE TITLE
Iron-list broken when there's content above it in its designated scroll target

### ISSUE THREAD

**Issue by andreasanheuser** [PolymerElements/iron-list#360]
### Live Demo
https://jsfiddle.net/g9tek022/3/
Scroll up and down and notice how first and last visible index don't reflect what is actually rendered. This leads to items disappearing before they actually leave the viewport.

### Expected outcome
Iron list should calculate the list's offset relative to its scroll target and take that offset into account when laying out items. The offset can be computed as `list.getBoundingClientRect().top + scrollTarget.scrollTop - scrollTarget.getBoundingClientRect().top` and should be relatively easy to maintain in addition to `this._scrollerPaddingTop`.

The current workaround would be to manually compute that offset and set a `padding-top` (+reverse margin-top) on the list since it respects padding and ensure all content above the list has a higher z-index than the list itself. This is pretty ugly though :-(

**Comment by blasten** [comment]
Merging this issue #366
