### ISSUE TITLE
Duplicate Numbers Cause Incorrect Selection Behavior

### ISSUE THREAD

**Issue by rajsite** [PolymerElements/iron-list#367]
### Description
When using an array of numbers as the items for iron-list, having duplicate values in the array causes the selection behavior to select the wrong item.

### Expected outcome

The item at the index clicked is selected

### Actual outcome

A different item with the same value, but at an index that was not clicked is selected

### Live Demo
http://jsbin.com/jusenih/1/edit?html,output

### Steps to reproduce

1. Open the jsbin and select (ie click) Item 3
2) Notice that it is Item 7 that has selected changed to true

### Browsers Affected

- [x] Firefox
- [ ] Safari 9
- [x] Chrome
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10
^ Browsers reproducing the behavior
^  Firefox Nightly reproduces intermittently

**Comment by blasten** [comment]
Yep, this is known issue. Check https://github.com/Polymer/polymer/issues/1913 for more reference.  Is it possible for you to wrap the values in an object?

**Comment by rajsite** [comment]
Ah I had missed that, thanks @blasten. I had noticed the behavior when playing with the jsbins referenced in the [README](https://github.com/PolymerElements/iron-list/blob/e07f3b637c12126611cde76d1ade15ebf6330045/README.md) when evaluating iron-list (which all demonstrate using an array of numbers). 

I did not notice the same problem as my data set is an array of objects (although it did make me hesitant to use the iron-list element). I imagine the common use case in an array of objects instead of primitives. It might be useful to have the examples demonstrate that use case and / or have this limitation using arrays of primitives documented.

**Comment by rajsite** [comment]
The original question of this issue was definitely a duplicate of Polymer/polymer#1913

The second question of whether the jsbin examples should not demonstrate arrays of numbers seems moot as the jsbin examples are non-functional: https://github.com/PolymerElements/iron-list/issues/465

I'll just close this issue and a separate issue could be opened for the jsbin iron-list examples using numerics.
