### ISSUE TITLE
Support paged data queries

### ISSUE THREAD

**Issue by nalbion** [PolymerElements/iron-list#37]
For truly infinite lists, or even very large lists, it would be preferable to be able to query the server for a limited number of records.  If a browser can display 5 records at a time, the application would probably still want to query a larger dataset - say 10 (displayable records + cached buffer).  

- When the user scrolls one or two records the iron-list component would just update the display (if required).  
- When the user scrolls close enough to the buffer, the component should fire an event which can be used to send an ajax request for the next page (might need to support scrolling up as well as down).  
- Applications might also want to be able to remove the pages of data which are well beyond the current scroll position.

**Comment by blasten** [comment]
@nalbion `iron-list` supports all these cases.  Have you found any issue or are you looking for a demo?

**Comment by birkir** [comment]
Checkout this: https://github.com/Decateron/iron-scroll-threshold/

Attach the `iron-list` to your `scrollTarget` and set the `lowerThreshold` to something you want. Then do a request to your server and append the data to the iron-list using the notify-path's push. (`this.push('items', loadedItems);`

**Comment by nalbion** [comment]
Awesome - would be good if a paging demo could be provided or linked to from the README

**Comment by birkir** [comment]
It's not an official Polymer component, it's a port from the 0.5. But I can give you an example on how to use it.
```html
<iron-scroll-threshold lower-threshold="500" on-lower-trigger="{{moreItems}}" id="threshold"></iron-scroll-threshold>
<iron-list items="{{items}}" id="list">
...
</iron-list>
```

Then the controller prototype could be something like this
```js
Polymer({

  is: 'root-node',

  properties: {
    page: Number,
    items: Array
  },

  ready: function () {
    this.$.threshold.scrollTarget = this.$.list;
  },

  moreItems: function () {

    var self = this,
        request = document.createElement('iron-request');

    // Request more items
    request.send({
      url: '/api/data?page=' + (this.page + 1)
    })
    .then(function (req) {

      // Loop through items and push them into the real array via path notifier
      req.response.forEach(function (item) {
        self.push('items', item);
      });

      // Clear the lower threshold to re-enable lower threshold firing the moreItems event
      self.$.threshold.clearLower(true);
    });
  }

});
```

**Comment by agozie** [comment]
You can simply do this:
```html
 <iron-list items="[[data]]" on-scroll="onScroll" id="list" as="item">
 </iron-list>
```
then:
```javascript
        onScroll: function(e) {
            if (e.target.scrollTop + e.target.offsetHeight >= e.target.scrollHeight - 500) {
                //this.getData()
                //then (this.push('data', loadedItems);
            }
        }
```

**Comment by blasten** [comment]
I think it will be nice to have an event for this.  e.g. `on-scroll-end`

**Comment by tasosno1** [comment]
@blasten @agozie  i think you guys should kick off a blog like https://jqmtricks.wordpress.com/ and add these Goodies in there for now until this stuff gets built in to iron-list

Ill try that code now

**Comment by tasosno1** [comment]
@agozie  -- hmm, strange  the <code>on-scroll="onScroll"</code> directly on the iron-list wasn't firing the <code>onScroll</code> for my app. Tried it on demo1 for iron-list and works ok.

So i had to create a custom scroll function and attach it to the <code>#mainContainer</code> and works as expected

Not sure why on-scroll event is not registering on the iron-list itself, probably in my instance its the main container is scrolling, but i'm 100% the iron-list works as expected

**Comment by tasosno1** [comment]
Why measure pixels onscroll,

iron list has a count of items and knows which current one is on top of the view 

<code>//set a done flag to make sure  items has finished rendering and iron-list has updated the total count of items otherwise if a user is scrolling quick it will push new items multiple times</code>  
<code>done="yes"</code>

inside  the scroll function

<code>//get the actually count of items and minus that by the first visible item i.e the top item on the screen you are seeing</code>
<code>var litop =  document.getElementById("mainlist")._virtualCount - document.getElementById("mainlist").firstVisibleIndex ;</code> 

<code>Set a number  for items left to view in the list 10 sound good on a 25 items per page view and push new items on the list</code>
<code>if (litop < 10 && done == "yes") { done="no"; push new items on the list.. once finished set  done="yes"}</code>

Tested, and works very good better than measuring pixels on the screen.

**Comment by birkir** [comment]
Why are you using strings as Boolean flags? And also you should use the already active observer to listen for changes in the virtual position property on the prototype, not another on-scroll listener.

**Comment by tasosno1** [comment]
@birkir How would you go about doing that?

**Comment by cdata** [comment]
Hey guys, is there something that we can take action on here? Documentation? Enhancement? If so, can we update the original issue to more clearly describe what is being asked for?

**Comment by blasten** [comment]
You can take a look at the demo https://github.com/PolymerElements/iron-list/blob/master/demo/scroll-threshold.html using the new iron-scroll-threshold https://github.com/PolymerElements/iron-scroll-threshold :)
