### ISSUE TITLE
iron-list won't render correctly when child has flex display

### ISSUE THREAD

**Issue by quangld** [PolymerElements/iron-list#370]
### Description
When updating items array in the iron-list. If the direct child inside the template of iron-list has display:flex style, iron-list won't render the list correctly

### Live Demo
https://jsbin.com/yudugap/edit?html,console,output

### Steps to reproduce
Click on "Empty List" Button: items in the iron-list with flex-child still presents while the iron-list without flex-child is empty as expected
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by quangld** [comment]
Work-around is to put that flex div inside another div: to make sure the flex div is not a direct child of the iron-list.

**Comment by blasten** [comment]
Yep. That is annoying. Another workaround is to set `display:flex` in a rule with the selector `.flex:not([hidden])`.

**Comment by peerke** [comment]
Thanks a lot @quangld for the workaround. I have been looking for a solution for days.
