### ISSUE TITLE
Iron-list doesn't update items during scrolling in PhoneGap app (iOS UIWebView)

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerElements/iron-list#38]
The iron-list becomes empty as the user scrolls above/below the rendered items. The new items are only shown once the scrolling stops.
This seems to be caused by UIWebView not executing JavaScript during scrolling. Setting "-webkit-overflow-scrolling:auto" makes the iron-list update the items immediately but results in a very poor overall scrolling experience.

**Comment by blasten** [comment]
@ronnyroeller iron-list uses `-webkit-overflow-scrolling: touch` in iOS devices. Unfortunately, that feature is not available for `UIWebView` because Apple hasn't updated their webkit version yet. Mobile Safari does run a webkit version that support this CSS feature though.
