### ISSUE TITLE
[2.0-preview] Some items are overlapped

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/iron-list#384]
### Description
I ported code.nasa.gov to use 2.0-preview.  One issue I am seeing is some of the items in are not position correctly so they overlap.

### Steps to reproduce

1. Checkout code.nasa.gov 2.0-preview branch: https://github.com/frankiefu/code-nasa-gov/tree/2.0-preview
2. Run the app
3. Scroll down the projects list and you will some items are not position correctly.

<img width="1029" alt="screen shot 2017-01-25 at 12 43 53 pm" src="https://cloud.githubusercontent.com/assets/116360/22308506/1e95a93a-e2fc-11e6-93d4-574d3486ed74.png">

### Browsers Affected

- [x] Chrome

**Comment by keanulee** [comment]
https://github.com/PolymerElements/iron-list/pull/386
