### ISSUE TITLE
easy way to reset the list

### ISSUE THREAD

**Issue by Stefdv** [PolymerElements/iron-list#396]
### Description
Iron-list 1.4.1
I have a dynamic iron-list. When one of the items has a changed property i splice/replace the whole item.
If the item is in the viewport it doesn't change. Only when i scroll the item out of the viewport and back the change is visible.
`list.fire('iron-resize') ` doesn't do anything.

### Expected outcome

When i replace an item in the Array the list should refresh ( if i have to force it that would be fine )

### Actual outcome

Items don't change unless i move them out of the viewport.
list.fire('iron-resize') does NOT refresh the list

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
To change the property of an item use the polymer data mutation API.  https://www.polymer-project.org/1.0/docs/devguide/model-data

**Comment by artemik** [comment]
Still that hassle in 2017 modern framework? What's the point in two-way data binding then at all?

**Comment by deto** [comment]
Yeah, I just ran into this issue today - this issue should not be closed.  Clearly the list isn't working as expected here - it is supposed to observe when entire elements change.

I have an iron-list with many items and an operation which makes many changes to them.  I want to just re-render the list.  If I use this pattern:  

```
var _my_array = this.my_array;
this.set('my_array', []);
this.set('my_array', _my_array);
```

The rows are not updated until I scroll.  This doesn't make any sense as the component should be completely re-rendering with the new array.  Clearly, there is some sort of caching/memory going on in the element?

**Comment by Stefdv** [comment]
Yup....fire('iron-resize') or notifyResize() doesn't work (anymore) .
It used to work but now i'm using iron-list#2.0-preview and it doesn't :(

**Comment by ernsheong** [comment]
This might be want you want: https://www.polymer-project.org/2.0/docs/devguide/model-data#notify-path

**Comment by deto** [comment]
No, @ernsheong , above I tried that as well as using `.set` on the array to which the iron-list binds and neither cause it to properly re-evaluate the elements.

**Comment by ernsheong** [comment]
I found an issue with iron-list at https://github.com/PolymerElements/iron-list/blob/9e9b938e32ca0f87beeb1078093dc8bf6498ac78/iron-list.html#L1096

After the call to `_debounceRender` nothing is calling Polymer.flush() in order to flush the debounce queue. I'll try to submit a PR tonight...

**Comment by ernsheong** [comment]
@deto https://www.polymer-project.org/2.0/docs/devguide/model-data#array-mutation `PolymerElement#splice method` seems to work instead of the `set` method.

**Comment by deto** [comment]
Interesting.   So a workaround would be to splice out all the old elements
and splice in all the new ones when changing the list?  I'll have to try
that out the next time I run into this .

**Comment by ernsheong** [comment]
Actually, false alarm. Changes using splices still suffer from https://github.com/PolymerElements/iron-list/issues/475. Easy workaround is to just call `Polymer.flush()` after mutation code.

**Comment by Stefdv** [comment]
Using latest iron-list....still not solved

**Comment by lequem** [comment]
+1

**Comment by Stefdv** [comment]
To change an item using splice still only works on first level keys `{name:'Polymer'}` but if you want the changes on deeper levels `{ name:'Polymer', profile:{ website:'''}}` you have to empty the whole object first.
```
this.splice('items',idx,1,{})
this.splice('items,idx,1,newItem)
```.
Although this works...it's a pain if you just happen to have that item opened ( like a dropdown in the field).
I try to use iron-list in a distributed system, but it sucks.
I use vaadin-grid now, but that's a whole other ballgame

**Comment by Nehaw149** [comment]
Anyone still facing this issue?

**Comment by dman777** [comment]
I seem to be hitting this issue....even when I override with dirty checking. I have checkboxes and when I reload the data it seems the checkboxes keep a state.

**Comment by alooosh** [comment]
Any solution  i am facing the same problem  in 19/6/2019
