### ISSUE TITLE
[2.0] Error on Keyboard selection

### ISSUE THREAD

**Issue by 200Puls** [PolymerElements/iron-list#398]
When using the keyboard navigation an error occurs when using the arrow down key to select the next item.

### Expected outcome
When pressing arrow down the next item should be selected.

### Actual outcome
An error occurs in code:
`e.detail.keyboardEvent.preventDefault()`

The  problem ist 'e' is the keyboard event and detail seems to be an index or a value and not an object structure with a wrapped event. So preventDefault cannot be called on undefined.

### Example Code
`<iron-list items="{{searchResult}}" as="result" selection-enabled selected-item="{{_selectedRow}}" >
     <template>
         <div on-click="navigate" tabindex$="[[tabIndex]]">
             <div class="pad">
                 <div>[[result.name]]</div>
              </div>
     </template>
 </iron-list>`

### Steps to reproduce

1. Put `iron-list` on the page
2. Bin to a model
3. Add a `tabindex$="[[tabIndex]]"` to enable keyboard selection:
4. Select first element
5. Push arrow down key

### Browsers Affected

- [x] Chrome

**Comment by blasten** [comment]
Fixed in https://github.com/PolymerElements/iron-list/pull/394/commits/2ee12366b62332dbbeb9fb285a55dfad03200227. Thanks for reporting!
