### ISSUE TITLE
[2.0-preview] selection demo throws when trying to delete an item

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/iron-list#404]
If you run the demo `selection.html` and try to delete a selected contact you will get an error.

### Expected outcome

The item is deleted.

### Actual outcome
```
Uncaught TypeError: Cannot read property 'item' of undefined
    at HTMLElement._unselect (selection.html:263)
    at HTMLElement.handler (template-stamp.html:429)
    at Object._fire (gestures.html:504)
    at Object.forward (gestures.html:799)
    at Object.click (gestures.html:780)
    at HTMLElement._handleNative (gestures.html:318)
```

### Steps to reproduce

1. Run `demo/selection.html`
2. Click on any contact in the `main list` to select it.
3. On the `Selected contacts list`, click on the item to remove the contact.

### Browsers Affected

- [x] Chrome

**Comment by blasten** [comment]
@keanulee the issue might be solved by adding `_parentModel: true` to the prototype.

**Comment by frankiefu** [comment]
👍  on a test for this case.

**Comment by keanulee** [comment]
@blasten Not sure what you mean - prototype of what?

I was able to fix this by replacing the `_unselect` tap handler in the selection demo with:

```javascript
_unselect: function(e) {
  var item = this.$.selectedItemsList.modelForElement(e.target).item;
  this.$.itemsList.deselectItem(item);
},
```

@frankiefu Not sure whether a test is appropriate if the fix is in the demo (unless `TapEvent.model` is [supposed to be something](https://github.com/PolymerElements/iron-list/blob/master/demo/selection.html#L264)?).

**Comment by blasten** [comment]
sorry to iron-list's prototype. Check @sorvell comment: https://github.com/Polymer/polymer/pull/4339#issuecomment-282871104

**Comment by blasten** [comment]
A test could check if `model` is properly decorated in the event object since that is part of the contract.

**Comment by frankiefu** [comment]
Fixed in https://github.com/PolymerElements/iron-list/pull/405
