### ISSUE TITLE
[2.0-preview] Using arrow keys to navigate causes the the item to be removed

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/iron-list#407]
Using arrow keys to focus the next item in the list causes the item to be removed.

### Expected outcome

Using arrow keys to focus the next item should work.

### Actual outcome

The item is removed.

<img width="1024" alt="screen shot 2017-03-03 at 5 26 18 pm" src="https://cloud.githubusercontent.com/assets/116360/23574726/a4c7430e-0036-11e7-92ea-9f2bc02cb6fe.png">

### Steps to reproduce

1. Run `demo/cards.html`
2. Scroll down the list.
3. Click on an item to select it.
4. Using `down` arrow key to navigate/focus the next item

### Browsers Affected

- [x] Chrome

**Comment by keanulee** [comment]
Hmm, can't seem to repro this with the latest `2.0-preview` with a fresh `polymer install`.
