### ISSUE TITLE
[2.0-preview] Random access causes the list to position incorrectly

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/iron-list#408]
### Steps to reproduce

1. Run `demo/cards.html`
2. Drag on the scroll bar to scroll up and down (like 5/6 times) very quickly
3. Now drag the scroll bar on the way back to the top

### Expected outcome

The list displays correctly

### Actual outcome

The top position of the list is incorrect.

<img width="1026" alt="screen shot 2017-03-03 at 6 10 43 pm" src="https://cloud.githubusercontent.com/assets/116360/23575105/bf5c952e-003c-11e7-9739-784652076b14.png">

### Browsers Affected

- [x] Chrome

**Comment by keanulee** [comment]
May be related to #400

**Comment by keanulee** [comment]
Should be fixed by https://github.com/PolymerElements/iron-list/commit/587728f6215e325d88786558320a33646dd000f0
