### ISSUE TITLE
Scrolling bug introduced in 785861b

### ISSUE THREAD

**Issue by pkaske** [PolymerElements/iron-list#409]
### Description
When scrolling rapidly down and up the top of the list can't be reach anymore.
I found that https://github.com/PolymerElements/iron-list/commit/785861b73747819f1a46633b3bbbd3f3d603f4b6#diff-b97995700c5da5fa638d0324b5f3f861L1394 seems to be the issue (see gif down below).

![iron-list](https://cloud.githubusercontent.com/assets/11567985/23607357/f32260da-0264-11e7-81cd-08cf4a116e28.gif)

**Comment by blasten** [comment]
Thanks for the report and the PR working on fixing it.

**Comment by keanulee** [comment]
Duplicate of #408 , but leaving this open to track the fix on `master` as well.
