### ISSUE TITLE
First tap interactions not registered on some list items

### ISSUE THREAD

**Issue by shc023** [PolymerElements/iron-list#411]
### Description
Noticed that on a long list, some list items won't recognize click events if its the first click onto the list.

### Expected outcome
Click events recognized correctly on all list elements.

### Actual outcome
Clicks events are not registered on list elements when first being clicked.

### Live Demo
https://jsfiddle.net/cyenptb4/7/

### Steps to reproduce
See live demo.

**Comment by danbeam** [comment]
@blasten

**Comment by blasten** [comment]
@danbeam  The issue seems to be fixed if you place the `paper-checkbox` inside a `div` container.

**Comment by shc023** [comment]
@blasten Actually, adding a `div` around the `paper-checkbox` only shifts the problem to other items. After adding `div`, I then see the same issue on the first "27". I believe the issue moved onto another element because after adding the `div`, there's code inside iron-list's code that made it load items in batches of 26 items, instead 27 items before adding the `div`.

Please re-open the issue, thanks!
