### ISSUE TITLE
Poor scrolling performance on multiple iron lists

### ISSUE THREAD

**Issue by tasosno1** [PolymerElements/iron-list#42]
Hi,

If you have an iron-list on the main page and another on a dialog, once you open the dialog the scrolling performance is poor and you get flickers.

However, sliding up the main list or setting it to <code>display:none;</code> fixes the scrolling performance on the dialog. 

would anyone know the reason why that happens. in regards to the poor scrolling performance?

people would want an iron-list on a dialog for Bookmarks, search list etc but as it stands the users would get a bad experience with scrolling flickers

Assuming its because the dialog has <code>position:fixed;</code> i'm wondering why when you set the main list to <code>display:none;</code> fixes the scrolling performance. 

I thought maybe adding  <code>backface-visibility: hidden;</code> to the dialog and/or iron-list may help, but it didn't.

Resolution in issue #39 is a workaround  for now.

Thanks

==========
This issue appears when using the following specs

Device - LG400 Tablet --- Os - Android Lollipop --- Android App with Crosswalk Embedding API

**Comment by blasten** [comment]
@tasosno1 did you use a paper-dialog?  Can you send a snippet to see the overall structure of your app?  Btw, this should be helpful now: https://github.com/PolymerElements/iron-list#resizing

**Comment by tasosno1** [comment]
@blasten

Hi thanks for your reply

Yes this is helpful <code>document.querySelector('iron-list').fire('resize');</code> one drawback is that if you scrolled down a bit <code>.fire('resize');</code> takes you back to the top. 

i put in a solution in #39 that records where you are on the list and takes you back to item(index). 
Thank god those 2 functions are there in the iron-list html, someone at the Polymer team thought ahead :))

Anyway i have now idea why when you i open a dialog the iron-list feels like 5 fps when scrolling and when i set the main list on main page to <code>display: "none"</code> i get 60 fps when scrolling. Spooky. I cant trace the issue, i tried all the css tricks but ill keep looking. 

<strong>App Structure</strong>

<code>
<body unresolved class="fullbleed">
<my-request></my-request>
<dom-module id="my-request">
<style>
the styles
</style>
<template>
<iron-ajax>
the ajax
</iron-ajax>
<paper-drawer-panel>
<paper-header-panel drawer>
App name
<paper-toolbar>
Panel items
</paper-header-panel>
<paper-header-panel  main>
<paper-toolbar>
The Header
</paper-toolbar>

<iron-list>
<template>
<div>
Item Structure
</div>
</template>
</iron-list>

<paper-dialog id="bookmarks" entry-animation="slide-from-right-animation" exit-animation="slide-right-animation">
<h2><br>Bookmarks</h2>
<iron-list id="bookmarks-list">

Populated by Jquery from local storage 
 
</iron-list>

<paper-fab id='closeBookmarks' mini icon='close'></paper-fab>
</paper-dialog>

one more dialog, but this one is just <ul> <li> </li> ...... </ul>

</paper-header-panel>
</paper-drawer-panel>

</template>
</dom-module>

**Comment by tasosno1** [comment]
@blasten 

Because i'm using Crosswalk a few min's ago i thought to test my App on Google Chrome Browser on my tablet. The poor scrolling performance is hardly noticeable, from like 60 fps its 50 and i don't see any flickers. Feels smooth anyhow.

I think it might be down to Crosswalk not performing well in such instances. ill check for the latest  Crosswalk and see about upgrading.

Ill close this issue for now as i think its browser specific

**Comment by tasosno1** [comment]
Looks like browser specific (Crosswalk) issue, as on Google Chrome for tablet the scrolling performance is good and acceptable
