### ISSUE TITLE
2.0.0 release breaks under polymer.build

### ISSUE THREAD

**Issue by scrubskip** [PolymerElements/iron-list#443]
### Description
2.0.0 release breaks under polymer build

### Expected outcome

Should be able to bower install PolymerElements/ironlist --save and then run polymer build

### Actual outcome

info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file /usr/local/google/home/justinkoh/src/eclipse2017/static-nginx/app/static/bower_components/iron-list/iron-list.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
     filename: 0,
     line: 1567,
     col: 20,
     pos: 51092,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)\n    at token_error (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)\n    at expect_token (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:9)\n    at expect (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2116:36)\n    at eval (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2689:13)\n    at eval (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)\n    at expr_atom (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2619:35)\n    at maybe_unary (eval at <anonymous> (/usr/local/google/home/justinkoh/.nvm/versions/node/v7.0.0/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)' } }

### Steps to reproduce

1. bower install --save PolymerElements/iron-list
2. polymer build

This works if you hardcode PolymerElements/iron-list#1.4.6

### Browsers Affected
N/A

**Comment by keanulee** [comment]
Unable to reproduce with polymer-cli#1.0.0 - what version are you using (`polymer --version`), and do you see any syntax errors in the generated `iron-list.html_script_0.js`?
