### ISSUE TITLE
Filtering and selecting preserves actions taken on unrelated elements

### ISSUE THREAD

**Issue by evanbechtol** [PolymerElements/iron-list#444]
### Description & Actual Outcome
The `iron-list` element is incorrectly binding actions across elements, on what appear to be indices. When filtering the list of elements in an `iron-list`, the actions perform on the filtered list are bound to the indices. When the filter is removed, the actions performed are then incorrectly reflected on the unfiltered list indices.

### Expected outcome
When performing actions on a filtered list, the unfiltered list should not be affected. The actions should be bound to the specific element that they were performed on initially.

### Live Demo
[Live Demo (Plunkr)](https://plnkr.co/edit/v2a6C3fYBAIwWYgwTvwg?p=catalogue)

### Steps to reproduce
0. Initial State
![selectall0](https://cloud.githubusercontent.com/assets/10092035/26204063/3d3bdf4e-3ba3-11e7-9635-f613bde22a08.png)

1. Search for a project in the list
![selectall1](https://cloud.githubusercontent.com/assets/10092035/26203931/b445a09e-3ba2-11e7-9e57-5a1329f398b0.png)

2. In that project, check the select all checkbox
![selectall2](https://cloud.githubusercontent.com/assets/10092035/26203937/b7f85e02-3ba2-11e7-8eff-68398758bce3.png)

3. Clear the search input, and expand the first project in the list, notice that the items appear checked now, even though their data has not been retrieved
![selectall3](https://cloud.githubusercontent.com/assets/10092035/26203941/bb55a334-3ba2-11e7-9313-014a09b1717e.png)

4. Uncheck the select all checkbox that is incorrectly checked
![selectall4](https://cloud.githubusercontent.com/assets/10092035/26203970/d74940e6-3ba2-11e7-8ad7-dc39f107808e.png)

5. Go back to the project that was originally filtered on, notice that the checkboxes are now unchecked as well
![selectall5](https://cloud.githubusercontent.com/assets/10092035/26203993/e9b03424-3ba2-11e7-8d84-c5a56345e98f.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
In your example, the `checked` state of a project is correctly bound to the `filteredProjectData` array, but when you toggle "select all", `filteredProjectData` is reset, so you lose the checked state.

**Comment by Parasin** [comment]
This is true, but shouldn't​ iron-list then also lose the checked state?

**Comment by keanulee** [comment]
The first `<workplan-filter-list>` is also being recycled, and when you clear the search filter the first `<workplan-filter-list>` will have its `selectAllChecked` property set, so that's why it's checked. Haven't tried using nested `<iron-list>`s before - interesting use case, but not 100% sure it'll work as expected.

**Comment by Parasin** [comment]
So is there a way to force the iron-list to provide the behavior that I am
stating above? Am I doing something incorrectly, or is this in fact an
issue?

**Comment by keanulee** [comment]
I would try making `project.selectAllChecked` a property on the project and bind to that.
