### ISSUE TITLE
data bound in item templates do not render w/o interaction on 2.0-preview

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/iron-list#445]
### Description

Working with 2.0-preview branch, my iron-list templates all render the static content but none of the bound data... This can be "fixed" one of several ways it seems (not code fix, but rendering fixed)

1) if I grab one of the templated items and modify one of the values, everything seems to render like magic then
2) scrolling the list down will render the 2nd set/page of items and everything below them... scrolling back up will render the 1st set/page as well *EXCEPT* for the 1st item... The only way to get it to render is to modify that specific set of properties...

For comparison, I tested with dom-repeat as well... it worked no problem.
### Expected outcome
List items render bound data properly when data is supplied

### Actual outcome
List is not rendering any bound data initially

### Live Demo

(I will get this setup tomorrow/today (almost 4am right now)

### Steps to reproduce
(will edit this as well once the demo is available)

### Browsers Affected

- [x] Chrome (only tested here so far)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
This seems like related to https://github.com/Polymer/polymer/issues/4601

**Comment by ktiedt** [comment]
Just checked the patch for that issue and it is the same problem, thanks @frankiefu for matching those up, never would have thought to look at those issues! Also thanks to @sorvell for the fix!

**Comment by RoXuS** [comment]
👍

**Comment by ktiedt** [comment]
Do we know when this will land in a release? (I suppose worst case I can make an exception and pull the branch for this fix or fork and apply it to a local repo but hoping to avoid more problems ;) )

**Comment by frankiefu** [comment]
We are planning to do a Polymer release this week. Thanks for bearing with us!

**Comment by Bodhiz** [comment]
I'm still experimenting this issue with Polymer 2.X

**Comment by keanulee** [comment]
The original issue has been fixed since Polymer 2.0.1 (see https://raw-dot-custom-elements.appspot.com/PolymerElements/iron-list/v2.0.8/iron-list/demo/basic.html for demo). If you see another issue please make a new issue with appropriate details.
