### ISSUE TITLE
iron-list steals focus when the list property changes

### ISSUE THREAD

**Issue by wilron** [PolymerElements/iron-list#449]
### Description
The `iron-list` element causes focus to be stolen from other elements when its `items` property/attribute gets a new value.  I created a live example using a `paper-input` and an `iron-list` in order to demonstrate the issue.  This just appeared with the 2.0.1 release of `iron-list`.  It looks to me like the code currently on line 1725 of iron-list.html `document.activeElement && document.activeElement.blur && document.activeElement.blur();` is the culprit.  In my case, document.activeElement does not appear to be the current element with focus at the time this is called at least.

### Expected outcome
`iron-list` does not cause focus to be lost from other elements, such as `paper-input`, when updating the `items` property/attribute.

### Actual outcome
Updating `iron-list` `items` property/attribute causes input to be lost from other elements, such as `paper-input`, when updating the `items` property/attribute.

### Live Demo
[https://jsbin.com/wehoyaw/edit?html,output](https://jsbin.com/wehoyaw/edit?html,output)

### Steps to reproduce

See live demo, or hook up the value-change event of a paper-input to update the data for the `items` property of `iron-list`.

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ x] Edge
- [x ] IE 11
- [ ] IE 10

**Comment by Stefdv** [comment]
Same here...

**Comment by samiheikki** [comment]
+1 for fixing this

**Comment by manolo** [comment]
Blur should be only called if the focused element is actually inside the iron-list.

**Comment by ronnyroeller** [comment]
+1 for fixing this
