### ISSUE TITLE
_updateMetrics called prematurely, causes Exception:

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-list#46]
HTML below throws inside _increasePoolIfNeeded with:
`Uncaught RangeError: Invalid array length iron-list:559`
Reason is:
`this._physicalAverage` is 0
because:
`this._updateMetrics` got called before items measured have been attached to DOM, and offsetHeight of every physicalItem was 0 at time of measurement.
If I muck with the code, and make it not crash, items are displayed with proper height.
The stack before this._updateMetrics is
```attached -> _render -> _update -> updateMetrics```

To demonstrate the bug load:
```
<!doctype html>
<head>
<link rel="import" href="../iron-list/iron-list.html">
<link rel="import" href="../paper-scroll-header-panel/paper-scroll-header-panel.html">
<link rel="import" href="../paper-toolbar/paper-toolbar.html">
</head>
<body class="fullbleed">
  <paper-scroll-header-panel>
    <paper-toolbar>
      <div>Help</div>
      <div>Patients</div>
      <div>Search</div>
    </paper-toolbar>
    <section>
    <iron-list items='["a","b","c"]'>
      <template>
        <div>{{item}}</div>
      </template>
    </iron-list>
    </section>
  </paper-scroll-header-panel>
</body>
```

**Comment by blasten** [comment]
@atotic This bug has been fixed in v1.0.2 https://github.com/PolymerElements/iron-list/releases/tag/v1.0.2

**Comment by atotic** [comment]
Nice turnaround!

**Comment by atotic** [comment]
Just tested it. It does not thrown, but items are invisible until I resize the window.

**Comment by blasten** [comment]
@atotic you're right

**Comment by mdwragg** [comment]
+1 I'm seeing this too. Well diagnosed!

**Comment by devinivy** [comment]
We're also seeing this issue.  Has to do with `_physicalAverageCount` being zero, causing a `NaN` when computing `_physicalAverage`, I believe.  CC @kevmannn.

**Comment by devinivy** [comment]
@blasten I think this is less of a timing issue, and more a general issue around displaying an `iron-list` with zero items.  Even with PR #50 my list is eventually displaying, but I'm getting an exception that spawns from one of the debounced `_refresh` calls.

**Comment by blasten** [comment]
@devinivy are you using the version from master or v1.0.2?   There was an issue https://github.com/Polymer/polymer/issues/2193 we encountered, but the fix hasn't been released yet.  The following should fix it meanwhile:

```js
Polymer.ImportStatus.whenLoaded(function() { 
  list.fire('resize');
});
```

**Comment by devinivy** [comment]
I'm on 1.0.2.  Thanks @blasten– that gets the display working correctly for me.

**Comment by blasten** [comment]
@devinivy good to know

**Comment by blasten** [comment]
This issue should be fixed by now after https://github.com/Polymer/polymer/commit/2bffc4c84e706043355eaf367100b60beb9cce60. :)
