### ISSUE TITLE
iron-list scrollHeight can fail to update when items are added

### ISSUE THREAD

**Issue by tgsergeant** [PolymerElements/iron-list#463]
### Summary

When adding items to an iron-list, the scrollHeight (and therefore the size of the `<iron-list>` element) can fail to update, depending on the size of the scroll target, the size of the items before the change, and the size of the items after the change.

### Expected outcome

When items are added to the iron-list, the size of the list element should update to match.

### Actual outcome

The iron-list can fail to have its height updated.

### Live Demo
https://jsbin.com/hulebezefo/7/edit?html,output

### Steps to reproduce

1. Open the demo link above
2. Notice that the iron-list (lightblue) does not fill the whole container (pink)
3. Click the 'Add Items' button
4. Extra items will be added to the list, but the list element won't change size.

![iron_list_bug](https://user-images.githubusercontent.com/745035/28103586-d6f350a8-6719-11e7-88f1-e0d4fc8f788a.png)

5. In the code, change `NEW_ITEM_COUNT` from `55` to `53`. When the page refreshes, click the button again. It should work correctly this time.

### Browsers Affected

Can reproduce on all the browsers I tested:
- Chrome
- Firefox
- Safari 11
- Edge

### More details

* The relevant code is [updateScrollerHeight_](https://github.com/PolymerElements/iron-list/blob/276cba4e249e20a61ab838c3964b04061a26c27a/iron-list.html#L1383), which contains some logic to reduce updates to scrollHeight that seems to be the culprit.
* This bug is affecting Chrome's new MD Bookmark Manager, which is currently enabled on Dev/Canary channel. If you have folders with particular numbers of bookmarks, the bug is reliably reproducible there. Here's what the bug looks like in chrome://bookmarks:

![bookmarks_list_bug](https://user-images.githubusercontent.com/745035/28104638-7a8b5a8a-671f-11e7-9064-c12a234da27c.png)

**Comment by tgsergeant** [comment]
Hi @keanulee, any chance you can take a look at this?

(also cc @nik3daz)

**Comment by keanulee** [comment]
@tgsergeant iron-list must be explicitly sized (i.e. its height must NOT be determined by the height of its content) - see https://github.com/PolymerElements/iron-list#sizing-iron-list. The API has to be this way because if it's not explicitly sized, then the height would have be the height of the children, which means you would have to render the children, which defeats the whole point of a virtual list.

**Comment by tgsergeant** [comment]
Thanks for the reply.

To the best of my knowledge, the usage of iron-list in the demo meets the sizing requirements described in the docs. Specifically, the docs say

"... or delegate scrolling to an explicitly sized parent".

In the demo, we set `scroll-target="container"` on the iron-list to delegate the scrolling to its parent, and then we set this CSS to make the parent explicitly sized:

```css
#container {
  height: 1000px;
}
```

To explain the original problem a bit more, I think that instead of "its height must NOT be determined by the height of its content", the issue is more like

> "internally, the iron-list guesses its height based on the height of its content, but sometimes it guesses very wrong"

(see [updateScrollerHeight_](https://github.com/PolymerElements/iron-list/blob/276cba4e249e20a61ab838c3964b04061a26c27a/iron-list.html#L1383) for the code in question)

By updating the height in this way, the iron-list is able to make sure that its scrollbar roughly matches the expected height of the content. It doesn't matter if it's not exact, since it can adjust as the user scrolls down.

Similarly, though, we can use the approximate height to draw a box around the items. Again, it normally doesn't matter if it's not exact, since the user won't see the bottom of the card when it's off screen.

This works fine almost all the time, but there's this one specific case shown in the demo where the optimization in updateScrollerHeight_ doesn't trigger when it probably should. The result is that the iron-list itself is very wrong about what it thinks its height is (its internal height is 400px, when it should be ~2200px).

**Comment by keanulee** [comment]
Seems like we were over-optimizing and not catching this edge case. Fixed

**Comment by tgsergeant** [comment]
Great! Thanks for the fix!
