### ISSUE TITLE
jsbin examples in docs/README don't work

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/iron-list#465]
### Description
The jsbin links in the README point to examples that don't work

### Expected outcome
jsbin example works

### Actual outcome
```
11382-6924-111 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
runner:26 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
webcomponents-lite.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
apply-shim.html Failed to load resource: the server responded with a status of 404 (Not Found)
custom-style-interface.html Failed to load resource: the server responded with a status of 404 (Not Found)
custom-style.html:18 Uncaught TypeError: Cannot read property 'CustomStyleInterface' of undefined
    at custom-style.html:18
    at custom-style.html:72
runner:2 Uncaught ReferenceError: HTMLImports is not defined
    at runner:2
1x Failed to load resource: the server responded with a status of 404 (Not Found)
```

### Live Demo
http://jsbin.com/kokaki/edit?html,output

### Steps to reproduce
follow the link and open the console

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
This is unrelated to this repo, but it appears that "webcomponents-lite.min.js" isn't available on polygit.org. Not sure what the issue is, but "webcomponents-lite.js" (no "min") seems to work.

**Comment by davidmaxwaterman** [comment]
I think the links on your readme make it relevant to this report, no?

**Comment by arthurevans** [comment]
Yep. I don't know who owns the jsbins linked from the README, but they need to be updated or removed. (Or maybe migrated somewhere else, because jsbin seems to be very unstable these days.)
