### ISSUE TITLE
Mutating iron-list within an iron-list

### ISSUE THREAD

**Issue by kr05** [PolymerElements/iron-list#469]
I currently have an iron-list within another iron-list. The parent's data comes from a firebase-query element, and the child's data is computed from each parent item. The db structure and code looks a bit like this:

    DB: [
         category1: [
                     itemId1: {
                               price: 10,
                               title: "title" 
                              }
                    ]
        ]

    <iron-list id="categoryList" items="{{categories}}" multi-selection as="category">
            <template>
                <div class="category-holder">
                    <iron-list id="{{category.$key}}" items="{{_removeExtraIndex(category)}}" as="item" selection-enabled multi-selection selected-items="{{selectedItems}}" grid>
                        <template>
                            <div class$="{{_computeItemClass(selected)}}">
                                <p>[[item.title]]</p>
                                <p>[[item.price]]</p>
                            </div>
                        </template>
                    </iron-list>
                </div>
            </template>
        </iron-list>

After selecting any number of items, the user can tap on a fab to batch edit the price, which calls the following:

    (this.selectedItems).forEach(function(item) {
                    var list = this.$.categoryList.querySelector('#' + item.category);
                    var index = list.items.indexOf(item);
                    list.deselectIndex(index);
                    list.set(["items", index, "price"], 30);                   
                }, this);

A couple of things worth noting. I'm using querySelector instead of the recommended this.$$(selector) because I keep running into a "function DNE" error. I'm also deselecting item before changing it in accordance with the docs. But now I have another problem...after calling the function, only the first selected value gets updated and then I get the following error:

    Uncaught TypeError: inst.dispatchEvent is not a function

Here's a picture of the full error message:
[![enter image description here][1]][1]

Any pointers would be greatly appreciated. 

  [1]: https://i.stack.imgur.com/QKNFI.png

**Comment by keanulee** [comment]
Nested iron-list is not supported - see #161
