### ISSUE TITLE
list without fit does not scroll to top on item change

### ISSUE THREAD

**Issue by m4b** [PolymerElements/iron-list#47]
@blasten I have another polymer puzzle for you ;)

So, I think i've narrowed down the problem I mentioned in #21 to a list that:

1. **does not** have the fit class, 
2. and/or, very complicated nested cases where an iron list is fit inside a paper header which is inside another paper header which is inside a drawer.

I don't have a working sample of 2., but it's a pretty common case, especially in any large app.  But I suspect that if 1. gets fixed, then 2. will be resolved (if it isn't I'll submit another issue).

### _Without_ fit, does not scroll to top

You can [see this effect here](http://output.jsbin.com/vuvura) (only works in Chrome), if you scroll down to the bottom or middle, and repeatedly touch the list item buttons, which causes the list's items to be changed from 100 to 200, or 200 to 100.

If you simply change the list to have `class=fit` it works as expected, namely, on item change it scrolls to the top of the list.

The code is available at that url, but I'll put it inline here as well:

````html
<dom-module id="computed-list">
  <style>
  :host {
    @apply(--layout-fit);
  }
    iron-list {
      margin: 16px;
    }
  </style>
  <template>
    <!-- add class="fit" and works fine, scrolls to top correctly, etc. -->
    <iron-list id="list" items="[[_items]]">
      <template>
        <paper-button raised on-tap="_changeItems">[[item]]</paper-button>
      </template>
    </iron-list>
  </template>
  <script>
  (function() {
    Polymer({
      is: 'computed-list',

      properties: {
        _selected: {
          type: Number,
          value: 0
        },
        _items: {
          computed: '_computeItems(_selected)'
        }
      },
      _changeItems: function() {
        this._selected = (this._selected + 1) % 2;
      },
      _computeItems:function (selected){
        var i = 200;
        if (selected % 2 === 0) {
          i = 200;
        } else {
          i = 100;
        }
        var tmp = [];
        while (i--) {
          tmp.push(i);
        }
        console.log('item count: ', tmp.length);
        return tmp;
      }
    });
  })();
  </script>
</dom-module>
````

**Comment by blasten** [comment]
1. You need to put the `Polymer` definition inside ` HTMLImports.whenReady`:
http://jsbin.com/duhifeguti/edit?html,output

2. From the readme: `iron-list` must ether be explicitly sized, or delegate scrolling to an explicitly sized parent. By "explicitly sized", we mean it either has an explicit CSS height property set via a class or inline style, or else is sized by other layout means (e.g. the flex or fit classes). 

Also this should be useful: https://github.com/PolymerElements/iron-list#resizing

**Comment by m4b** [comment]
@blasten: well that was a derp on my part!  I thought if you used the `:host{}` to set it explicitly that counted as setting it, but I guess not.

So I'm still seeing the symptom of this issue (not scrolling to top on item change) in other cases (complex nested paper-header-panels, but it could be a manifestation of the list somehow not having a height, so I will close this particular issue, and reopen with a better example.

Sorry for wasting time!

**Comment by blasten** [comment]
@m4b `:host` is for the container `<computed-list>`, so you are adding `fit` to the container of the list. You will also need: 

```css
iron-list {
  @apply(--layout-fit);
  margin: 16px;
}
```
