### ISSUE TITLE
_itemsChanged(items.*) does not re-render list implicitly.

### ISSUE THREAD

**Issue by ernsheong** [PolymerElements/iron-list#475]
Referring to: https://github.com/PolymerElements/iron-list/blob/368f75fae81cd7696b710635eccacbca7a6a93b1/iron-list.html#L1067

### Description

Changes to the `items` array does not cause the iron-list re-render. A manual call to `Polymer.flush()` is still required.

### Expected outcome

The list is automatically rerendered after items has been changed with a completely new array.

### Actual outcome

The call here https://github.com/PolymerElements/iron-list/blob/368f75fae81cd7696b710635eccacbca7a6a93b1/iron-list.html#L1085 does not cause a Polymer.flush(), and indeed it never happens until the user scrolls more. 

### Steps to reproduce
1. Load a list.
2. Reload the list by replacing the `items` array completely.
3. The list does not get re-rendered.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by ernsheong** [comment]
Possibly related to https://github.com/PolymerElements/iron-list/issues/396

**Comment by ernsheong** [comment]
Changes to path "items.splices" also suffer from the same fate.

**Comment by keanulee** [comment]
Able to reproduce this with the latest iron-list with Polymer 2. Seems like the debounced `_render` call isn't actually called here https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1085. Working on a patch

**Comment by ernsheong** [comment]
@keanulee Thank you for the fast response!
