### ISSUE TITLE
Polymer iron list with position fixed element content hidden behind

### ISSUE THREAD

**Issue by bala89thangavel** [PolymerElements/iron-list#482]
### Description

i have a iron-list, And i am facing the issue when i keep paper-dropdown, date-picker(etc..) inside iron-list.

Basically the element with position fixed also has height or width higher then the iron-list container. 
Then the fixed element reside behind the iron-list container..

### Expected outcome

if i keep paper-dropdown, date-picker(etc..) inside iron-list should not reside behind the iron-list container

### Actual outcome

if i keep paper-dropdown, date-picker(etc..) inside iron-list is reside behind the iron-list container

### Live Demo
 http://jsbin.com/ginakis/edit?html,output

### Steps to reproduce

1. Put a paper-textbox inside the iron-list.
2. Put a `paper-dropdown or date-picker`  inside the iron-list.
3. Open the page in a web browser.
3. Click the `paper-textbox` and open the paper-dropdown

### Browsers Affected

- [ yes] Chrome
- [yes ] Firefox
- [yes ] Safari 9
- [ yes] Safari 8
- [yes ] Safari 7
- [yes ] Edge
- [yes ] IE 11
- [yes ] IE 10

**Comment by keanulee** [comment]
This is the same issue as #242. Because iron-list uses `translate3d` for each item, it creates a stacking context so fixed position items get clipped.
