### ISSUE TITLE
Recursive iron-list breaks data-binding

### ISSUE THREAD

**Issue by schrotie** [PolymerElements/iron-list#484]
### Expected Outcome
Should display nested iron-list

### Actual Outcome
Databinding breaks at first nesting level, property update notification inhibited

### Steps to reproduce

Put these components in a page. You should see the labels a, b, b but you only see a. When inspecting the properties of the recursively nested tester you see that array property of the first nested array property is set correctly. But when implementing observers on this (also deep sub-property observers) you see that the update trigger is never propagated to the first nested tester.

```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/iron-list/iron-list.html">

<dom-module id="recursive-list">
	<template >
		<iron-list items="[[array]]">
			<template>
				<div>
					<label>[[item.key]]</label>
					<recursive-list array="[[item.array]]"></recursive-list>
				</div>
			</template>
		</iron-list>
	</template>
	<script>
(function() {
	class Component extends Polymer.Element {
		static get is() {return 'recursive-list';}
		static get properties() {return {array : Array};}
	}
	window.customElements.define(Component.is, Component);
})();
	</script>
</dom-module>

<dom-module id="iia-test">
	<template >
		<recursive-list array="[[array]]"></recursive-list>
	</template>
	<script>
(function() {
	class Component extends Polymer.Element {
		static get is() {return 'iia-test';}
		static get properties() {return {
			array :{value:[{key:'a', array:[{key:'b', array:[{key:'c'}]}]}]},
		};}
	}
	window.customElements.define(Component.is, Component);
})();
	</script>
</dom-module>
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Nested iron-list is not supported - see #161
