### ISSUE TITLE
demo broken on webcomponents.org

### ISSUE THREAD

**Issue by n1ywb** [PolymerElements/iron-list#489]
### Description

Demo doe not work when demo link clicked

### Expected outcome

demo dialog pop up

### Actual outcome

nothing happen

### Live Demo

https://www.webcomponents.org/element/PolymerElements/iron-list

### Steps to reproduce
 go to https://www.webcomponents.org/element/PolymerElements/iron-list 

click demo

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Demo popup works as expected on Chrome - check your extensions, or provide more details:

![image](https://user-images.githubusercontent.com/1319720/31191210-af32a3f2-a8fa-11e7-90a3-2405f0020c1d.png)
