### ISSUE TITLE
Problems with item update on scrolling when there is an elements in between of paper-scroll-header-pandel and iron-list

### ISSUE THREAD

**Issue by edvail** [PolymerElements/iron-list#49]
In medium large project there is need to put iron-list into the custom element. That produces spare elements in between of paper-scroll-header-panel and iron-list. Even just <div> produces problem: only first 20 elements are rendered, and then comes only white space.
If I add fit class to that intemediate <div class="fit"> element, then first two list items are hidden behind the paper-toolbar.
Please try to play with <div id="problem"> element by yourself in my jsbin: <a class="jsbin-embed" href="http://jsbin.com/fadafa/embed?html,output">JS Bin on jsbin.com</a><script src="http://static.jsbin.com/js/embed.min.js?3.34.1"></script>
Please, help me solve that issue.

**Comment by blasten** [comment]
Is there a reason why you need: 
` <div id="problem" class="fullbleed layout vertical">`

If you remove the div then the list works as expected:
http://jsbin.com/xusugu/edit?html,output

The list doesn't offer a way to programmatically specify the scroller object yet.  If you really want to change it, you can create a `x-div` that exposes a `scroller` property and delegates it to the parent scroller (the `scroll-header-panel`.scroller). e.g.

```js
  Polymer({
    is: 'x-div',
    get scroller() {
      return Polymer.dom(this).parentNode.scroller;
    }
});
```

**Comment by blasten** [comment]
solved by using the `scrollTarget` property and [app-header-layout](https://github.com/PolymerElements/app-layout/).
