### ISSUE TITLE
iron-list items of different heights either overlap each other or have large gaps

### ISSUE THREAD

**Issue by rbjarnason** [PolymerElements/iron-list#501]
### Description
iron-list items of different heights either overlap each other or have large gaps, especially when scrolling up. We're using document as scroll target.

### Expected outcome
The items should always be in the right place.

### Actual outcome
Sometimes when scrolling down a list and always when scrolling up the items starts to overlap each other like in this image:
![image](https://user-images.githubusercontent.com/43699/33792113-fc42bcd6-dc8f-11e7-9068-85cf30139fb0.png)

Or this one:
![image](https://user-images.githubusercontent.com/43699/33792116-0d9227ba-dc90-11e7-8331-f08328b52fb1.png)

Here two iron-lists are side by side and this seems to cause the problem to be even worse.
![image](https://user-images.githubusercontent.com/43699/33792175-c730d8d8-dc90-11e7-9d6e-0a52bf5335b1.png)

### Live Demo
In this live demo I have a brute workaround - I've added a feature into my fork of iron-list that fires iron-resize at certain scroll intervals, 800px on larger screens and 300px on smaller screens.

https://yrpri.org/group/1075/news

Here is an example in the code:
https://github.com/CitizensFoundation/your-priorities-app/blob/master/client_app/src/ac-activities/ac-activities.html#L170

### Steps to reproduce
Well, this works in the simple iron-list demo. I'm not sure what causes this not to work for me. This has been a problem for me since Polymer 1.0 but now I've moved to iron-list 2 and I'm in the progress of upgrading the whole app and would like to try to figure out what the real problem is. Also, I'm moving from dom-repeat to iron-lists where I have two lists side by side and firing iron-resize events at certain scroll intervals affects scroll performance on large lists. 

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ x] Edge
- [ x] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
It would be helpful if you have an actual repro demo that _didn't_ work around the issue that can be debugged.

**Comment by rbjarnason** [comment]
Hi @keanulee I finally have a live demo of the bug - this is the latest iron-list unchanged.  You will need to scroll down then up again and maybe up and down a bit - after a bit it will start to have overlaps or large gaps.

https://staging-test.idea-synergy.com/group/2/news

This is a new server I'm setting up, still in staging mode and will be so for the next week or so.

**Comment by keanulee** [comment]
Not exactly sure if this is the problem, but it looks like the height of the items change as images in them load so they become out of sync with the heights memoized by iron-list. Maybe see if giving the images a static height fixes the issue?

**Comment by rbjarnason** [comment]
Thanks @keanulee! :) It was both an image in one place but mostly I was doing some funky things with dynamically processing text for emoji and links in each component and using set innerHTML. I have now refactored my code to do the text preprocessing right after the data is loaded and I use the juicy-html element to display the emojied and linkyfied content. Closing this ticket now.
