### ISSUE TITLE
Iron-list doesn't work with Iron-ajax

### ISSUE THREAD

**Issue by DaniPani** [PolymerElements/iron-list#509]
### Description
`iron-list` doesn't work when I try to bind `iron-ajax`. I'm new to Polymer so I tried almost everything that I found on Internet, but it didn't work. I got only a white page. `index.html` and `data.json` are in the same root.. What I'm doing wrong? This is my code

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">

  <title>ScuolaMedia</title>
  <meta name="description" content="ScuolaMedia description">

  <link rel="manifest" href="/manifest.json">

  <script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="/bower_components/polymer/polymer.html">
  <link rel="import" href="/bower_components/iron-ajax/iron-ajax.html">
  <link rel="import" href="/bower_components/iron-list/iron-list.html">

</head>

<body>
      <iron-ajax url="data.json" last-response="{{data}}" auto handle-as="json"></iron-ajax>
      <iron-list items="[[data]]" as="item">
        <template>
          <div>
            Name: [[item.name]]
          </div>
        </template>
      </iron-list>
</body>

</html>
```

```json
[
    {"name": "Bob"},
    {"name": "Tim"},
    {"name": "Mike"}
  ]
```

### Actual outcome
White Page

### Live Demo
https://codepen.io/DaniPani/pen/RQYXxV

### Browsers Affected
All

**Comment by Westbrook** [comment]
Assuming you had access to the `data.json` file referenced in the `iron-ajax`, you still wouldn't be able to bind `data` between the two elements here without either wrapping the two in a `dom-bind` https://www.polymer-project.org/2.0/docs/api/elements/Polymer.DomBind

```
<dom-bind>
  <iron-ajax  last-response="{{data}}" />
  <iron-list items="[[data]] />
</dom-bind>
```

Or in a parent element. This is required to facilitate the mediator pattern outlined by 2-way binding `data` to the `iron-ajax` component, and the subsequently into the `iron-list`. 

Check out the following for a working example:
https://wonderful-space.glitch.me/
https://glitch.com/edit/#!/wonderful-space
