### ISSUE TITLE
Polymer 3 compatible version

### ISSUE THREAD

**Issue by moodyjmz** [PolymerElements/iron-list#525]
### Description
Element fails in v3 and is listed as not working:

https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md

Is there a timeframe for when iron-list will land for Polymer 3?

### Expected outcome

Element works in v3

### Actual outcome

Element fails in v3

### Live Demo

https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md

### Steps to reproduce

Attempt to use in v3

### Browsers Affected

All

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
I recently [merged a PR](https://github.com/PolymerElements/iron-list/pull/523) that makes the tests better on 3.0 which hasn't been modulized/released yet, but that only affects the test files. Functionally, `@polymer/iron-list@3.0.0-pre.19` should be working.

**Comment by moodyjmz** [comment]
@keanulee hi, thanks for getting back quickly - I ran `npm dedupe` and after that it appears to be working fine
