### ISSUE TITLE
Reversing the "get firstVisibleIndex()" function 

### ISSUE THREAD

**Issue by tasosno1** [PolymerElements/iron-list#53]
Question,

Hi, 

The <code>get firstVisibleIndex()</code> function in the iron-list.html file is great for getting the first visible item in the viewport.

Unfortunately i've been using Jquery all these years and my Js skills just starting to surface with Polymer.

How will one go about reversing that, getting the index id of  the last item currently in the viewport?.

i.e a function called <code>get lastVisibleIndex()</code>

This will be helpful for pushing new items on the list as you have a virtual count of items to compare with and would be great for any screen size to record the bottom item rather than the top.

Thought to ask this question here rather than SO because these functions are inbuilt into iron-list.html file 

Thanks

**Comment by blasten** [comment]
That is all private API, but I can consider exposing `lastVisibleIndex`

**Comment by tasosno1** [comment]
@blasten If its already there, please do. At the mo, i'm using firstVisibleIndex() to push new items but earlier today i was thinking  about different screen sizes and its better i think to push when, lets say 10 items left from the bottom of the list than the top.

**Comment by tasosno1** [comment]
Thanks :)
