### ISSUE TITLE
Plans for reimplementing this based on lit-element?

### ISSUE THREAD

**Issue by MaKleSoft** [PolymerElements/iron-list#531]
With [lit-element](https://github.com/Polymer/lit-element) being touted as the way forward for building web components, I wonder if there are any plans for building something similar as iron-list based on lit-element? For me, having a highly performant, robust virtual list component is one of the key requirements for building complex web apps and iron-list has been doing an impressive job so far. I know building something like this requires a lot of skill so it would be cool to know that the same devs that built iron-list are working on a `lit-element`-based successor.

**Comment by keanulee** [comment]
@valdrinkoshi is working on a next-generation virtual scroller element over at https://github.com/valdrinkoshi/virtual-scroller. By itself it doesn't use lit-element, but you can probably design your own lit-element that uses it internally.

**Comment by MaKleSoft** [comment]
@keanulee Yep, I've come across that project as well. Looks like they are building on the learnings from iron-list, which sounds quite promising! I guess it'll be a while before it's production-ready though, so I guess I'll be using iron-list a while longer. Thanks responding!

**Comment by liyangguang** [comment]
Is there any replacement of iron-list before we have https://github.com/WICG/virtual-scroller ready? I'm migrating a code base from Polymer to lit-element and we are using iron-list.

**Comment by sebastianroming** [comment]
Same here - any working example of an (alternate) `iron-list` in combination with `lit-element`?

**Comment by hzmsrv** [comment]
@liyangguang you already found a solution?

**Comment by MaKleSoft** [comment]
I've built a pretty decent virtual list implementation for [padloc](https://github.com/padloc/padloc): https://github.com/padloc/padloc/blob/master/packages/app/src/elements/virtual-list.ts
Wouldn't be too much work to pull out the code and make it a standalone component and add some documentation but I'm pretty swamped with work right now. But if there is enough demand (let's say 10 thumbs up?) I could carve out an hour or two to get it done 😁

**Comment by liyangguang** [comment]
Ploymer / lit-element team built https://github.com/PolymerLabs/uni-virtualizer/tree/master/packages/lit-virtualizer, which replaces iron-list.
