### ISSUE TITLE
Iron-collapse and iron-list

### ISSUE THREAD

**Issue by derhuebiii** [PolymerElements/iron-list#534]
### Description

I have a list item that contains an iron-collapse. What I managed already is that the list item changes when the iron-collapse transition has finished. Anyway I want the resizing to be in realtime.

### Expected outcome
Items below item with iron-collapse change during transition.

### Actual outcome
Change only happens after transition (as iron-resize is only fired then).

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
That sounds really expensive (in terms of performance) to implement - you'd have to run `_render` on every frame of the transition, so I don't think it's possible.
