### ISSUE TITLE
Rendering issue with hidden lists and data-binding

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/iron-list#54]
##### Problem 
Iron-list is not rendering when using polymer data binding inside of `neon-animated-pages`. So far, I've found that if I trigger `data-source` to re-fetch the data (internally using `iron-ajax`), that the list then renders correctly. I can navigate to other pages and come back and it will still work (after the initial fix).

##### Solutions
If I refresh the page and data is cached, it will render the current `iron-list`. But, after navigating to a new list and the new list is empty (the list items' skeletons are all rendered on top of each other). 

Manually calling `_render()` on the list also works; however, it only fixes the `iron-list` currently being displayed. Ex.) One button calls render on all `iron-list`s, but only the currently displayed one is fixed, the process must be repeated on each page.

##### Thoughts
It feels like there is some timing issue between `iron-list`s data-binding receiving the notification about data-available, and rendering when hidden/detached.

##### Example
```
<paper-drawer-panel>
<paper-header-panel>
.....
<neon-animated-pages>
  <data-source data="[[list]]"></data-source>
  <data-source2 data="[[list2]]"></data-source>
  <neon-animatable>
    <x-element data="[[list]]"></element>
  </neon-animatable>
  <neon-animatable>
    <x-element2 data="[[list2]]"></element>
  </neon-animatable>
</neon-animated-pages>
```

```
<dom-module id="x-element">
  <iron-list items="[[data]]"></iron-list>
</dom-module>
...
properties: {
  data: Object,
}
```

##### Versions
Iron-List Commit #221f11d9eacd8e3ef8c0c28c3423e8e5dea413d1
Linux Chrome 44.0.2403.125 (Official Build) (64-bit)

**Comment by blasten** [comment]
This issue seems to be related to https://github.com/PolymerElements/neon-animation/issues/60

**Comment by blasten** [comment]
I'm closing this issues as it's not related to iron-list itself.
