### ISSUE TITLE
iron-list is incompatible with Polymer policy of stripping template contents

### ISSUE THREAD

**Issue by Jamtis** [PolymerElements/iron-list#545]
### Description
`iron-list` is incompatible with Polymer policy of stripping `template` contents.

### Expected outcome
When using `iron-list` in a `PolymerElement`'s template `iron-list` should produce the content of its child `template`.

### Actual outcome
The content of the child `template` gets stripped by the parent `PolymerElement` as described [in the docs](https://www.polymer-project.org/3.0/docs/devguide/dom-template#preserve-template-contents).

### Live Demo
jsbin demos @ https://www.webcomponents.org/element/@polymer/iron-list
That's also why those demos are broken...

### Steps to reproduce

In Polymer 2: Use `<iron-list>` in the parent `PolymerElement` (HTML-Code)
In Polymer 3: Use `<iron-list>` in the string returned by the parents `template` method

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

#### See also
https://stackoverflow.com/questions/52617387/how-to-use-template-based-elements-in-polymer-2-3

**Comment by keanulee** [comment]
This shouldn't be an issue. I updated the 3 JS Bin demos on the README to Polymer 3 and they seem to work without having to modify the HTML in the template. (I did modify the CSS styles, but those shouldn't be strictly necessary to get iron-list running.)

JS Bin seems pretty bad with caching, so if you don't see the updates at first try opening them in an incognito window.

**Comment by Jamtis** [comment]
Thanks very much.

Indeed, the updated version works (both normally and incognito).

Am I right in the assumption that elements like `iron-list` can use their child `template`s despite stripping because the `Templatizer` them?
Does that mean that `template`s must either have the `perserve-content` attribute or be `Templatizer`ed?

**Comment by keanulee** [comment]
iron-list will run `Templatizer` over it's child `<template>` so you don't need to use `perserve-content`.
