### ISSUE TITLE
Some implementation or virtual-scroller or iron-list for litElement?

### ISSUE THREAD

**Issue by herberthobregon** [PolymerElements/iron-list#553]
I think it has not followed the development `virtual-scroller` for a long time, and the doc is harder to use, to difference of the `iron list` that is fast enough as visually and the docs is easy to use.

There are jobs started? or proposed to open a branch to start their migration

**Comment by zeriss** [comment]
I'm working on a virtual-scroller projet for lit, but i'm struggling with the template and binding sytems.

**Comment by herberthobregon** [comment]
You can use https://www.npmjs.com/package/lit-virtualizer/v/0.4.1

https://github.com/PolymerLabs/uni-virtualizer/tree/master/packages/lit-virtualizer
