### ISSUE TITLE
Focus jumps to first element when bound data changes

### ISSUE THREAD

**Issue by jon-mann** [PolymerElements/iron-list#566]
### Description
When the items array bound to an iron-list is updated, the internal focus jumps up to the first element, while the visible focus (item with :focus attribute) doesn't change.  

### Live Demo
https://glitch.com/edit/#!/rebel-methane
(hit "Show" -> "Next to the Code" to run it.)

### Repro

1. Focus on any item in the list.
2. Wait for the order to update.
3. Press the down arrow

Expected: Next element gets highlighted
Actual: Second element gets highlighted

Note that with dev tools open at the time the list is updated, you'll see the first item gets the `tabindex` attribute set to 0, but the `focus` attribute doesn't move.

### Browsers Affected
Only tested Chrome.

**Comment by jon-mann** [comment]
I also tried using `preserve-focus` but unfortunately it didn't seem to have any effect.

When I attempted to record which item was focused before the data update and manually set it back with `focusItem(index)` after, it would work for one update and then set back to 0 after the next.  I tracked it down to a call to `_removeFocusedItem()` at [iron-list.js#L1088](https://github.com/PolymerElements/iron-list/blob/master/iron-list.js#L1088).  After I commented that out, my workaround of manually setting focus after each update became stable.  I assume that line can't actually be removed, but hopefully this will be helpful in finding a good solution.

**Comment by graynorton** [comment]
Per an offline conversation with @jon-mann, I'm going to close this issue.

There's a relatively simple way to achieve the desired results by adding some lightweight focus management code at the app level, and at this point in the lifecycle of `iron-list` we have a very high bar for making changes (critical, must-fix issues only).

This modified glitch illustrates the type of focus management code you might add to your app if you experience similar problems: https://glitch.com/edit/#!/efficacious-toothbrush

Please feel free to reopen this issue or create a new one if you come across a behavior that can't be  easily worked around, and we'll reevaluate.
