### ISSUE TITLE
Only seeing 20 items

### ISSUE THREAD

**Issue by deadlyfingers** [PolymerElements/iron-list#57]
I seem to be only seeing the first 20 items in the list, however the scroll will go down further to where more items should be but there is only white space.

```html
<iron-ajax url="./data.json" last-response="{{data}}" auto></iron-ajax>
<iron-list id="my-list" items="[[data]]" as="item" flex>
<template>
  <div class="row" >
    <p>[[item.message]]</p>
    <div class="divider"></div>
  </div>
</template>
</iron-list>
```

**Comment by blasten** [comment]
@deadlyfingers `flex` should be a class.   `class="flex"` should fix it.
