### ISSUE TITLE
Re-rendering individual list items

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/iron-list#60]
I'm using ``iron-list`` to render a calendar where each item in the list is a month.  Each month has its own array of days rendered using ``dom-repeat``.  A ``day`` is an object along the lines of ``{day: 1, active: false}`` with the active property indicating whether that day is the current date.  A simplified version looks like this:

```
<iron-list items="{{months}}" as="month" index-as="monthIndex">
	<template>
		<div class="month">
			<template is="dom-repeat" items="{{month.days}}" as="day" index-as="day-index">
				<div class="day" active$="{{day.active}}">{{day.day}}</div>
			</template>
		</div>
	</template>
</iron-list>
```

``months`` is a property of my custom element.  When the date changes, I call ``this.months[monthIndex].days[dayIndex].active = true;``  When I inspect the months array, I can see that ``active`` property is true on the appropriate ``day`` object.  However, the ``active`` attribute on the ``.day`` div doesn't get updated unless I scroll that month far out of the list and then back into view.  Is there a way to re-render that one month div when one of its days changes?  Is there a reason the ``active`` attribute isn't being updated?

**Comment by blasten** [comment]
@miztroh yes. you can use `set`  to notify the change.    e.g. `list.set('items.0.days.0.active', true);`  that will be the first day of the first month.

**Comment by miztroh** [comment]
Beautiful!  Thanks so much.
