### ISSUE TITLE
iron-list scrolling is laggy on iOS after first 20 items

### ISSUE THREAD

**Issue by deadlyfingers** [PolymerElements/iron-list#61]
I've have an iron-list element running buttery smooth on desktop but is very laggy on iOS simulator or device. If you scroll quickly on iOS the items jump back up and often white space is left until the scrollbar comes to a complete halt.

Polymer 1.0 iron-list project:
https://www.dropbox.com/s/oxihd7eddknbq5b/PolymerIronList.zip?dl=0 
localhost setup: `npm install && bower install` then run with `node server.js`. 

Sample iOS project to just build & run:
https://www.dropbox.com/s/w1xtjzyf53s4pfz/PolymerApp.zip?dl=0

Is this something with flex vs fit layout or a bug?

**Comment by blasten** [comment]
@deadlyfingers are you running it from iOS Safari or from a webview?

**Comment by deadlyfingers** [comment]
Yes, packaged as native iOS app in WebView is where the issue happens.

**Comment by blasten** [comment]
Unfortunately, that's a limitation. Apple still use an old webkit version for Webviews that doesn't support the CSS property `-webkit-overflow-scrolling: touch`

**Comment by hereiam133** [comment]
This is an issue also in both a cordova wrapped android app and just in a chrome web browser
