### ISSUE TITLE
dereferencing null scroller in updateViewportBoundaries

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-list#63]
Just updated to Polymer 1.1. Got some iron-pages in visible, and invisible pages, and one of them throw inside updateViewportBoundaries.

Code flow that makes it throw:
- `_resizeHandler` is getting called before attached.
- `updateViewportBoundaries` calls `window.getComputedStyle(this._scroller);`
- `this._scroller` is null, BAM!, there is a null exception.

"Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

**Comment by blasten** [comment]
@atotic can you try https://github.com/PolymerElements/iron-list/tree/fix-resize
