### ISSUE TITLE
Why must index be explicitly declared?

### ISSUE THREAD

**Issue by mvpmvh** [PolymerElements/iron-list#65]
As per the docs, "List item templates should bind to template models of the following structure:"

    {
        index: 0,     // data index for this item
        item: {       // user data corresponding to items[index]
            /* user item data  */
        }
    }

Can you help me understand why the index must be explicitly provided to iron-list vs iron-list implicitly knowing and providing this data upon each rendered iteration?

**Comment by blasten** [comment]
They don't have to now, I think we need to fix the docs. You can just use:
```json
{
  /* user item data  */
}
```
