### ISSUE TITLE
adding items not possible

### ISSUE THREAD

**Issue by Nemo64** [PolymerElements/iron-list#66]
With a normal `<template is="dom-repeat">` it is possible to update the list explicitly using `.render();` but i don't see a way to do it with the `<iron-list>`. There is the private method `._update()` which works but it's private and it also breaks if it's called too early.

My entire workaround is:
```JavaScript
_updateList: function () {
    // workaround for https://github.com/PolymerElements/iron-list/issues/66
    var list = this.$.list;
    if (list._initRendered) {
        setTimeout(function () {
            list._update();
        }, 10);
    }
}
```

**Comment by blasten** [comment]
I am not sure what the use case was here. Can you describe why this is needed?

**Comment by Nemo64** [comment]
I have a contact list with the capability to add new ones. These new contacts must appear in the list. Basic example ;)

**Comment by blasten** [comment]
You can use `push`  e.g.   `list.push('items', itemModel);`  where `itemModel` is the data model.

**Comment by Nemo64** [comment]
Thanks, seems to work. Is this method documented somewhere? I only found `.set()` and `.notifyPath()`.
