### ISSUE TITLE
Anything equivalent to the old core-list.refresh(true) method?

### ISSUE THREAD

**Issue by urandom** [PolymerElements/iron-list#67]
I used the old .refresh(true) method to update the list whenever I made a change to a property of one of the items. I was hoping that the list would update an item whenever I did ```this.set('item.' + index + '.something', some_value)```, but that doesn't seem to be the case. So how do I force the list to refresh itself?

**Comment by dulimarta** [comment]
Poking into the source code of `iron-list.html`, I found the `iron-resize` event handler (that invokes the 'private' function `_resizeHandler()`) and use the following `fire` call from the element that hosts my `iron-list`

    this.$$('iron-list').fire('iron-resize');

But I don't see any updates to the web UI.

**Comment by urandom** [comment]
After some debugging I found out that the list will change an item's representation if a binding is listening to a path change, i.e.: ```prop="[[ _computeChange(item.*) ]]"```. Changing to that and handling the change record itself solves my particular problem

**Comment by blasten** [comment]
That's correct. That is the reason why we removed `refresh` There should not be any need for such a method.

**Comment by dtruffaut** [comment]
Can you please provide a working example ?
