### ISSUE TITLE
When should I use iron-list and when dom-repeat?

### ISSUE THREAD

**Issue by fxedel** [PolymerElements/iron-list#68]
For what kinds of list should I use iron-list instead of dom-repeat? Or should I use dom-repeat at all? Well, the syntax is very similar:

```html
<iron-list items="[[data]]" as="item">
  <template>
    <div>
      Name: <span>[[item.name]]</span>
    </div>
  </template>
</iron-list>
```

against

```html
<template is="dom-repeat" items="[[data]]">
  <div>
    Name: <span>[[item.name]]</span>
  </div>
</template>
```

I know that iron-list optimizes things like scrolling (doesn't it reuse list items?), but does that matter with a list size under 50? Or is the content important – are images better handled by iron-list? Or is iron-list "simply better", and I should use it always where I can?

Thanks for your answers ;-)

**Comment by blasten** [comment]
@fxedel you should use an `iron-list` when you have significantly more DOM nodes than the ones visible on the screen. e.g. you have 500 nodes, but only 10 are visible at the time. In this case, a `dom-repeat` will still create 500 nodes which will slow down your web app, but `iron-list` will only create 10.

However, having an iron-list does not mean that you can load all the data at once. Say, you have a million records in the database, you want to split the data into pages so you can bring a page at the time. The page could contain 500 items, and iron-list will only render 10.
