### ISSUE TITLE
The list hijacks the scroller even when not visible

### ISSUE THREAD

**Issue by urandom** [PolymerElements/iron-list#70]
When the iron-list is hidden for some reason (e.g. is a page within an iron-pages component), and the scroller is not its immediate parent (it is set manually), nothing will stop the list from hijacking the scroller, even if something else is filling the scroller (e.g. another page is currently selected). 

Modifying the following iron-list method fixes the problem:
```javascript
    _scrollHandler: function() {
      if (this.offsetHeight > 0) {
        this._refresh();
      }
    },
```

**Comment by blasten** [comment]
Oops. I think we should fix that in the list. Another solution would be to set the scroller to `null` programmatically when you hide the list.  e.g.
```js
list.style.display = 'none';
list.scroller = null;
```
In that way, the list can detach the event listener from the scroller  and  `this.offsetHeight > 0` won't be necessary.

**Comment by blasten** [comment]
I'm going to handle this issue from https://github.com/PolymerElements/iron-list/issues/70
