### ISSUE TITLE
selection functionality using clearSelection() et. al. causes severe breakage in Polymer 1.0.8

### ISSUE THREAD

**Issue by m4b** [PolymerElements/iron-list#74]
If Polymer is pinned at 1.0.8, or less than 1.1.0, `<iron-list>` (and hence the rest of the app) breaks on startup with errors like:

```
Uncaught TypeError: this.$.selector.clearSelection is not a function
```

See line [1178](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1178) and others for the culprit.  It looks like `array-selector` added new methods (`isSelected`, `clearSelection`) in the 1.1.0 release, which aren't in 1.0.8?

Solution is maybe something like:

```js
      if (this.$.selector.clearSelection) {
        this.$.selector.clearSelection();
      } else {
        this.selected = [];
      }
```
But I didn't look too hard into it, cause I'm really busy :hear_no_evil:

**Comment by blasten** [comment]
Yeah, that's right. The release should point to polymer 1.1.0, I will update the bower file.

**Comment by blasten** [comment]
Done. You should update your bower to `polymerelements/iron-list#^1.1.0`

**Comment by Alos** [comment]
I have a similar issue with `polymerelements/iron-list#^1.3.14` while running it along with Polymer 2.0 Preview. I'll investigate further.
