### ISSUE TITLE
iron-list inside an iron-dropdown

### ISSUE THREAD

**Issue by yo3jones** [PolymerElements/iron-list#76]
I am trying to create a component where a user can select a value from a dropdown. In my case the number of values the user can select from can be very large.  Because of this I am trying to put an iron-list inside the dropdown for performance.

When trying this, I'm getting some strange results. I have tried setting a static height and width to both the parent element (iron-list is flex) and iron-list it's self.

Here is an example of the result:
<img width="302" alt="iron-list" src="https://cloud.githubusercontent.com/assets/532441/9429517/7b6644b8-4987-11e5-87b4-ce4e16e2af29.png">

**Comment by blasten** [comment]
cc @cdata

**Comment by blasten** [comment]
this issue has been moved to https://github.com/PolymerElements/iron-dropdown/issues/24
