### ISSUE TITLE
Perf: large paints on chromestatus.com

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-list#78]
The [iron-list demo](https://elements.polymer-project.org/bower_components/iron-list/demo/index.html) doesn't exhibit this but I'm using iron-list as described in https://github.com/PolymerElements/iron-list/issues/73 (not in a paper-scroll-header-panel).

Scrolling the iron-list shows the entire area repaints :(

![screenflow](https://cloud.githubusercontent.com/assets/238208/9449489/b7b85b2e-4a57-11e5-9969-0a1e4fb5bb50.gif)

**Comment by blasten** [comment]
@ebidel :( You can add `translateZ(0)` to the iron-list. Please check this comment: https://github.com/PolymerElements/paper-scroll-header-panel/issues/41#issuecomment-133595788

**Comment by ebidel** [comment]
That was the first thing I tried, but no luck. It usually does the trick, but there's something else going on here.

![screen shot 2015-08-24 at 1 06 35 pm](https://cloud.githubusercontent.com/assets/238208/9451009/fdaeb566-4a60-11e5-9e2c-50336bd72c2b.png)

**Comment by ebidel** [comment]
@blasten I'm not sure this is the right use of `will-change`: https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L95. Namely, this element never gets transformed, it's the children it manages, correct?

For me, removing this will-change makes the paint region smaller, but `translateZ(0)` still doesn't promote the layer.

**Comment by blasten** [comment]
@ebidel I think you right. we should remove the will-change.

**Comment by blasten** [comment]
Also, I will point out that iron-list adjusts the height of the items container when the items have different heights (It won't if the items have the same heights). This adjustment will cause a repaint, but in our perf metrics we keep the target of 60fps on desktop and mobile.

**Comment by ebidel** [comment]
Should we still keep this open. The paints are still happening

**Comment by m4b** [comment]
I'm still seeing the paints as well with v1.1.0 and polymer v1.1.1
