### ISSUE TITLE
Occasional duplicate entries in iron-list

### ISSUE THREAD

**Issue by fiber** [PolymerElements/iron-list#80]
I'm observing occasional duplicate entries in the list, which disappear after some scrolling back and forth.

**Comment by blasten** [comment]
That's not expected. Can you share the code you're using?

**Comment by fiber** [comment]
Sorry. Had no time to reproduce this last night. Here you go.

It's not just duplication but some random misses and duplicates and misorders. This seems to occur around item #70 only after initially scrolling down. After scrolling up, the items seem to have the correct order. I get slightly different results depending on window size. Here is a screenshot. The gists  contain code and some static json data.

![polymer-disorder-bug](https://cloud.githubusercontent.com/assets/192150/9465017/05209df0-4b29-11e5-9845-d12f680803a6.png)

iron-list-disorder.html https://gist.github.com/fiber/164b49b76eabe67dd729
bugdata.json https://gist.github.com/fiber/b1598bef89d437280300

**Comment by blasten** [comment]
I  followed your steps and I couldn't replicate the issue. Can you give me more details about the environment (polymer version, iron-list version), browser?

**Comment by fiber** [comment]
Polmyer 1.1.1
iron-list 1.0.3
Chrome Linux Version 43.0.2357.125 (64-bit)

I also noticed the issue on an Android Tablet using Chrome Android.

2015-08-26 21:25 GMT+02:00 Emmanuel Garcia <notifications@github.com>:

**Comment by fiber** [comment]
the issue also exists with iron-list 1.1.0

**Comment by fiber** [comment]
... and also with Firefox 40.0

**Comment by fiber** [comment]
which of the elements are disordered really depends on window size. scroll down and check for the sequence numbers. They should be in order. For smaller windows this seems to happen before #70.

**Comment by fiber** [comment]
Let me know if I can provide any more assistance to track this down.

**Comment by blasten** [comment]
@fiber thanks for coming to the Polymer summit! I have this jsbin http://jsbin.com/xutene/edit?html,output based on your code and I couldn't repro the issue.

**Comment by fiber** [comment]
Weird. I see 59, 60, 64, 65 missing (screenshot attached.)

2015-09-17 10:32 GMT+02:00 Emmanuel Garcia <notifications@github.com>:

**Comment by fiber** [comment]
here's a disorder - 23 -22 -24 is clearly the wrong order, 26 is missing
after all. After scrolling down to ~#40 and then scrolling back up things
look ok.

2015-09-17 10:40 GMT+02:00 Sven Engelhardt <sven@engelhardt.to>:

**Comment by fiber** [comment]
with a slightly smaller window - 24-25-26 is followed by 24-25-26

2015-09-17 10:49 GMT+02:00 Sven Engelhardt <sven@engelhardt.to>:

**Comment by blasten** [comment]
@fiber I was able to repro and found the issue. Can you try this branch?   `bower install polymerelements/iron-list#pool-patch`

**Comment by fiber** [comment]
Awesome. This indeed seems to fix it. :+1: I'm not sure I fully understand your patch, except for the fact that iron-list is even faster now ;)

**Comment by blasten** [comment]
That's awesome! Yes, the logic was incorrect there.
