### ISSUE TITLE
Data-bound parent array inside iron-list not refreshing properly

### ISSUE THREAD

**Issue by Compufreak345** [PolymerElements/iron-list#82]
Hi,

I've got a dom-repeat inside an iron-list, bound to an array in the parent element and I am adding items to the array. The dom-repeat inside the iron-list does not refresh, if I do the same inside another dom-repeat  instead of the iron-list it does. 

I wrote a small example for this, the issue gets visible when clicking on the second button : 
http://jsbin.com/jebudar/6/edit?html,output

Another interesting thing : On my local project I tried using a custom element containing the dom-repeat instead of nesting the dom-repeat directly. If I add an observer there : 
```
            observers:[
                "_listChanged(list2.*)"
            ],
```

It fires when I add an element, but the change-array is always empty.

Is this intended behavior or is this a bug?

/edit : This might be releated to https://github.com/PolymerElements/iron-list/issues/75

**Comment by blasten** [comment]
This issue is confirmed.

**Comment by blasten** [comment]
@Compufreak345 This issue is fixed now, please run `bower update`
