### ISSUE TITLE
Unable to scrollToIndex

### ISSUE THREAD

**Issue by motss** [PolymerElements/iron-list#87]
I was trying to create a custom element and was using `iron-list` inside a `neon-animated-pages` element. I was able to generate the list but encountered a problem when came to setting the position of the scroller. 
Any way to resolve this error while trying to use `scrollToIndex` of `iron-list` (an basic example of a solution would be greatly appreciated)?

`Uncaught TypeError: Cannot read property 'offsetHeight' of null`

**Comment by blasten** [comment]
Do you have a code example I could look at?

**Comment by blasten** [comment]
ping

**Comment by blasten** [comment]
I'm closing this issue, feel free to reopen if you have a code that reproduces this issue.
