### ISSUE TITLE
selected=...

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-list#88]
Based on 
https://github.com/PolymerElements/iron-selector
https://github.com/PolymerElements/iron-pages
https://github.com/PolymerElements/paper-radio-group
...

I expect `selected=...` to be consistent.
```html
<iron-localstorage name="selectedItems" value="{{selectedItems}}"></iron-localstorage>
<iron-list class="flex" items="{{data}}" as="item" selected="{{selectedItems}}" selection-enabled>
````

But it doesn't seem to work, I can't preload selected items. Why are you doing this?
https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L121

A) I am doing something wrong again which is 99% of the case usually
B) Or is this a, we do not collaborate with other team members problem :P

Yes, I asked on polymer.slack.com first to see if it was something stupid but no response yet.

**Comment by blasten** [comment]
This property was named `selected-items` for multi item selection and `selected-item` for single item selection.
```html
<iron-localstorage name="selectedItems" value="{{selectedItems}}"></iron-localstorage>
<iron-list class="flex" items="{{data}}" as="item" selected-items="{{selectedItems}}" selection-enabled multi-selection>
```

That being said, I think this property should be named `selected` instead of `selectedItems`.

**Comment by gertcuykens** [comment]
Thank you, that would indeed satisfy my obsessive compulsive personality disorder :D

```html
    <array-selector id="selector" items="{{items}}"
        selected="{{selected}}" selected-item="{{selectedItem}}">
    </array-selector>
```

**Comment by blasten** [comment]
I was looking at this again, and  iron-selector uses `selected-items` https://github.com/PolymerElements/iron-selector/blob/master/iron-multi-selectable.html.   The `selected` property in `Polymer.IronSelectableBehavior` is used for the item index.

https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L32-L37
