### ISSUE TITLE
Iron-list breaks styling of other elements in neon-animatable within paper-dialog

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerElements/iron-list#90]
I added an ```<iron-list>``` to the first ```<neon-animatable>``` within a ```<paper-dialog>```. This breaks the default and custom styling of the elements within the other ```<neon-animatable>```'s.
The styling is correct if I remove the ```<iron-list>```. The styling is also correct if the ```<neon-animated-pages>``` are not within a ```<paper-dialog>```.

Here the minimal reproduction case:
```javascript
<dom-module id="bug-example">
	<template>
		<style>
			paper-icon-button {
				--paper-icon-button-ink-color: red;
			}
		</style>
	
		<paper-dialog id='dialog' class='fit' entry-animation='slide-down-animation'>
			<neon-animated-pages selected='[[selectedPage]]'>
				<neon-animatable>
					<paper-icon-button icon='arrow-forward' on-tap='_tapPage2'></paper-icon-button>
					<iron-list items='[[values]]'>
						<template>
							<paper-item>[[item]]</paper-item>
						</template>
					</iron-list>
				</neon-animatable>
				
				<neon-animatable>
					<paper-icon-button icon='arrow-back'></paper-icon-button>
				</neon-animatable>
			</neon-animated-pages>
		</paper-dialog>
	</template>
	         
</dom-module>

<script>

(function() {

	Polymer({
		is: 'bug-example',
		ready: function() {
			this.selectedPage = 0;
			this.values = ['a','b','c'];
		},
		open: function() {
			this.$.dialog.open();
		},
		_tapPage2: function(e) {
			this.selectedPage = 1;
		}
	});

})();
</script>
```

See how the size (default styling) and the focus ripple color (custom styling) of the icon break:

When opening the dialog (correct styling):
![bug-example-page1](https://cloud.githubusercontent.com/assets/9339055/9756503/fb92a9aa-56da-11e5-8fd5-3a7af7938340.PNG)

After clicking the forward icon (wrong styling):
![bug-example-page2](https://cloud.githubusercontent.com/assets/9339055/9756507/008db12a-56db-11e5-859f-37385fd53634.PNG)

**Comment by blasten** [comment]
I cannot reproduce this issue. Could you do a `bower update`? Please reopen if the issue is still occurring.
