### ISSUE TITLE
500+ items

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-list#91]
http://output.jsbin.com/vugeru

Isn't it suppose to just load the next 500 when you keep scrolling down?

**Comment by Compufreak345** [comment]
Add a height to your iron-list and it works.

> Important: iron-list must ether be explicitly sized, or delegate scrolling to an explicitly sized parent. By "explicitly sized", we mean it either has an explicit CSS height property set via a class or inline style, or else is sized by other layout means (e.g. the flex or fit classes).

Source : https://elements.polymer-project.org/elements/iron-list

**Comment by chuckh** [comment]
@gertcuykens if you change `<link rel="import" href="iron-flex-layout/iron-flex-layout.html">` to `<link rel="import" href="iron-flex-layout/classes/iron-flex-layout.html">`  then ` <iron-list class="flex" items="[[data]]" as="item">` will work for sizing in http://output.jsbin.com/vugeru.

**Comment by ebidel** [comment]
Closing, as this isn't a bug. Please reopen if the suggestions don't fix your issue.

**Comment by gertcuykens** [comment]
@chuckh Your magic is working! @ebidel How is the polymer linter going :) because only people who really know what they are doing in polymer can find mistakes like this.

**Comment by ebidel** [comment]
I'm not sure if the linter would have helped here. It's specific to iron-list and called out with a big "IMPORTANT".

**Comment by gertcuykens** [comment]
@ebidel I did use flex to start with, its this part that only pro's will detect `iron-flex-layout/iron-flex-layout.html` vs `iron-flex-layout/classes/iron-flex-layout.html` so there are apparently two kinds of flexing.

```
Important: iron-list must ether be explicitly sized, or delegate scrolling to an explicitly sized parent. By "explicitly sized", we mean it either has an explicit CSS height property set via a class or inline style, or else is sized by other layout means (e.g. the flex or fit classes).
```

**Comment by ebidel** [comment]
Yea, it's a little buried:
https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes.

There's also a guide:
https://elements.polymer-project.org/guides/flex-layout

**Comment by gertcuykens** [comment]
Ok the migration guide was clear, but the other link is benchmarking my cpu and gets stuck in javascript loop :D But as long as we agree that if a noob like me uses the class flex and actually sees 500 items in full screen. The last thing he or she is going to think about is. "Wait a minute maybe i am using the wrong flex"

**Comment by niedzielski** [comment]
Thank you for this thread. I had the same issue because I made the same mistake. @gertcuykens' iron-list example was very concise and helpful too.
