### ISSUE TITLE
Problem with dom-if sub-templates.

### ISSUE THREAD

**Issue by alan-strohm** [PolymerElements/iron-list#95]
If I take the demo and surround the outer div with  <template is="dom-if" if="[[item.boolean]]"> the items that get rendered get rendered on top of each other.  I'd expect this to work the same as the normal demo, but with only the boolean=true items rendered.  Let me know if you need a more complete example, description to reproduce.

**Comment by blasten** [comment]
@alan-strohm can you send a code to repro the issue?

**Comment by alan-strohm** [comment]
Here's a modified version of a jsfiddle I found in a different bug:
http://jsfiddle.net/s6f029j3/5/

**Comment by blasten** [comment]
@alan-strohm This issue should be fixed by https://github.com/PolymerElements/iron-list/issues/107.  Here's a demo: http://jsbin.com/mekaji/edit?html,output
