### ISSUE TITLE
Custom transformation in the demo only distracts and has nothing to do with iron-list

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/iron-list#97]
Per title, it would probably be a good thing to remove it so that it won't distract when people try to learn how the component works when checking out the code. It might be a fine secondary demo to add to `<paper-scroll-header-panel>` though. Just wanted to point this out, but all up to you guys :) At the very least it would be nice to add a minimal working demo without the extras.

**Comment by blasten** [comment]
I think we should have a `basic` vanilla demo, so I agree.

**Comment by indolering** [comment]
I agree with the need for a more basic demo, but I really want to keep the slick version around so I know how to emulate it : )

**Comment by blasten** [comment]
btw, this demo has been added recently https://github.com/PolymerElements/iron-list/blob/master/demo/basic.html 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
