### ISSUE TITLE
Big size differences causes list item to disappear too early.

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/iron-list#98]
I has just in the middle of development and at one point incorrectly my first item became about the size of 20 normal list items. Whilst scrolling down however the item would disappear before it left the viewport.

Just the sizes in case they turn out to be useful:

 - First item: 1176x3096
 - Rest of the items: 150 to 300px  

It's not the a huge issue in my case (I think/hope), as the items should all be more similarly sized, but it still shouldn't happen. Especially considering there still are a **lot** of DOM-loaded items out of view.

**Comment by blasten** [comment]
@David-Mulder This will be an issue because we use the average of the items height to estimate how many items should be rendered in certain cases. That said, I think we can have a way to handle the case where the average is not useful.

**Comment by hawkett** [comment]
An obvious real-world example of the need for broad size variance is a slack-like post stream - some things are single lines of text, while an unfurled URL or some markdowned code might take up half the screen height.

**Comment by David-Mulder** [comment]
@blasten Figured it would be something like that, but the main thing of note is that even in that case you should be able to prevent visibile items from disappearing. I mean, the scrollbar and stuff will get totally messed up, but in comparison that's quite acceptable.

**Comment by hawkett** [comment]
Can support for variant sizes be added to the feature roadmap? Thx!

**Comment by blasten** [comment]
@hawkett This issue has been fixed in https://github.com/PolymerElements/iron-list/releases/tag/v1.1.5 :)
